/* Chinese (zh) terminology for grape varieties and wine regions.
 * Used only in the Chinese view: grape/region fields are free-text Latin
 * strings; here we map the internationally-known tokens to their standard
 * Chinese names and render them bilingually — 中文 (Latin) — so a guest can
 * still match the name on the bottle/label.
 *
 * Indigenous grapes (Plavac Mali, Pošip, Grk, Teran, Malvazija istarska…) and
 * small village/appellation names have no established Chinese name and are
 * intentionally left in Latin — that is the convention on premium Chinese
 * lists too. Producer/winery names are likewise kept in their original script
 * elsewhere. To add a translation, just add a token here.
 */
(function (g) {
  // Grape variety → standard Chinese name (rendered bilingually).
  g.ZH_GRAPE = {
    "Aligoté": "阿里高特",
    "Barbera": "巴贝拉",
    "Cabernet Franc": "品丽珠",
    "Cabernet Sauvignon": "赤霞珠",
    "Canaiolo": "卡内奥罗",
    "Carignane": "佳丽酿",
    "Carricante": "卡利坎特",
    "Chardonnay": "霞多丽",
    "Chenin Blanc": "白诗南",
    "Colorino": "科罗里诺",
    "Corvina": "科尔维纳",
    "Corvinone": "科尔维诺内",
    "Croatina": "克罗地纳",
    "Friulano": "弗留拉诺",
    "Gamay": "佳美",
    "Garnacha": "歌海娜",
    "Glera": "歌蕾拉",
    "Godello": "歌德约",
    "Graciano": "格拉西亚诺",
    "Grüner Veltliner": "绿维特利纳",
    "Malvasia": "玛尔维萨",
    "Mazuelo": "马苏埃洛",
    "Merlot": "美乐",
    "Muscat": "麝香",
    "Oseleta": "奥赛莱塔",
    "Petit Verdot": "小维铎",
    "Petite Sirah": "小西拉",
    "Pignolo": "皮诺洛",
    "Pinot Bianco": "白皮诺",
    "Pinot Blanc": "白皮诺",
    "Pinot Grigio": "灰皮诺",
    "Pinot Gris": "灰皮诺",
    "Pinot Meunier": "莫尼耶皮诺",
    "Pinot Nero": "黑皮诺",
    "Pinot Noir": "黑皮诺",
    "Ribolla Gialla": "丽波拉",
    "Riesling": "雷司令",
    "Rondinella": "罗蒂内拉",
    "Sangiovese": "桑娇维塞",
    "Sangiovese Grosso": "大粒桑娇维塞",
    "Sauvignon": "长相思",
    "Sauvignon Blanc": "长相思",
    "Savagnin": "萨瓦涅",
    "Syrah": "西拉",
    "Sémillon": "赛美蓉",
    "Tempranillo": "添帕尼罗",
    "Vespolina": "韦斯波利纳",
    "Viura": "维尤拉",
    "Zinfandel": "仙粉黛",
    // Descriptive phrases (rendered Chinese-only — see ZH_ONLY below).
    "Autochthone bijele sorte": "本土白葡萄品种",
    "Autohtone dalmatinske sorte": "达尔马提亚本土品种",
    "Autohtone dalmatinske sorte (prošek)": "达尔马提亚本土品种",
    "Dalmatinske autohtone sorte": "达尔马提亚本土品种",
    "Španjolske sorte": "西班牙本土品种"
  };

  // Region → standard Chinese name (rendered bilingually). Villages and small
  // appellations without an established Chinese name are omitted on purpose.
  g.ZH_REGION = {
    "Alba": "阿尔巴",
    "Alexander Valley": "亚历山大谷",
    "Alsace": "阿尔萨斯",
    "Alsace Grand Cru": "阿尔萨斯特级园",
    "Alto Adige": "上阿迪杰",
    "Alto Piemonte": "上皮埃蒙特",
    "Aube": "奥布",
    "Barbaresco": "巴巴莱斯科",
    "Barolo": "巴罗洛",
    "Beaujolais": "博若莱",
    "Bolgheri": "博格利",
    "Bordeaux": "波尔多",
    "Bourgogne": "勃艮第",
    "California": "加利福尼亚",
    "Chablis": "夏布利",
    "Chablis Grand Cru": "夏布利特级园",
    "Champagne": "香槟",
    "Chassagne-Montrachet": "夏山-蒙哈榭",
    "Chianti Classico": "经典基安蒂",
    "Château-Chalon": "夏隆堡",
    "Corton-Charlemagne": "高登-查理曼",
    "Costa Toscana": "托斯卡纳海岸",
    "Côte Chalonnaise": "夏隆内丘",
    "Côte de Beaune": "博讷丘",
    "Côte de Nuits": "夜丘",
    "Dalmacija": "达尔马提亚",
    "Emilia-Romagna": "艾米利亚-罗马涅",
    "España": "西班牙",
    "Etna": "埃特纳",
    "France": "法国",
    "Franciacorta": "弗朗齐亚柯达",
    "Friuli": "弗留利",
    "Friuli Isonzo": "弗留利伊松佐",
    "Gevrey-Chambertin": "热夫雷-香贝丹",
    "Gorizia": "戈里齐亚",
    "Himalaya": "喜马拉雅",
    "Istra": "伊斯特拉",
    "Jura": "汝拉",
    "Kontinentalna Hrvatska": "克罗地亚内陆",
    "Langhe": "朗格",
    "Loire": "卢瓦尔",
    "Lombardia": "伦巴第",
    "Maremma": "马雷玛",
    "Meursault": "默尔索",
    "Montalcino": "蒙塔奇诺",
    "Morey-Saint-Denis": "莫雷-圣丹尼",
    "Mosel": "摩泽尔",
    "Mount Veeder": "维德山",
    "Napa Valley": "纳帕谷",
    "Nuits-Saint-Georges": "夜圣乔治",
    "Oregon": "俄勒冈",
    "Pantelleria": "潘泰莱里亚",
    "Pfalz": "法尔兹",
    "Piemonte": "皮埃蒙特",
    "Pomerol": "波美侯",
    "Pommard": "玻玛",
    "Pouilly-Fuissé": "普伊-富赛",
    "Puligny-Montrachet": "普利尼-蒙哈榭",
    "Reims": "兰斯",
    "Rheinhessen": "莱茵黑森",
    "Rioja": "里奥哈",
    "Saar": "萨尔",
    "Saint-Aubin": "圣欧班",
    "Saint-Estèphe": "圣爱斯泰夫",
    "Saint-Julien": "圣朱利安",
    "Saint-Véran": "圣维朗",
    "Saint-Émilion": "圣埃美隆",
    "Sancerre": "桑塞尔",
    "Santa Cruz Mountains": "圣克鲁兹山",
    "Santenay": "桑特奈",
    "Sauternes": "苏玳",
    "Sicilia": "西西里",
    "Sonoma Coast": "索诺玛海岸",
    "Spring Mountain": "春山",
    "Sta. Rita Hills": "圣丽塔山",
    "Toscana": "托斯卡纳",
    "Valpolicella": "瓦坡里切拉",
    "Valpolicella Classica": "经典瓦坡里切拉",
    "Veneto": "威尼托",
    "Volnay": "沃尔奈",
    "Vosne-Romanée": "沃恩-罗曼尼",
    "Wachau": "瓦豪",
    "Willamette Valley": "威拉米特谷",
    "Yunnan": "云南",
    "Épernay": "埃佩尔奈",
    // Country-level tokens used in the producer terroir line.
    "Slovenia": "斯洛文尼亚",
    "Austria": "奥地利",
    "China": "中国",
    "Romagna": "罗马涅",
    "Muscadet": "慕斯卡德"
  };

  // Tokens rendered Chinese-only (no Latin in parentheses) — descriptive
  // phrases where the original wording carries no brand/label value.
  g.ZH_ONLY = {
    "Autochthone bijele sorte": 1,
    "Autohtone dalmatinske sorte": 1,
    "Autohtone dalmatinske sorte (prošek)": 1,
    "Dalmatinske autohtone sorte": 1,
    "Španjolske sorte": 1
  };
})(window);
