# -*- coding: utf-8 -*-
"""French batch two, with the owner's corrections (2026-08-12).

Barton takes his phrasing, Rousseau's monopole stops being an adjective,
l'Écu explains why a rock's age is on the card at all (the cuvées are named
after it), Mikulski opens on what was its last line, Crochet and Pattes Loup
are rewritten rather than reordered, and Selosse gains the link that was
missing: what Spain showed him was two ways of giving wine time.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Château de Pez"] = {
 "hr": "Drži ga Louis Roederer, šampanjska kuća koja je i sama na ovoj karti — a prije njih, dva stoljeća, obitelj Pontac: ista koja je držala Haut-Brion i time praktički izmislila ideju da vino nosi ime svoje zemlje. Uz Calon-Ségur je najstarije imanje u Saint-Estèpheu. 48 hektara sjevernog Médoca: cabernet čvrste građe i tamnog voća, vino koje se ne otvara prerano.",
 "en": "It belongs to Louis Roederer, the Champagne house that is itself on this list — and before them, for two centuries, to the Pontac family: the same one that held Haut-Brion and so all but invented the idea that a wine carries the name of its land. With Calon-Ségur it is the oldest estate in Saint-Estèphe. 48 hectares of the northern Médoc: Cabernet of firm build and dark fruit, a wine not to be opened early.",
 "it": "È di Louis Roederer, la maison di Champagne che sta anch'essa su questa carta — e prima di loro, per due secoli, della famiglia Pontac: la stessa che teneva Haut-Brion e che così ha praticamente inventato l'idea che un vino porti il nome della propria terra. Con Calon-Ségur è la tenuta più antica di Saint-Estèphe. 48 ettari di Médoc settentrionale: cabernet di struttura salda e frutto scuro, un vino da non aprire troppo presto.",
 "fr": "Il appartient à Louis Roederer, la maison de Champagne qui figure elle aussi sur cette carte — et avant eux, deux siècles durant, à la famille Pontac : celle-là même qui tenait Haut-Brion et qui a ainsi quasiment inventé l'idée qu'un vin porte le nom de sa terre. Avec Calon-Ségur, c'est le plus ancien domaine de Saint-Estèphe. 48 hectares de Médoc nord : un cabernet de charpente ferme et de fruit sombre, un vin qu'on n'ouvre pas trop tôt.",
 "de": "Es gehört Louis Roederer, dem Champagnerhaus, das selbst auf dieser Karte steht — und davor, zwei Jahrhunderte lang, der Familie Pontac: derselben, die Haut-Brion hielt und damit die Idee, dass ein Wein den Namen seines Bodens trägt, praktisch erfunden hat. Mit Calon-Ségur ist es das älteste Gut in Saint-Estèphe. 48 Hektar nördliches Médoc: Cabernet von festem Bau und dunkler Frucht, ein Wein, den man nicht zu früh öffnet.",
 "sl": "Drži ga Louis Roederer, šampanjska hiša, ki je tudi sama na tej karti — pred njimi pa dve stoletji družina Pontac: ista, ki je imela Haut-Brion in s tem tako rekoč iznašla misel, da vino nosi ime svoje zemlje. Skupaj s Calon-Ségurjem je najstarejše posestvo v Saint-Estèphu. 48 hektarov severnega Médoca: cabernet trdne gradnje in temnega sadja, vino, ki se ne odpira prezgodaj.",
 "es": "Lo tiene Louis Roederer, la casa de Champaña que está también en esta carta — y antes que ellos, durante dos siglos, la familia Pontac: la misma que tuvo Haut-Brion y que así prácticamente inventó la idea de que un vino lleve el nombre de su tierra. Con Calon-Ségur es la finca más antigua de Saint-Estèphe. 48 hectáreas del Médoc norte: Cabernet de estructura firme y fruta oscura, un vino que no se abre pronto.",
 "zh": "它属于路易王妃——那家香槟酒庄也在这份酒单上；而在他们之前的两百年，它属于蓬塔克家族：正是持有侯伯王的那一家，也几乎由他们发明了「酒以其土地为名」这个念头。它与 Calon-Ségur 同为圣埃斯泰夫最古老的庄园。48 公顷北梅多克：骨架结实、果味深沉的赤霞珠，一款不该太早开的酒。"
}

NEW["Château Troplong Mondot"] = {
 "hr": "Najviša točka Saint-Émiliona, 110 m — što u ovom kraju znači svježije noći i berbu koja nikad ne izgori. Premier Grand Cru Classé B. Uz podrum ide i restoran s Michelinovom zvjezdicom, Les Belles Perdrix, pa je ovo jedna od rijetkih bordoških adresa na kojoj se vino i jede, ne samo kuša.",
 "en": "The highest point in Saint-Émilion, 110 m — which here means cooler nights and a harvest that never burns. Premier Grand Cru Classé B. The cellar comes with a Michelin-starred restaurant, Les Belles Perdrix, which makes this one of the few Bordeaux addresses where the wine is eaten with rather than only tasted.",
 "it": "Il punto più alto di Saint-Émilion, 110 m — che da queste parti vuol dire notti più fresche e una vendemmia che non brucia mai. Premier Grand Cru Classé B. Con la cantina va anche un ristorante stellato Michelin, Les Belles Perdrix, il che fa di questo uno dei pochi indirizzi bordolesi dove il vino si mangia, non solo si assaggia.",
 "fr": "Le point le plus haut de Saint-Émilion, 110 m — ce qui ici veut dire des nuits plus fraîches et une vendange qui ne brûle jamais. Premier Grand Cru Classé B. À la cave s'ajoute un restaurant étoilé, Les Belles Perdrix, ce qui en fait l'une des rares adresses bordelaises où l'on mange le vin au lieu de seulement le déguster.",
 "de": "Der höchste Punkt von Saint-Émilion, 110 m — was hier kühlere Nächte heißt und eine Lese, die nie verbrennt. Premier Grand Cru Classé B. Zum Keller gehört ein Michelin-besterntes Restaurant, Les Belles Perdrix, womit dies eine der wenigen Bordeaux-Adressen ist, an denen der Wein gegessen und nicht nur verkostet wird.",
 "sl": "Najvišja točka Saint-Émiliona, 110 m — kar v teh krajih pomeni hladnejše noči in trgatev, ki nikoli ne zgori. Premier Grand Cru Classé B. Ob kleti stoji restavracija z Michelinovo zvezdico, Les Belles Perdrix, zato je to eden redkih bordojskih naslovov, kjer se vino tudi je, ne le pokuša.",
 "es": "El punto más alto de Saint-Émilion, 110 m — lo que aquí significa noches más frescas y una vendimia que nunca se quema. Premier Grand Cru Classé B. Junto a la bodega hay un restaurante con estrella Michelin, Les Belles Perdrix, lo que hace de esta una de las pocas direcciones bordelesas donde el vino se come y no sólo se cata.",
 "zh": "圣埃美隆的最高点，110 米——在这一带，这意味着更凉的夜晚，以及一场永远不会被晒垮的采收。一级特等园 B 级。酒窖旁还有一家米其林星级餐厅 Les Belles Perdrix，所以这是波尔多少数几个「酒是拿来吃的、不只是拿来品的」地址之一。"
}

NEW["Château Léoville Barton"] = {
 "hr": "Kuća koja cijenu nikad nije podizala koliko je tržište htjelo platiti — a drži je ista obitelj gotovo 200 godina, što je u Bordeauxu rijetkost. Dvorca s etikete ovdje zapravo nema: to je Langoa Barton, susjedno imanje, i oba se vina do danas rade ondje. Thomas Barton došao je iz Irske u Bordeaux, a njegov unuk Hugh kupio je 1826. dio velikog imanja Léoville.",
 "en": "A house that never pushed its price as high as the market was willing to pay — and the same family has held it for nearly 200 years, which in Bordeaux is a rarity. There is in fact no château of its own here: the building on the label is Langoa Barton, the neighbouring estate, and both wines are still made there. Thomas Barton came from Ireland to Bordeaux, and his grandson Hugh bought part of the great Léoville estate in 1826.",
 "it": "Una casa che non ha mai alzato il prezzo fin dove il mercato era disposto a pagare — e la tiene la stessa famiglia da quasi 200 anni, cosa rara a Bordeaux. Un proprio château qui in realtà non c'è: l'edificio in etichetta è Langoa Barton, la tenuta accanto, e lì si fanno ancora entrambi i vini. Thomas Barton arrivò dall'Irlanda a Bordeaux, e suo nipote Hugh comprò nel 1826 una parte della grande tenuta Léoville.",
 "fr": "Une maison qui n'a jamais monté son prix jusqu'où le marché était prêt à payer — et la même famille la tient depuis presque 200 ans, ce qui à Bordeaux est rare. De château propre, il n'y en a pas ici : le bâtiment de l'étiquette est Langoa Barton, le domaine voisin, et les deux vins s'y font encore. Thomas Barton est venu d'Irlande à Bordeaux, et son petit-fils Hugh a acheté en 1826 une part du grand domaine de Léoville.",
 "de": "Ein Haus, das den Preis nie so weit hochgetrieben hat, wie der Markt zu zahlen bereit war — und dieselbe Familie hält es seit fast 200 Jahren, was in Bordeaux selten ist. Ein eigenes Château gibt es hier gar nicht: Das Gebäude auf dem Etikett ist Langoa Barton, das Nachbargut, und dort werden beide Weine bis heute gemacht. Thomas Barton kam aus Irland nach Bordeaux, und sein Enkel Hugh kaufte 1826 einen Teil des großen Guts Léoville.",
 "sl": "Hiša, ki cene nikoli ni dvigovala do tja, kamor jo je bil trg pripravljen plačati — in drži jo ista družina že skoraj 200 let, kar je v Bordeauxu redkost. Lastnega dvorca tu pravzaprav ni: stavba z etikete je Langoa Barton, sosednje posestvo, in obe vini še danes nastajata tam. Thomas Barton je prišel iz Irske v Bordeaux, njegov vnuk Hugh pa je leta 1826 kupil del velikega posestva Léoville.",
 "es": "Una casa que nunca subió el precio hasta donde el mercado estaba dispuesto a pagar — y la lleva la misma familia desde hace casi 200 años, algo raro en Burdeos. Château propio aquí no hay: el edificio de la etiqueta es Langoa Barton, la finca vecina, y allí se siguen haciendo los dos vinos. Thomas Barton llegó de Irlanda a Burdeos, y su nieto Hugh compró en 1826 una parte de la gran finca Léoville.",
 "zh": "一家从不把价格抬到市场愿意付的高度的酒庄——而且同一个家族持有了将近 200 年，这在波尔多是稀罕事。这里其实没有自己的城堡：酒标上那栋楼是隔壁的 Langoa Barton，两款酒至今都在那儿酿。托马斯·巴顿从爱尔兰来到波尔多，他的孙子休在 1826 年买下了雷奥维尔大庄园的一部分。"
}

NEW["Domaine Armand Rousseau"] = {
 "hr": "Dok su svi oko njega rasprodavali svoje komadiće, Armand Rousseau je desetljećima dokupovao — a počeo je s trsovima koje je naslijedio s 18 godina. Tridesetih je poslušao Raymonda Baudoina, čovjeka koji je burgundijske vinare nagovarao da vino prestanu prodavati u bačvi trgovcima i počnu ga puniti sami, pa je imanje među prvima stavilo vlastito ime na etiketu. Poginuo je u prometnoj nesreći 1959. Sin Charles dokupio je Clos de Bèze i monopol Clos des Ruchottes; danas su tu Éric i kći Cyrielle, koja je prije vina studirala geologiju.",
 "en": "While everyone around him was selling off their scraps, Armand Rousseau spent decades buying more — starting with the vines he inherited at 18. In the 1930s he listened to Raymond Baudoin, the man who talked Burgundy's growers into stopping selling wine to merchants by the cask and bottling it themselves, and the estate became one of the first to put its own name on the label. He died in a road accident in 1959. His son Charles added Clos de Bèze and the Clos des Ruchottes monopole; today it is Éric and his daughter Cyrielle, who studied geology before wine.",
 "it": "Mentre tutti attorno a lui svendevano i loro pezzetti, Armand Rousseau per decenni comprava — a partire dalle viti ereditate a 18 anni. Negli anni Trenta diede retta a Raymond Baudoin, l'uomo che convinse i vignaioli di Borgogna a smettere di vendere il vino in botte ai negozianti e a imbottigliarlo da sé, e la tenuta fu tra le prime a mettere in etichetta il proprio nome. Morì in un incidente stradale nel 1959. Il figlio Charles aggiunse il Clos de Bèze e il monopole Clos des Ruchottes; oggi ci sono Éric e la figlia Cyrielle, che prima del vino ha studiato geologia.",
 "fr": "Pendant que tout le monde autour de lui bradait ses parcelles, Armand Rousseau a passé des décennies à en racheter — en partant des vignes héritées à 18 ans. Dans les années 1930, il a écouté Raymond Baudoin, l'homme qui a convaincu les vignerons bourguignons de cesser de vendre leur vin en fût au négoce et de le mettre eux-mêmes en bouteille, et le domaine fut l'un des premiers à porter son propre nom sur l'étiquette. Il est mort dans un accident de la route en 1959. Son fils Charles a ajouté le Clos de Bèze et le monopole du Clos des Ruchottes ; aujourd'hui ce sont Éric et sa fille Cyrielle, qui a étudié la géologie avant le vin.",
 "de": "Während rings um ihn alle ihre Stücke verkauften, kaufte Armand Rousseau jahrzehntelang zu — angefangen mit den Reben, die er mit 18 erbte. In den 1930ern hörte er auf Raymond Baudoin, den Mann, der Burgunds Winzer dazu brachte, ihren Wein nicht länger fassweise an den Handel zu geben, sondern selbst zu füllen; das Gut war eines der ersten mit dem eigenen Namen auf dem Etikett. 1959 kam er bei einem Verkehrsunfall ums Leben. Sohn Charles kaufte Clos de Bèze und das Monopol Clos des Ruchottes dazu; heute sind es Éric und seine Tochter Cyrielle, die vor dem Wein Geologie studiert hat.",
 "sl": "Medtem ko so vsi okrog njega razprodajali svoje koščke, je Armand Rousseau desetletja dokupoval — začel je s trtami, ki jih je podedoval pri 18 letih. V tridesetih je poslušal Raymonda Baudoina, človeka, ki je burgundske vinarje pregovoril, naj vina nehajo prodajati trgovcem v sodih in ga začnejo polniti sami, in posestvo je bilo med prvimi z lastnim imenom na etiketi. Leta 1959 je umrl v prometni nesreči. Sin Charles je dokupil Clos de Bèze in monopol Clos des Ruchottes; danes sta tu Éric in hči Cyrielle, ki je pred vinom študirala geologijo.",
 "es": "Mientras todos a su alrededor malvendían sus pedazos, Armand Rousseau se pasó décadas comprando — empezando por las cepas que heredó a los 18 años. En los años treinta hizo caso a Raymond Baudoin, el hombre que convenció a los viticultores de Borgoña de dejar de vender el vino en barrica al comercio y embotellarlo ellos mismos, y la finca fue de las primeras en poner su propio nombre en la etiqueta. Murió en un accidente de tráfico en 1959. Su hijo Charles añadió el Clos de Bèze y el monopole Clos des Ruchottes; hoy están Éric y su hija Cyrielle, que antes del vino estudió geología.",
 "zh": "当周围的人纷纷把自家的小块地卖掉时，阿尔芒·卢梭却用几十年一直在买进——起点是他 18 岁继承的那几行老藤。三十年代，他听了雷蒙·博杜安的话——正是此人劝动勃艮第酒农别再把酒整桶卖给酒商、改为自己装瓶——于是这座酒庄成了最早把自家名字印上酒标的之一。1959 年，他死于一场车祸。儿子夏尔又买下 Clos de Bèze 与独占园 Clos des Ruchottes；如今是埃里克和女儿西里埃勒，她在做酒之前学的是地质。"
}

NEW["Michel Forgeron"] = {
 "hr": "U kraju u kojem velike kuće otkupljuju tuđe, oni ne prodaju nikome. Obiteljski vinogradari iz Segonzaca, u samom srcu Grande Champagne: sami uzgajaju, sami destiliraju, sami čekaju.",
 "en": "In a region where the great houses buy in other people's, they sell to nobody. A family of growers in Segonzac, in the very heart of Grande Champagne: they grow it, distil it and wait it out themselves.",
 "it": "In una zona dove le grandi case comprano l'altrui, loro non vendono a nessuno. Viticoltori di famiglia a Segonzac, nel cuore stesso della Grande Champagne: coltivano, distillano e aspettano da soli.",
 "fr": "Dans une région où les grandes maisons achètent celui des autres, eux ne vendent à personne. Vignerons de famille à Segonzac, au cœur même de la Grande Champagne : ils cultivent, distillent et attendent eux-mêmes.",
 "de": "In einer Gegend, in der die großen Häuser den Brand anderer aufkaufen, verkaufen sie an niemanden. Eine Winzerfamilie in Segonzac, mitten im Herzen der Grande Champagne: Sie bauen selbst an, brennen selbst und warten selbst.",
 "sl": "V kraju, kjer velike hiše odkupujejo tuje, oni ne prodajajo nikomur. Družinski vinogradniki iz Segonzaca, v samem srcu Grande Champagne: sami pridelujejo, sami žgejo, sami čakajo.",
 "es": "En una comarca donde las grandes casas compran lo de los demás, ellos no venden a nadie. Viticultores de familia en Segonzac, en pleno corazón de la Grande Champagne: cultivan, destilan y esperan ellos mismos.",
 "zh": "在这片大厂靠收购别人原酒过日子的地方，他们不卖给任何人。塞贡扎克的家族种植者，就在大香槟区的正中心：自己种，自己蒸馏，自己等。"
}

NEW["Château de Beaulon"] = {
 "hr": "Ovdje se ne žuri: bačve leže u vlažnom podrumu desetljećima, i cognac izlazi mekan umjesto oštar. Dvorac je iz 15. stoljeća, pod vinogradom je plava glina, a vrtovi su zaštićeni spomenik.",
 "en": "Nobody hurries here: the casks lie in a damp cellar for decades, and the cognac comes out soft instead of sharp. The château is 15th century, there is blue clay under the vineyard, and the gardens are a listed monument.",
 "it": "Qui non si ha fretta: le botti restano decenni in una cantina umida, e il cognac esce morbido invece che tagliente. Il castello è del Quattrocento, sotto la vigna c'è argilla azzurra e i giardini sono monumento tutelato.",
 "fr": "Ici, on ne se presse pas : les fûts reposent des décennies dans un chai humide, et le cognac en sort tendre au lieu d'être tranchant. Le château est du XVe siècle, il y a de l'argile bleue sous la vigne, et les jardins sont classés.",
 "de": "Hier wird nicht geeilt: Die Fässer liegen jahrzehntelang in einem feuchten Keller, und der Cognac kommt weich statt scharf heraus. Das Schloss ist aus dem 15. Jahrhundert, unter dem Weinberg liegt blauer Ton, und die Gärten stehen unter Denkmalschutz.",
 "sl": "Tu se nihče ne mudi: sodi ležijo v vlažni kleti desetletja, in konjak pride ven mehak namesto oster. Grad je iz 15. stoletja, pod vinogradom je modra glina, vrtovi pa so zaščiten spomenik.",
 "es": "Aquí no se corre: las barricas reposan décadas en una bodega húmeda, y el coñac sale suave en vez de afilado. El castillo es del siglo XV, bajo la viña hay arcilla azul y los jardines son monumento protegido.",
 "zh": "这里不赶时间：桶在潮湿的酒窖里一躺就是几十年，干邑出来是柔的，而不是冲的。城堡建于 15 世纪，葡萄园下面是蓝黏土，花园则是受保护的古迹。"
}

NEW["Bourdy"] = {
 "hr": "U podrumu stoji arhiva kakva se drugdje ne vidi: bijela vina do 1911., a Château-Chalon do 1865. Ista obitelj na istom mjestu od 1475. — 15 naraštaja, što ovo imanje kod Arlaya čini jednim od najstarijih na svijetu koje nikad nije promijenilo prezime. Danas ga vode braća Jean-François i Jean-Philippe na 10 hektara, u biodinamici. Vin jaune se ionako mjeri desetljećima, pa je arhiva ovdje samo dosljednost.",
 "en": "In the cellar there is an archive of a kind you do not see elsewhere: whites back to 1911, and Château-Chalon back to 1865. The same family in the same place since 1475 — 15 generations, which makes this estate near Arlay one of the oldest in the world never to have changed its surname. The brothers Jean-François and Jean-Philippe run its 10 hectares today, biodynamically. Vin jaune is measured in decades anyway, so the archive here is only consistency.",
 "it": "In cantina c'è un archivio che altrove non si vede: bianchi fino al 1911 e Château-Chalon fino al 1865. La stessa famiglia nello stesso posto dal 1475 — 15 generazioni, il che fa di questa tenuta presso Arlay una delle più antiche al mondo a non aver mai cambiato cognome. Oggi i fratelli Jean-François e Jean-Philippe ne conducono 10 ettari, in biodinamica. Il vin jaune si misura comunque in decenni, e l'archivio qui è solo coerenza.",
 "fr": "À la cave, il y a des archives comme on n'en voit pas ailleurs : des blancs jusqu'à 1911, et du Château-Chalon jusqu'à 1865. La même famille au même endroit depuis 1475 — 15 générations, ce qui fait de ce domaine près d'Arlay l'un des plus anciens au monde à n'avoir jamais changé de nom. Les frères Jean-François et Jean-Philippe en mènent aujourd'hui 10 hectares, en biodynamie. Le vin jaune se mesure de toute façon en décennies : l'archive n'est ici que de la cohérence.",
 "de": "Im Keller liegt ein Archiv, wie man es sonst nicht sieht: Weiße bis 1911 und Château-Chalon bis 1865. Dieselbe Familie am selben Ort seit 1475 — 15 Generationen, was dieses Gut bei Arlay zu einem der ältesten der Welt macht, das nie den Namen gewechselt hat. Heute führen die Brüder Jean-François und Jean-Philippe seine 10 Hektar, biodynamisch. Vin jaune misst man ohnehin in Jahrzehnten, das Archiv ist hier nur Folgerichtigkeit.",
 "sl": "V kleti stoji arhiv, kakršnega drugod ni videti: bela vina do 1911 in Château-Chalon do 1865. Ista družina na istem mestu od 1475 — 15 rodov, kar to posestvo pri Arlayu uvršča med najstarejša na svetu, ki nikoli niso zamenjala priimka. Danes njegovih 10 hektarov vodita brata Jean-François in Jean-Philippe, v biodinamiki. Vin jaune se tako ali tako meri v desetletjih, arhiv je tu le doslednost.",
 "es": "En la bodega hay un archivo como no se ve en otros sitios: blancos hasta 1911 y Château-Chalon hasta 1865. La misma familia en el mismo lugar desde 1475 — 15 generaciones, lo que hace de esta finca cerca de Arlay una de las más antiguas del mundo que nunca cambió de apellido. Hoy los hermanos Jean-François y Jean-Philippe llevan sus 10 hectáreas, en biodinámica. El vin jaune se mide de todos modos en décadas: aquí el archivo es sólo coherencia.",
 "zh": "酒窖里有一份别处见不到的档案：白葡萄酒可回溯到 1911 年，夏隆堡则到 1865 年。同一个家族在同一个地方待了自 1475 年起——15 代人，这让阿尔莱附近的这座酒庄成为世上从未改过姓氏的最古老庄园之一。如今由让-弗朗索瓦与让-菲利普兄弟打理这 10 公顷，采用生物动力。黄酒本来就以十年为单位计量，所以这份档案在这里只是理所当然。"
}

NEW["l'Écu"] = {
 "hr": "Cuvée ovdje nose imena kamena ispod loze — pa Granite dolazi s 3 hektara granita starog 400 milijuna godina, s trsova od 45 do 55 godina. Ekološki certifikat imaju od 1972., kad je ostatak Francuske još prskao sve što se prskati dalo; Guy Bossard, koji je to pokrenuo, bio je jedan od prvih biodinamičara u zemlji, a danas imanje vodi Fred Niger na 17 hektara. Muscadet koji se ne pije uz kamenice iz navike nego zato što je vino.",
 "en": "The cuvées here are named after the rock under the vines — so Granite comes from 3 hectares of granite 400 million years old, off vines of 45 to 55 years. They have been certified organic since 1972, when the rest of France was still spraying anything that could be sprayed; Guy Bossard, who started it, was one of the country's first biodynamic growers, and Fred Niger runs the 17 hectares today. Muscadet you drink with oysters not out of habit but because it is wine.",
 "it": "Qui le cuvée portano il nome della roccia sotto la vigna — così il Granite viene da 3 ettari di granito vecchio 400 milioni di anni, da viti di 45-55 anni. Sono certificati biologici dal 1972, quando il resto della Francia irrorava ancora tutto ciò che si poteva irrorare; Guy Bossard, che avviò la cosa, fu uno dei primi biodinamici del paese, e oggi la tenuta di 17 ettari è di Fred Niger. Un Muscadet che si beve con le ostriche non per abitudine ma perché è vino.",
 "fr": "Ici, les cuvées portent le nom de la roche sous la vigne — ainsi Granite vient de 3 hectares de granite vieux de 400 millions d'années, de vignes de 45 à 55 ans. Ils sont certifiés bio depuis 1972, quand le reste de la France traitait encore tout ce qui pouvait l'être ; Guy Bossard, qui a lancé cela, fut l'un des premiers biodynamistes du pays, et Fred Niger mène aujourd'hui les 17 hectares. Un muscadet qu'on boit avec les huîtres non par habitude mais parce que c'est du vin.",
 "de": "Die Cuvées tragen hier den Namen des Gesteins unter den Reben — Granite kommt also von 3 Hektar 400 Millionen Jahre altem Granit, von 45 bis 55 Jahre alten Stöcken. Bio-zertifiziert sind sie seit 1972, als der Rest Frankreichs noch alles spritzte, was sich spritzen ließ; Guy Bossard, der damit anfing, war einer der ersten Biodynamiker des Landes, und heute führt Fred Niger die 17 Hektar. Ein Muscadet, den man zu Austern nicht aus Gewohnheit trinkt, sondern weil er Wein ist.",
 "sl": "Cuvéeji tu nosijo imena kamnine pod trtami — Granite tako prihaja s 3 hektarov granita, starega 400 milijonov let, s trt, starih od 45 do 55 let. Ekološki certifikat imajo od leta 1972, ko je preostala Francija še škropila vse, kar se je dalo poškropiti; Guy Bossard, ki je to začel, je bil med prvimi biodinamiki v državi, danes pa 17 hektarov vodi Fred Niger. Muscadet, ki se ob ostrigah ne pije iz navade, ampak zato, ker je vino.",
 "es": "Aquí las cuvées llevan el nombre de la roca bajo la viña — así el Granite viene de 3 hectáreas de granito de 400 millones de años, de cepas de 45 a 55 años. Están certificados en ecológico desde 1972, cuando el resto de Francia aún fumigaba todo lo que se podía fumigar; Guy Bossard, que lo puso en marcha, fue uno de los primeros biodinámicos del país, y hoy Fred Niger lleva las 17 hectáreas. Un Muscadet que se bebe con ostras no por costumbre sino porque es vino.",
 "zh": "这里的酒款以藤下的岩石命名——所以 Granite 来自 3 公顷、有 4 亿年历史的花岗岩，藤龄 45 到 55 年。他们自 1972 年起就有有机认证，那时法国其余地方还在喷洒一切能喷的东西；开启这一切的居伊·博萨尔，是法国最早的生物动力农之一，如今这 17 公顷由弗雷德·尼热打理。这是一款喝它配生蚝不是出于习惯、而是因为它本身就是酒的密斯卡岱。"
}

NEW["Mikulski"] = {
 "hr": "Poljsko prezime na burgundijskoj etiketi nije marketing nego cijelo jedno stoljeće. Otac mu je bio poručnik Mieczysław Mikulski, koji je 1939. pobjegao iz okupirane Poljske u Englesku i borio se u slobodnim poljskim postrojbama. Sin je završio u Meursaultu: François je godinama radio uz ujaka Pierrea Boillota, a nakon ujakove smrti naslijedio prve parcele.",
 "en": "A Polish surname on a Burgundy label is not marketing but a whole century. His father was Lieutenant Mieczysław Mikulski, who escaped occupied Poland for England in 1939 and fought with the Free Polish forces. The son ended up in Meursault: François worked for years alongside his uncle Pierre Boillot, and inherited his first parcels after his uncle's death.",
 "it": "Un cognome polacco su un'etichetta di Borgogna non è marketing ma un secolo intero. Suo padre era il tenente Mieczysław Mikulski, fuggito nel 1939 dalla Polonia occupata in Inghilterra, dove combatté con le forze polacche libere. Il figlio è finito a Meursault: François ha lavorato per anni accanto allo zio Pierre Boillot, e alla morte dello zio ha ereditato le prime parcelle.",
 "fr": "Un nom polonais sur une étiquette bourguignonne, ce n'est pas du marketing mais tout un siècle. Son père était le lieutenant Mieczysław Mikulski, qui a fui la Pologne occupée pour l'Angleterre en 1939 et s'est battu dans les forces polonaises libres. Le fils a atterri à Meursault : François a travaillé des années aux côtés de son oncle Pierre Boillot, et a hérité de ses premières parcelles à la mort de celui-ci.",
 "de": "Ein polnischer Nachname auf einem Burgunder-Etikett ist kein Marketing, sondern ein ganzes Jahrhundert. Sein Vater war Leutnant Mieczysław Mikulski, der 1939 aus dem besetzten Polen nach England floh und in den freien polnischen Verbänden kämpfte. Der Sohn landete in Meursault: François arbeitete jahrelang an der Seite seines Onkels Pierre Boillot und erbte nach dessen Tod die ersten Parzellen.",
 "sl": "Poljski priimek na burgundski etiketi ni marketing, ampak celo stoletje. Njegov oče je bil poročnik Mieczysław Mikulski, ki je leta 1939 iz zasedene Poljske pobegnil v Anglijo in se boril v svobodnih poljskih enotah. Sin je pristal v Meursaultu: François je leta delal ob stricu Pierru Boillotu, po stričevi smrti pa podedoval prve parcele.",
 "es": "Un apellido polaco en una etiqueta de Borgoña no es marketing sino todo un siglo. Su padre fue el teniente Mieczysław Mikulski, que en 1939 huyó de la Polonia ocupada a Inglaterra y combatió en las fuerzas polacas libres. El hijo acabó en Meursault: François trabajó años junto a su tío Pierre Boillot, y heredó sus primeras parcelas a la muerte de este.",
 "zh": "勃艮第酒标上的一个波兰姓氏，不是营销手法，而是整整一个世纪。他父亲是米耶奇斯瓦夫·米库尔斯基中尉，1939 年从被占领的波兰逃到英国，在自由波兰部队里作战。儿子最后落在默尔索：弗朗索瓦多年在舅舅皮埃尔·布瓦洛身边做事，舅舅去世后继承了最初的几块园地。"
}

NEW["Crochet"] = {
 "hr": "Sancerre se razlikuje po kamenu, ne po sorti — a 10 hektara Françoisa Crocheta dodiruje sva tri tla Sancerrea: caillottes, vapnenačko kamenje; terres blanches, bijelu glinu s vapnencem; i silex, kremen, onaj koji vinu daje dim. Enologiju je studirao u Beauneu — u Burgundiji, ne u Sancerreu — i vratio se u Bué preuzeti očevo imanje. U ekološki uzgoj prešao je 2017., a naša berba 2023. prva je koja nosi certifikat.",
 "en": "Sancerre differs by its stone, not by its grape — and François Crochet's 10 hectares touch all three of Sancerre's soils: caillottes, limestone pebbles; terres blanches, white clay over limestone; and silex, flint, the one that puts the smoke in the wine. He studied oenology in Beaune — in Burgundy, not in Sancerre — and came back to Bué to take on his father's estate. He converted to organic farming in 2017, and our 2023 is the first vintage to carry the certificate.",
 "it": "Sancerre si distingue per la pietra, non per il vitigno — e i 10 ettari di François Crochet toccano tutti e tre i suoli di Sancerre: caillottes, sassi calcarei; terres blanches, argilla bianca su calcare; e silex, la selce, quella che mette il fumo nel vino. Ha studiato enologia a Beaune — in Borgogna, non a Sancerre — ed è tornato a Bué a prendere la tenuta del padre. È passato al biologico nel 2017, e la nostra annata 2023 è la prima con il certificato.",
 "fr": "Sancerre se distingue par la pierre, pas par le cépage — et les 10 hectares de François Crochet touchent les trois sols de Sancerre : caillottes, cailloux calcaires ; terres blanches, argile blanche sur calcaire ; et silex, celui qui met la fumée dans le vin. Il a étudié l'œnologie à Beaune — en Bourgogne, pas à Sancerre — et il est rentré à Bué reprendre le domaine de son père. Il est passé en bio en 2017, et notre 2023 est le premier millésime certifié.",
 "de": "Sancerre unterscheidet sich durch den Stein, nicht durch die Rebsorte — und François Crochets 10 Hektar berühren alle drei Böden von Sancerre: caillottes, Kalkgeröll; terres blanches, weißer Ton über Kalk; und silex, Feuerstein, jener, der den Rauch in den Wein bringt. Önologie studierte er in Beaune — im Burgund, nicht in Sancerre — und kam nach Bué zurück, um das Gut des Vaters zu übernehmen. 2017 stellte er auf biologischen Anbau um, und unser 2023er ist der erste zertifizierte Jahrgang.",
 "sl": "Sancerre se razlikuje po kamnu, ne po sorti — in 10 hektarov Françoisa Crocheta se dotika vseh treh tal Sancerra: caillottes, apnenčastega kamenja; terres blanches, bele gline na apnencu; in silexa, kremena, tistega, ki vinu da dim. Enologijo je študiral v Beaunu — v Burgundiji, ne v Sancerru — in se vrnil v Bué prevzet očetovo posestvo. Na ekološko pridelavo je prešel leta 2017, naš letnik 2023 pa je prvi s certifikatom.",
 "es": "Sancerre se distingue por la piedra, no por la variedad — y las 10 hectáreas de François Crochet tocan los tres suelos de Sancerre: caillottes, guijarros calizos; terres blanches, arcilla blanca sobre caliza; y silex, el pedernal, el que pone el humo en el vino. Estudió enología en Beaune — en Borgoña, no en Sancerre — y volvió a Bué a tomar la finca de su padre. Pasó a ecológico en 2017, y nuestra añada 2023 es la primera con certificado.",
 "zh": "桑塞尔的分别在石头，不在品种——而弗朗索瓦·克罗谢的 10 公顷恰好触到桑塞尔的三种土壤：caillottes，石灰岩碎石；terres blanches，石灰岩上的白黏土；以及 silex，燧石，正是它把烟熏味放进酒里。他在博讷学的酿酒——在勃艮第，不在桑塞尔——之后回到 Bué 接手父亲的酒庄。2017 年转为有机，我们这瓶 2023 是第一个带认证的年份。"
}

NEW["Pattes Loup"] = {
 "hr": "Vino ovdje leži 36, katkad i 48 mjeseci prije nego što uđe u bocu — otud *mise tardive*, kasno punjenje, jedini opis koji Thomasu Picu treba. Vratio se iz škole u Beauneu u rodni Courgis i odmah svojih 8 hektara preveo na ekološki uzgoj, u Chablisu, gdje se to tada nije radilo; certifikat je stigao pet godina kasnije. Vrije na vlastitim kvascima, bez ičega dodanog. Pattes Loup doslovno znači vučje šape.",
 "en": "The wine here lies 36, sometimes 48 months before it goes into bottle — hence *mise tardive*, late bottling, the only description Thomas Pico needs. He came back from school in Beaune to his native Courgis and immediately turned his 8 hectares over to organic farming, in Chablis, where nobody did that then; the certificate came five years later. It ferments on its own yeasts, with nothing added. Pattes Loup means, literally, wolf paws.",
 "it": "Qui il vino resta 36, a volte 48 mesi prima di andare in bottiglia — di qui *mise tardive*, imbottigliamento tardivo, l'unica descrizione che serva a Thomas Pico. Tornato dalla scuola di Beaune nella natia Courgis, convertì subito i suoi 8 ettari al biologico, a Chablis, dove allora non lo faceva nessuno; la certificazione arrivò cinque anni dopo. Fermenta con i propri lieviti, senza nulla di aggiunto. Pattes Loup significa, alla lettera, zampe di lupo.",
 "fr": "Ici le vin repose 36, parfois 48 mois avant la mise — d'où *mise tardive*, la seule description dont Thomas Pico ait besoin. Rentré de l'école de Beaune dans son Courgis natal, il a aussitôt converti ses 8 hectares en bio, à Chablis, où personne ne le faisait alors ; la certification est venue cinq ans plus tard. Il fermente sur ses propres levures, sans rien d'ajouté. Pattes Loup, littéralement, ce sont des pattes de loup.",
 "de": "Der Wein liegt hier 36, manchmal 48 Monate, bevor er auf die Flasche kommt — daher *mise tardive*, späte Füllung, die einzige Beschreibung, die Thomas Pico braucht. Aus der Schule in Beaune kehrte er in sein Heimatdorf Courgis zurück und stellte seine 8 Hektar sofort auf biologischen Anbau um, in Chablis, wo das damals niemand tat; das Zertifikat kam fünf Jahre später. Vergoren wird mit eigenen Hefen, ohne Zusatz. Pattes Loup heißt wörtlich Wolfspfoten.",
 "sl": "Vino tu leži 36, včasih 48 mesecev, preden gre v steklenico — od tod *mise tardive*, pozno polnjenje, edini opis, ki ga Thomas Pico potrebuje. Iz šole v Beaunu se je vrnil v rodni Courgis in svojih 8 hektarov takoj prevedel na ekološko pridelavo, v Chablisu, kjer tega takrat ni delal nihče; certifikat je prišel pet let pozneje. Vre na lastnih kvasovkah, brez dodatkov. Pattes Loup dobesedno pomeni volčje tace.",
 "es": "Aquí el vino reposa 36, a veces 48 meses antes de ir a botella — de ahí *mise tardive*, embotellado tardío, la única descripción que Thomas Pico necesita. Volvió de la escuela de Beaune a su Courgis natal y pasó de inmediato sus 8 hectáreas a ecológico, en Chablis, donde entonces no lo hacía nadie; la certificación llegó cinco años después. Fermenta con sus propias levaduras, sin nada añadido. Pattes Loup significa, literalmente, patas de lobo.",
 "zh": "这里的酒要躺 36 个月、有时 48 个月才装瓶——所以叫 *mise tardive*，晚装瓶，这是托马·皮科唯一需要的说明。他从博讷念完书回到故乡 Courgis，立刻把自己的 8 公顷转成有机——在当时的夏布利，没有人这么干；认证是五年后才到手的。用自身酵母发酵，什么也不加。Pattes Loup 字面意思是：狼爪。"
}

NEW["Jacques Selosse"] = {
 "hr": "Trebalo mu je 6 godina prepirke sa šampanjskim odborom da dobije ono što je vidio u Jerezu: soleru. Dopustili su mu je 1986. Anselme Selosse učio je sedamdesetih u Burgundiji, kod ljudi koji su vjerovali da vino nastaje u vinogradu, i to je uvjerenje donio natrag u Avize — gdje ga tada nitko nije dijelio. Na istom putu po Španjolskoj vidio je dva načina na koja se vinu daje vrijeme: kod Lópeza de Heredije u Rioji, koji je i sam na ovoj karti, vina desetljećima leže u starom drvu, a u Jerezu solera svake godine miješa mlado sa starim, pa vino nikad ne kreće iz početka. Oboje je donio u Champagne, gdje se tada mjerilo samo koliko je vino svježe.",
 "en": "It took him 6 years of argument with Champagne's governing body to be allowed what he had seen in Jerez: a solera. They let him have it in 1986. Anselme Selosse trained in Burgundy in the 1970s, among people who believed wine is made in the vineyard, and brought that conviction back to Avize — where nobody then shared it. On the same trip through Spain he saw two ways of giving wine time: at López de Heredia in Rioja, who are themselves on this list, the wines lie for decades in old wood, and in Jerez the solera blends young with old every year, so the wine never starts from scratch. He brought both to Champagne, where the only measure then was how fresh a wine was.",
 "it": "Gli sono serviti 6 anni di discussioni con l'ente della Champagne per ottenere ciò che aveva visto a Jerez: una solera. Gliel'hanno concessa nel 1986. Anselme Selosse si era formato negli anni Settanta in Borgogna, fra gente convinta che il vino si faccia in vigna, e quella convinzione l'ha riportata ad Avize — dove allora non la condivideva nessuno. Nello stesso viaggio in Spagna vide due modi di dare tempo al vino: da López de Heredia in Rioja, anch'essi su questa carta, i vini restano decenni in legno vecchio, e a Jerez la solera mescola ogni anno il giovane col vecchio, così il vino non riparte mai da zero. Portò entrambi in Champagne, dove allora si misurava solo quanto un vino fosse fresco.",
 "fr": "Il lui a fallu 6 ans de discussions avec l'organisme de la Champagne pour obtenir ce qu'il avait vu à Jerez : une solera. On la lui a accordée en 1986. Anselme Selosse s'était formé dans les années 1970 en Bourgogne, chez des gens convaincus que le vin se fait à la vigne, et il a rapporté cette conviction à Avize — où personne alors ne la partageait. Au cours du même voyage en Espagne, il a vu deux façons de donner du temps au vin : chez López de Heredia en Rioja, eux aussi sur cette carte, les vins reposent des décennies dans du vieux bois, et à Jerez la solera mêle chaque année le jeune et le vieux, si bien que le vin ne repart jamais de zéro. Il a rapporté les deux en Champagne, où l'on ne mesurait alors que la fraîcheur.",
 "de": "Er brauchte 6 Jahre Streit mit dem Champagne-Verband, um zu bekommen, was er in Jerez gesehen hatte: eine Solera. 1986 wurde sie ihm erlaubt. Anselme Selosse hatte in den 1970ern im Burgund gelernt, bei Leuten, die glaubten, Wein entstehe im Weinberg, und diese Überzeugung nach Avize zurückgebracht — wo sie damals niemand teilte. Auf derselben Reise durch Spanien sah er zwei Arten, dem Wein Zeit zu geben: Bei López de Heredia in der Rioja, die selbst auf dieser Karte stehen, liegen die Weine jahrzehntelang in altem Holz, und in Jerez mischt die Solera jedes Jahr Junges mit Altem, sodass der Wein nie von vorn beginnt. Beides brachte er in die Champagne, wo damals nur zählte, wie frisch ein Wein war.",
 "sl": "Potreboval je 6 let prerekanja s šampanjskim odborom, da je dobil to, kar je videl v Jerezu: solero. Dovolili so mu jo leta 1986. Anselme Selosse se je v sedemdesetih učil v Burgundiji, pri ljudeh, ki so verjeli, da vino nastane v vinogradu, in to prepričanje je prinesel nazaj v Avize — kjer ga takrat ni delil nihče. Na isti poti po Španiji je videl dva načina, kako vinu dati čas: pri Lópezu de Herediji v Rioji, ki je prav tako na tej karti, vina desetletja ležijo v starem lesu, v Jerezu pa solera vsako leto zmeša mlado s starim, tako da vino nikoli ne začne od začetka. Oboje je prinesel v Champagne, kjer se je takrat merilo le, kako sveže je vino.",
 "es": "Le hicieron falta 6 años de discusión con el organismo de Champaña para conseguir lo que había visto en Jerez: una solera. Se la permitieron en 1986. Anselme Selosse se formó en los años setenta en Borgoña, entre gente que creía que el vino se hace en la viña, y trajo esa convicción de vuelta a Avize — donde entonces no la compartía nadie. En ese mismo viaje por España vio dos maneras de darle tiempo al vino: en López de Heredia en Rioja, que están también en esta carta, los vinos reposan décadas en madera vieja, y en Jerez la solera mezcla cada año lo joven con lo viejo, de modo que el vino nunca empieza de cero. Trajo ambas a Champaña, donde entonces sólo se medía lo fresco que era un vino.",
 "zh": "他和香槟产区管理机构争了 6 年，才拿到他在赫雷斯看见的那样东西：索莱拉。1986 年，他们终于允许了。安塞尔姆·瑟洛斯在七十年代于勃艮第学艺，身边人都相信酒是在葡萄园里做成的，他把这个信念带回阿维兹——当时那里没有人认同。也正是在那趟西班牙之行里，他看见了给酒时间的两种办法：在里奥哈的 López de Heredia——那家也在这份酒单上——酒在老木桶里一躺就是几十年；而在赫雷斯，索莱拉每年把新酒掺进老酒，酒因此从不从头开始。这两样他都带回了香槟，而当时那里衡量一款酒，只看它有多新鲜。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-26s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
