# -*- coding: utf-8 -*-
"""The ten French reorderings the owner accepted (2026-08-12).

Same rule as the Croatian pass: the hook leads, the research follows, one story
and one date wherever the second date is not the payoff of the first. Roederer
loses two of its three years, Krug loses its founding date and keeps the wall,
Chavy gains what the owner heard from him in person last year.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Roederer"] = {
 "hr": "Bocu od prozirnog stakla, s ravnim dnom, naručio je ruski car — ne zbog raskoši nego zbog straha: htio je vidjeti mjehuriće, ali i biti siguran da mu nitko nije sakrio eksploziv pod udubljenjem kakvo ima svaka druga boca. Nije mu pomoglo; ubijen je 1881. Tako je nastao Cristal. Roederer je danas jedna od rijetkih velikih kuća koja posjeduje gotovo sve svoje vinograde — i Château de Pez u Saint-Estèpheu, koji je također na ovoj karti.",
 "en": "A bottle of clear glass with a flat bottom was ordered by the Tsar of Russia — not out of luxury but out of fear: he wanted to see the bubbles, and to be sure nobody had hidden an explosive in the punt every other bottle has. It did not save him; he was assassinated in 1881. That is how Cristal came about. Roederer is one of the few great houses that owns nearly all its own vineyards — and Château de Pez in Saint-Estèphe, which is also on this list.",
 "it": "Una bottiglia di vetro trasparente, a fondo piatto, la ordinò lo zar di Russia — non per sfarzo ma per paura: voleva vedere le bollicine, ed essere sicuro che nessuno gli avesse nascosto un esplosivo nella fossetta che ogni altra bottiglia ha. Non gli servì; fu assassinato nel 1881. È così che è nato il Cristal. Roederer è una delle poche grandi maison che possiede quasi tutte le proprie vigne — e anche Château de Pez a Saint-Estèphe, che è su questa carta.",
 "fr": "Une bouteille de verre clair, à fond plat, fut commandée par le tsar de Russie — non par faste mais par peur : il voulait voir les bulles, et être sûr que nul n'avait caché un explosif dans la piqûre qu'ont toutes les autres. Cela ne l'a pas sauvé ; il fut assassiné en 1881. C'est ainsi qu'est né le Cristal. Roederer est l'une des rares grandes maisons à posséder presque toutes ses vignes — et aussi Château de Pez à Saint-Estèphe, qui figure sur cette carte.",
 "de": "Eine Flasche aus klarem Glas, mit flachem Boden, bestellte der Zar von Russland — nicht aus Prunk, sondern aus Angst: Er wollte die Perlen sehen und sicher sein, dass ihm niemand einen Sprengsatz in der Wölbung versteckt hatte, die jede andere Flasche hat. Es half ihm nicht; 1881 wurde er ermordet. So entstand Cristal. Roederer ist eines der wenigen großen Häuser, das fast alle eigenen Weinberge besitzt — und dazu Château de Pez in Saint-Estèphe, das ebenfalls auf dieser Karte steht.",
 "sl": "Steklenico iz prozornega stekla, z ravnim dnom, je naročil ruski car — ne zaradi razkošja, ampak iz strahu: hotel je videti mehurčke in biti prepričan, da mu nihče ni skril razstreliva v vdolbini, kakršno ima vsaka druga steklenica. Ni mu pomagalo; leta 1881 so ga ubili. Tako je nastal Cristal. Roederer je ena redkih velikih hiš, ki ima skoraj vse svoje vinograde — in tudi Château de Pez v Saint-Estèphu, ki je na tej karti.",
 "es": "Una botella de vidrio transparente, de fondo plano, la encargó el zar de Rusia — no por lujo sino por miedo: quería ver las burbujas y estar seguro de que nadie le había escondido un explosivo en el hueco que tienen todas las demás. No le sirvió; lo asesinaron en 1881. Así nació el Cristal. Roederer es una de las pocas grandes casas que posee casi todas sus viñas — y también Château de Pez en Saint-Estèphe, que está en esta carta.",
 "zh": "一只透明玻璃、平底的瓶子，是俄国沙皇订下的——动机不是奢华，而是恐惧：他要看得见气泡，也要确认没有人在其他瓶子都有的凹底里藏进炸药。这没能救他；1881 年他遇刺身亡。水晶香槟就是这么来的。路易王妃是少数几乎拥有全部自有葡萄园的大型香槟酒庄之一——名下还有圣埃斯泰夫的 Château de Pez，那家也在这份酒单上。"
}

NEW["Krug"] = {
 "hr": "Kad je Krug 1971. kupio 6 hektara u Le Mesnilu, tek je na terenu otkrio što je unutra: zidom ograđena parcela od 1,84 hektara. Na zidu piše 1698. — godina kad je zid podignut i kad su posađene loze. To je Clos du Mesnil. Kuća inače postoji zbog jedne tvrdoglave ideje: vrhunski šampanjac svake godine, i u dobroj i u lošoj berbi — zato se Grande Cuvée slaže od nekoliko stotina mirnih vina iz raznih godina, a svaka parcela vrije zasebno, u maloj hrastovoj bačvi.",
 "en": "When Krug bought 6 hectares in Le Mesnil in 1971, it was only on the ground that they found what was inside: a walled plot of 1.84 hectares. The wall says 1698 — the year it was built and the year the vines were planted. That is Clos du Mesnil. The house otherwise exists for one stubborn idea: a great champagne every year, in poor vintages as well as good ones — which is why the Grande Cuvée assembles several hundred still wines from many years, and why every parcel ferments on its own, in a small oak cask.",
 "it": "Quando nel 1971 Krug comprò 6 ettari a Le Mesnil, solo sul posto scoprì che cosa ci fosse dentro: una parcella murata di 1,84 ettari. Sul muro c'è scritto 1698 — l'anno in cui fu eretto e in cui furono piantate le viti. È il Clos du Mesnil. Per il resto la maison esiste per un'idea testarda: un grande champagne ogni anno, nelle annate scarse come in quelle buone — per questo la Grande Cuvée assembla diverse centinaia di vini fermi di molte annate, e ogni parcella fermenta per conto suo, in una piccola botte di rovere.",
 "fr": "Quand Krug a acheté 6 hectares au Mesnil en 1971, ce n'est qu'une fois sur place qu'on a découvert ce qu'il y avait dedans : une parcelle close de murs de 1,84 hectare. Le mur dit 1698 — l'année où il fut bâti et où les vignes furent plantées. C'est le Clos du Mesnil. Pour le reste, la maison existe pour une idée têtue : un grand champagne chaque année, dans les millésimes faibles comme dans les bons — d'où une Grande Cuvée qui assemble plusieurs centaines de vins clairs de nombreuses années, et des parcelles qui fermentent chacune à part, en petit fût de chêne.",
 "de": "Als Krug 1971 sechs Hektar in Le Mesnil kaufte, entdeckte man erst vor Ort, was darin lag: eine ummauerte Parzelle von 1,84 Hektar. Die Mauer sagt 1698 — das Jahr, in dem sie errichtet und die Reben gepflanzt wurden. Das ist Clos du Mesnil. Im Übrigen gibt es das Haus wegen einer sturen Idee: jedes Jahr ein großer Champagner, in schwachen Jahrgängen wie in guten — darum setzt die Grande Cuvée mehrere hundert Stillweine aus vielen Jahren zusammen, und darum vergärt jede Parzelle für sich, im kleinen Eichenfass.",
 "sl": "Ko je Krug leta 1971 kupil 6 hektarov v Le Mesnilu, so šele na terenu odkrili, kaj je znotraj: z zidom obdana parcela 1,84 hektara. Na zidu piše 1698 — leto, ko je bil postavljen in ko so posadili trte. To je Clos du Mesnil. Sicer pa hiša obstaja zaradi ene trmaste zamisli: vrhunski šampanjec vsako leto, v slabih letnikih enako kot v dobrih — zato Grande Cuvée sestavi tudi po nekaj sto mirnih vin iz mnogih let, vsaka parcela pa vre posebej, v majhnem hrastovem sodu.",
 "es": "Cuando Krug compró 6 hectáreas en Le Mesnil en 1971, sólo sobre el terreno descubrió lo que había dentro: una parcela amurallada de 1,84 hectáreas. El muro dice 1698 — el año en que se levantó y en que se plantaron las cepas. Es el Clos du Mesnil. Por lo demás, la casa existe por una idea terca: un gran champán cada año, en las añadas flojas igual que en las buenas — por eso la Grande Cuvée ensambla varios cientos de vinos tranquilos de muchos años, y cada parcela fermenta por su cuenta, en una pequeña barrica de roble.",
 "zh": "1971 年库克在勒梅尼买下 6 公顷，到了现场才发现里头是什么：一块 1.84 公顷的围墙园。墙上刻着 1698——建墙的那一年，也是种下葡萄藤的那一年。那就是 Clos du Mesnil。至于这家酒庄，它存在是为了一个固执的念头：无论年份好坏，每年都要做出顶级香槟——所以 Grande Cuvée 会把来自许多年份的数百款静止酒调配起来，也所以每块园地都单独发酵，用的是小橡木桶。"
}

NEW["Philippe Chavy"] = {
 "hr": "Philippe Chavy ima 6 hektara i jedno pitanje na koje nema odgovor: tko će ih preuzeti. Ne govori o tome glasno, ali ga to brine više od berbe. Zemlju je dobio s dvije strane: Puligny od oca Alberta, loze zasađene pedesetih, i Meursault od majke Odile Ropiteau, koji seže do 1932. Danas ih s Graziellom obrađuje u Puligny-Montrachetu, Saint-Aubinu i Meursaultu — male količine, stare loze, i nijedno ime koje bi se prodavalo samo od sebe.",
 "en": "Philippe Chavy has 6 hectares and one question he has no answer to: who will take them on. He does not say it loudly, but it weighs on him more than the harvest does. The land came from both sides: Puligny from his father Albert, vines planted in the 1950s, and Meursault from his mother Odile Ropiteau, going back to 1932. He works it today with Graziella, across Puligny-Montrachet, Saint-Aubin and Meursault — small quantities, old vines, and not one name that would sell itself.",
 "it": "Philippe Chavy ha 6 ettari e una domanda cui non sa rispondere: chi li prenderà in mano. Non lo dice ad alta voce, ma lo assilla più della vendemmia. La terra gli è arrivata da due parti: il Puligny del padre Albert, viti piantate negli anni Cinquanta, e il Meursault della madre Odile Ropiteau, che risale al 1932. Oggi la lavora con Graziella, fra Puligny-Montrachet, Saint-Aubin e Meursault — piccole quantità, viti vecchie, e nessun nome che si venda da solo.",
 "fr": "Philippe Chavy a 6 hectares et une question sans réponse : qui les reprendra. Il ne le dit pas fort, mais cela le préoccupe plus que la vendange. La terre lui est venue des deux côtés : le puligny de son père Albert, vignes plantées dans les années 1950, et le meursault de sa mère Odile Ropiteau, qui remonte à 1932. Il les travaille aujourd'hui avec Graziella, entre Puligny-Montrachet, Saint-Aubin et Meursault — de petites quantités, de vieilles vignes, et pas un nom qui se vende tout seul.",
 "de": "Philippe Chavy hat 6 Hektar und eine Frage, auf die er keine Antwort hat: wer sie einmal übernimmt. Er sagt es nicht laut, aber es beschäftigt ihn mehr als die Lese. Das Land kam von beiden Seiten: Puligny vom Vater Albert, Reben aus den 1950ern, und Meursault von der Mutter Odile Ropiteau, der bis 1932 zurückreicht. Heute bewirtschaftet er es mit Graziella, in Puligny-Montrachet, Saint-Aubin und Meursault — kleine Mengen, alte Reben und kein Name, der sich von selbst verkauft.",
 "sl": "Philippe Chavy ima 6 hektarov in eno vprašanje, na katero nima odgovora: kdo jih bo prevzel. Na glas o tem ne govori, a ga skrbi bolj kot trgatev. Zemljo je dobil z dveh strani: Puligny od očeta Alberta, trte posajene v petdesetih, in meursault od matere Odile Ropiteau, ki sega v leto 1932. Danes jo z Graziello obdeluje v Puligny-Montrachetu, Saint-Aubinu in Meursaultu — majhne količine, stare trte in nobeno ime, ki bi se prodajalo samo od sebe.",
 "es": "Philippe Chavy tiene 6 hectáreas y una pregunta sin respuesta: quién las tomará. No lo dice en voz alta, pero le pesa más que la vendimia. La tierra le llegó por los dos lados: el Puligny de su padre Albert, cepas plantadas en los años cincuenta, y el Meursault de su madre Odile Ropiteau, que se remonta a 1932. Hoy la trabaja con Graziella, entre Puligny-Montrachet, Saint-Aubin y Meursault — cantidades pequeñas, cepas viejas y ni un nombre que se venda solo.",
 "zh": "菲利普·沙维有 6 公顷，还有一个他答不上来的问题：将来谁来接手。他不大声说，但这件事比收成更让他挂心。土地是从两边来的：父亲阿尔贝的普利尼，藤是五十年代种下的；母亲奥迪尔·罗皮托的默尔索，可追溯到 1932 年。如今他与格拉齐耶拉一起，在普利尼-蒙拉榭、圣欧班和默尔索耕作——产量很小，藤很老，而且没有一个名字能靠自己卖出去。"
}

NEW["Piuze"] = {
 "hr": "Patrick Piuze rođen je u Québecu, a do Chablisa je stigao preko vinograda Australije, Južne Afrike i Izraela. Nema nijedan vlastiti vinograd: grožđe kupuje od uzgajivača kojima sam govori kako da rade, bere se ručno, preša je stara okomita. Prije nego što je 2008. otvorio svoju kuću, Chablis je radio za Oliviera Leflaivea i Jean-Marca Brocarda. Nekome tko nije odavde trebalo je pola svijeta da dođe do jedne kredne padine u Burgundiji.",
 "en": "Patrick Piuze was born in Quebec and reached Chablis by way of vineyards in Australia, South Africa and Israel. He owns not a single vineyard of his own: he buys fruit from growers he himself tells how to farm it, everything is picked by hand, the press is an old vertical one. Before opening his own house in 2008 he made Chablis for Olivier Leflaive and Jean-Marc Brocard. It took an outsider half a world to arrive at one chalk slope in Burgundy.",
 "it": "Patrick Piuze è nato in Québec e a Chablis è arrivato passando per le vigne di Australia, Sudafrica e Israele. Non possiede una sola vigna: compra l'uva da viticoltori ai quali dice lui stesso come lavorarla, si vendemmia a mano, il torchio è un vecchio verticale. Prima di aprire casa propria nel 2008 faceva Chablis per Olivier Leflaive e Jean-Marc Brocard. A uno di fuori è servito mezzo mondo per arrivare a un pendio di creta in Borgogna.",
 "fr": "Patrick Piuze est né au Québec et est arrivé à Chablis en passant par les vignes d'Australie, d'Afrique du Sud et d'Israël. Il ne possède pas une seule vigne : il achète le raisin à des vignerons à qui il dit lui-même comment le cultiver, tout est vendangé à la main, le pressoir est un vieux vertical. Avant d'ouvrir sa maison en 2008, il faisait le chablis d'Olivier Leflaive et de Jean-Marc Brocard. Il aura fallu à un étranger la moitié du monde pour arriver à un coteau de craie en Bourgogne.",
 "de": "Patrick Piuze wurde in Québec geboren und kam über die Weinberge Australiens, Südafrikas und Israels nach Chablis. Er besitzt keinen einzigen eigenen Weinberg: Er kauft die Trauben von Winzern, denen er selbst sagt, wie sie sie anbauen sollen, gelesen wird von Hand, die Presse ist eine alte senkrechte. Bevor er 2008 sein eigenes Haus eröffnete, machte er den Chablis für Olivier Leflaive und Jean-Marc Brocard. Ein Fremder brauchte den halben Erdball, um an einem Kreidehang im Burgund anzukommen.",
 "sl": "Patrick Piuze se je rodil v Québecu, do Chablisa pa prišel prek vinogradov Avstralije, Južne Afrike in Izraela. Nima niti enega svojega vinograda: grozdje kupuje od pridelovalcev, ki jim sam pove, kako naj ga pridelujejo, trga se ročno, stiskalnica je stara navpična. Preden je leta 2008 odprl svojo hišo, je chablis delal za Oliviera Leflaiva in Jean-Marca Brocarda. Tujcu je bilo treba pol sveta, da je prišel do ene kredne rebri v Burgundiji.",
 "es": "Patrick Piuze nació en Quebec y llegó a Chablis pasando por las viñas de Australia, Sudáfrica e Israel. No posee ni una sola viña propia: compra la uva a viticultores a los que él mismo dice cómo cultivarla, se vendimia a mano, la prensa es una vieja vertical. Antes de abrir casa propia en 2008 hacía el Chablis de Olivier Leflaive y de Jean-Marc Brocard. A alguien de fuera le hizo falta medio mundo para llegar a una ladera de creta en Borgoña.",
 "zh": "帕特里克·皮兹生于魁北克，一路经过澳大利亚、南非与以色列的葡萄园，才走到夏布利。他自己一块葡萄园也没有：果实向果农收购，而怎么耕作则由他来说，全部手工采摘，压榨用的是老式立式榨机。2008 年开出自己的门户之前，他为奥利维耶·勒弗莱夫和让-马克·布罗卡尔酿夏布利。一个外来者，绕了半个地球，才抵达勃艮第的一道白垩山坡。"
}

NEW["Chartron"] = {
 "hr": "Puligny svoje drugo ime duguje jednom čovjeku: Jean-Édouardu Dupardu, bačvaru, vinaru i načelniku sela, koji je izborio da se imenu doda *Montrachet*. Ime na etiketi došlo je poslije, vjenčanjem Eugénie Dupard i Jeana-Edmonda Chartrona. Danas peti naraštaj, 14,5 hektara, i dva monopola koja nema nitko drugi: Clos de la Pucelle i Clos du Cailleret.",
 "en": "Puligny owes its second name to one man: Jean-Édouard Dupard, cooper, winemaker and mayor of the village, whose campaigning got *Montrachet* added to it. The name on the label came later, from the marriage of Eugénie Dupard and Jean-Edmond Chartron. Fifth generation today, 14.5 hectares, and two monopoles nobody else has: Clos de la Pucelle and Clos du Cailleret.",
 "it": "Puligny deve il proprio secondo nome a un uomo solo: Jean-Édouard Dupard, bottaio, vignaiolo e sindaco del paese, grazie al quale al nome fu aggiunto *Montrachet*. Il nome in etichetta venne dopo, dal matrimonio di Eugénie Dupard e Jean-Edmond Chartron. Oggi la quinta generazione, 14,5 ettari e due monopole che non ha nessun altro: Clos de la Pucelle e Clos du Cailleret.",
 "fr": "Puligny doit son second nom à un seul homme : Jean-Édouard Dupard, tonnelier, vigneron et maire du village, dont l'action a fait ajouter *Montrachet* au nom. Le nom de l'étiquette est venu après, du mariage d'Eugénie Dupard et de Jean-Edmond Chartron. Cinquième génération aujourd'hui, 14,5 hectares, et deux monopoles que personne d'autre ne possède : le Clos de la Pucelle et le Clos du Cailleret.",
 "de": "Puligny verdankt seinen zweiten Namen einem Einzigen: Jean-Édouard Dupard, Küfer, Winzer und Bürgermeister des Dorfes, dessen Einsatz dem Namen *Montrachet* hinzufügte. Der Name auf dem Etikett kam später, aus der Heirat von Eugénie Dupard und Jean-Edmond Chartron. Heute fünfte Generation, 14,5 Hektar und zwei Monopole, die sonst niemand hat: Clos de la Pucelle und Clos du Cailleret.",
 "sl": "Puligny se za svoje drugo ime zahvaljuje enemu človeku: Jean-Édouardu Dupardu, sodarju, vinarju in županu vasi, ki je izboril, da se je imenu dodal *Montrachet*. Ime na etiketi je prišlo pozneje, s poroko Eugénie Dupard in Jeana-Edmonda Chartrona. Danes peti rod, 14,5 hektara in dva monopola, ki ju nima nihče drug: Clos de la Pucelle in Clos du Cailleret.",
 "es": "Puligny le debe su segundo nombre a un solo hombre: Jean-Édouard Dupard, tonelero, viticultor y alcalde del pueblo, cuya insistencia logró que se le añadiera *Montrachet*. El nombre de la etiqueta llegó después, del matrimonio de Eugénie Dupard y Jean-Edmond Chartron. Hoy la quinta generación, 14,5 hectáreas y dos monopoles que no tiene nadie más: Clos de la Pucelle y Clos du Cailleret.",
 "zh": "普利尼名字里的后半截，要归功于一个人：让-爱德华·迪帕尔——箍桶匠、酿酒人，也是村长，是他奔走争取，才让村名后面加上了 *Montrachet*。酒标上的姓氏来得更晚，源自欧仁妮·迪帕尔与让-埃德蒙·沙特龙的婚姻。如今已是第五代，14,5 公顷，还有两块别人都没有的独占园：Clos de la Pucelle 与 Clos du Cailleret。"
}

NEW["Hubert Lamy"] = {
 "hr": "30.000 trsova po hektaru — trostruko gušće nego što se u Burgundiji sadi danas, i točno onako kako se sadilo prije nego što je u vinograd ušao traktor. Trsovi se otimaju o istu vodu, bobice ostaju sitne, korijen mora dublje; u čaši je to više tla i manje voća. Tako su Hubert i sin Olivier presadili dio Derrière chez Edouarda i Clos du Meixa. Saint-Aubin je dugo bio susjed kojeg nitko nije primjećivao — ovakvim potezima prestao je to biti.",
 "en": "30,000 vines per hectare — roughly three times what Burgundy plants today, and exactly what was planted before the tractor came into the vineyard. The vines fight each other for the same water, the berries stay tiny, the roots have to go deeper; in the glass that reads as more soil and less fruit. That is how Hubert and his son Olivier replanted part of Derrière chez Edouard and Clos du Meix. Saint-Aubin was long the neighbour nobody noticed — moves like this ended that.",
 "it": "30.000 ceppi per ettaro — circa il triplo di quanto si pianti oggi in Borgogna, ed esattamente come si piantava prima che il trattore entrasse in vigna. Le viti si contendono la stessa acqua, gli acini restano minuti, le radici devono scendere più a fondo; nel bicchiere è più terra e meno frutto. Così Hubert e il figlio Olivier hanno reimpiantato una parte di Derrière chez Edouard e del Clos du Meix. Saint-Aubin è stato a lungo il vicino che nessuno notava — mosse come questa hanno smesso di renderlo tale.",
 "fr": "30 000 pieds à l'hectare — environ le triple de ce qu'on plante aujourd'hui en Bourgogne, et exactement ce qu'on plantait avant que le tracteur n'entre dans la vigne. Les ceps se disputent la même eau, les baies restent minuscules, les racines doivent descendre plus bas ; dans le verre, c'est plus de sol et moins de fruit. C'est ainsi qu'Hubert et son fils Olivier ont replanté une partie de Derrière chez Edouard et du Clos du Meix. Saint-Aubin fut longtemps le voisin que personne ne regardait — des gestes comme celui-là y ont mis fin.",
 "de": "30.000 Stöcke je Hektar — etwa dreimal so dicht, wie man im Burgund heute pflanzt, und genau so, wie man pflanzte, bevor der Traktor in den Weinberg kam. Die Stöcke streiten um dasselbe Wasser, die Beeren bleiben winzig, die Wurzeln müssen tiefer; im Glas ist das mehr Boden und weniger Frucht. So haben Hubert und sein Sohn Olivier einen Teil von Derrière chez Edouard und des Clos du Meix neu gepflanzt. Saint-Aubin war lange der Nachbar, den niemand bemerkte — Schritte wie dieser haben damit Schluss gemacht.",
 "sl": "30.000 trt na hektar — približno trikrat gosteje, kot se v Burgundiji sadi danes, in natanko tako, kot se je sadilo, preden je v vinograd zapeljal traktor. Trte se pulijo za isto vodo, jagode ostanejo drobne, korenine morajo globlje; v kozarcu je to več tal in manj sadja. Tako sta Hubert in sin Olivier presadila del Derrière chez Edouarda in Clos du Meixa. Saint-Aubin je bil dolgo sosed, ki ga ni nihče opazil — s takimi potezami je to nehal biti.",
 "es": "30.000 cepas por hectárea — unas tres veces lo que se planta hoy en Borgoña, y exactamente lo que se plantaba antes de que el tractor entrara en la viña. Las cepas se disputan la misma agua, las bayas quedan diminutas, las raíces tienen que bajar más; en la copa eso es más suelo y menos fruta. Así replantaron Hubert y su hijo Olivier parte de Derrière chez Edouard y del Clos du Meix. Saint-Aubin fue mucho tiempo el vecino que nadie miraba — gestos así acabaron con eso.",
 "zh": "每公顷 30.000 株——约为今日勃艮第种植密度的三倍，也正是拖拉机开进葡萄园之前的种法。藤株彼此争夺同一份水，果粒因此细小，根系不得不扎得更深；落到杯子里，那是更多的土壤味、更少的果味。于贝尔与儿子奥利维耶就是这样重种了 Derrière chez Edouard 与 Clos du Meix 的一部分。圣欧班长久以来是无人留意的邻居——正是这样的举动让它不再如此。"
}

NEW["Lignier"] = {
 "hr": "Romain Lignier umro je 2004. od tumora na mozgu, sa 34 godine. Otac Hubert vratio se iz mirovine i s drugim sinom Laurentom nastavio raditi ono što je mislio da je već predao. Vina su ostala kakva su bila: pinot bez šminke, s onom finoćom po kojoj se Morey prepoznaje.",
 "en": "Romain Lignier died of a brain tumour in 2004, aged 34. His father Hubert came out of retirement and carried on with his other son, Laurent, doing the work he had thought he had already handed over. The wines did not change: Pinot with no make-up on it, and the fineness Morey is known by.",
 "it": "Romain Lignier è morto di un tumore al cervello nel 2004, a 34 anni. Il padre Hubert è uscito dalla pensione e ha proseguito con l'altro figlio, Laurent, il lavoro che credeva di avere già consegnato. I vini non sono cambiati: pinot senza trucco, con quella finezza da cui si riconosce Morey.",
 "fr": "Romain Lignier est mort d'une tumeur au cerveau en 2004, à 34 ans. Son père Hubert est sorti de sa retraite et a repris, avec son autre fils Laurent, le travail qu'il croyait avoir déjà transmis. Les vins n'ont pas changé : du pinot sans fard, et cette finesse à laquelle on reconnaît Morey.",
 "de": "Romain Lignier starb 2004 mit 34 Jahren an einem Hirntumor. Sein Vater Hubert kam aus dem Ruhestand zurück und führte mit dem anderen Sohn Laurent die Arbeit weiter, von der er geglaubt hatte, er habe sie längst übergeben. Die Weine blieben, was sie waren: Pinot ohne Schminke, mit jener Feinheit, an der man Morey erkennt.",
 "sl": "Romain Lignier je leta 2004 umrl za možganskim tumorjem, star 34 let. Oče Hubert se je vrnil iz pokoja in z drugim sinom Laurentom nadaljeval delo, za katerega je mislil, da ga je že predal. Vina so ostala, kar so bila: pinot brez ličila, s tisto finostjo, po kateri se Morey prepozna.",
 "es": "Romain Lignier murió de un tumor cerebral en 2004, a los 34 años. Su padre Hubert salió de la jubilación y continuó, con su otro hijo Laurent, el trabajo que creía haber entregado ya. Los vinos no cambiaron: Pinot sin maquillaje, y esa finura por la que se reconoce Morey.",
 "zh": "2004 年，罗曼·利尼耶因脑瘤去世，年仅 34 岁。父亲于贝尔从退休中回来，与另一个儿子洛朗一起，接着做那份他以为早已交出去的工作。酒没有变：不施粉黛的黑皮诺，带着那种一尝便认得出莫雷的细致。"
}

NEW["Rémi Jobard"] = {
 "hr": "Meursault koji zvuči mineralno ondje gdje se nekad očekivao maslac. Prešanje je dugo i nježno, vino ide u velike bačve austrijskog bačvara Stockingera i u visoke uske foudre — samo oko 20% novog drva, jer ideja nije da se čuje hrast. Nakon godine dana u drvu odmara se još 6 mjeseci u tanku prije punjenja. Ekološki uzgoj od 2011., s biodinamičkim zahvatima.",
 "en": "Meursault that sounds mineral where butter used to be expected. The pressing is long and gentle, the wine then goes into large barrels from the Austrian cooper Stockinger and into tall narrow foudres — only about 20% new wood, because the point is not to hear the oak. After a year in wood it settles another 6 months in tank before bottling. Farmed organically since 2011, with biodynamic work on top.",
 "it": "Un Meursault che suona minerale dove un tempo ci si aspettava il burro. La pressatura è lunga e delicata, poi il vino va in botti grandi del bottaio austriaco Stockinger e in foudre alte e strette — solo circa il 20% di legno nuovo, perché lo scopo non è sentire il rovere. Dopo un anno in legno riposa altri 6 mesi in vasca prima dell'imbottigliamento. In biologico dal 2011, con interventi biodinamici.",
 "fr": "Un meursault qui sonne minéral là où l'on attendait autrefois le beurre. Le pressurage est long et doux, puis le vin va en grands fûts du tonnelier autrichien Stockinger et en foudres hauts et étroits — seulement 20% de bois neuf environ, car il ne s'agit pas d'entendre le chêne. Après un an en bois, il repose encore 6 mois en cuve avant la mise. En bio depuis 2011, avec des gestes biodynamiques.",
 "de": "Ein Meursault, der mineralisch klingt, wo man früher Butter erwartete. Gepresst wird lange und sanft, dann geht der Wein in große Fässer des österreichischen Küfers Stockinger und in hohe schmale Foudres — nur etwa 20% neues Holz, denn es geht nicht darum, die Eiche zu hören. Nach einem Jahr im Holz ruht er weitere 6 Monate im Tank vor der Füllung. Seit 2011 biologisch bewirtschaftet, mit biodynamischen Eingriffen.",
 "sl": "Meursault, ki zveni mineralno tam, kjer se je nekoč pričakovalo maslo. Stiskanje je dolgo in nežno, vino pa nato odide v velike sode avstrijskega sodarja Stockingerja in v visoke ozke foudre — le okoli 20% novega lesa, ker namen ni, da bi se hrast slišal. Po letu dni v lesu počiva še 6 mesecev v cisterni pred polnjenjem. Ekološka pridelava od leta 2011, z biodinamičnimi posegi.",
 "es": "Un Meursault que suena mineral donde antes se esperaba mantequilla. El prensado es largo y suave, y el vino pasa después a barricas grandes del tonelero austríaco Stockinger y a foudres altos y estrechos — sólo un 20% de madera nueva, porque la idea no es oír el roble. Tras un año en madera reposa otros 6 meses en depósito antes de embotellar. En ecológico desde 2011, con trabajo biodinámico.",
 "zh": "一款在人们从前期待黄油之处、却响起矿石声音的默尔索。压榨漫长而轻柔，随后酒进入奥地利桶匠施托金格制作的大桶，以及高而窄的大木槽——新桶比例仅约 20%，因为重点从来不是让人听见橡木。在木头里待满一年后，装瓶前还要在罐中静置 6 个月。自 2011 年起以有机方式耕作，并辅以生物动力的做法。"
}

NEW["Théo Dancer"] = {
 "hr": "Théo Dancer preuzeo je imanje sa 20 godina i odmah promijenio dio postavki u vinogradu i podrumu — što je u Burgundiji hrabrije nego što zvuči. Otac Vincent osnovao je kuću u Chassagne-Montrachetu i bio prvi u selu s ekološkim certifikatom. Ovo, dakle, nije nastavak nego nova ruka na starom mjestu.",
 "en": "Théo Dancer took the estate on at 20 and immediately changed a number of settings in the vineyard and the cellar — which in Burgundy is braver than it sounds. His father Vincent founded the house in Chassagne-Montrachet and was the first in the village to take organic certification. So this is not a continuation but a new hand in an old place.",
 "it": "Théo Dancer ha preso in mano la tenuta a 20 anni e ha subito cambiato diverse impostazioni in vigna e in cantina — cosa che in Borgogna è più coraggiosa di quanto sembri. Il padre Vincent aveva fondato la casa a Chassagne-Montrachet ed era stato il primo del paese a ottenere la certificazione biologica. Non è dunque una continuazione, ma una mano nuova in un luogo antico.",
 "fr": "Théo Dancer a repris le domaine à 20 ans et a aussitôt changé plusieurs réglages à la vigne et à la cave — ce qui, en Bourgogne, est plus courageux qu'il n'y paraît. Son père Vincent avait fondé la maison à Chassagne-Montrachet et fut le premier du village à obtenir la certification bio. Ce n'est donc pas une suite, mais une main neuve dans un lieu ancien.",
 "de": "Théo Dancer übernahm das Gut mit 20 und änderte sofort etliche Einstellungen im Weinberg und im Keller — was im Burgund mutiger ist, als es klingt. Sein Vater Vincent hatte das Haus in Chassagne-Montrachet gegründet und war der Erste im Dorf mit Bio-Zertifikat. Das hier ist also keine Fortsetzung, sondern eine neue Hand an einem alten Ort.",
 "sl": "Théo Dancer je posestvo prevzel pri 20 letih in takoj spremenil marsikatero nastavitev v vinogradu in kleti — kar je v Burgundiji pogumneje, kot se sliši. Oče Vincent je hišo ustanovil v Chassagne-Montrachetu in bil prvi v vasi z ekološkim certifikatom. To torej ni nadaljevanje, ampak nova roka na starem kraju.",
 "es": "Théo Dancer tomó la finca a los 20 años y cambió de inmediato varias cosas en la viña y en la bodega — lo que en Borgoña es más valiente de lo que suena. Su padre Vincent había fundado la casa en Chassagne-Montrachet y fue el primero del pueblo en obtener la certificación ecológica. Así que esto no es una continuación, sino una mano nueva en un lugar antiguo.",
 "zh": "泰奥·当塞 20 岁接手酒庄，随即在葡萄园与酒窖里改动了不少设定——在勃艮第，这比听上去要大胆得多。父亲樊尚在夏山-蒙拉榭创立了这家酒庄，也是村里第一个取得有机认证的人。所以这不是延续，而是一双新的手落在一个老地方。"
}

NEW["Deutz"] = {
 "hr": "Dvojica Nijemaca došla su u Aÿ raditi za druge, pa odlučila raditi za sebe — William Deutz i Pierre-Hubert Geldermann. Stil se otad nije mijenjao: suzdržan, uglađen šampanjac bez ijedne teatralne geste. Kuća koja se nikad nije trudila biti glasna.",
 "en": "Two Germans came to Aÿ to work for others and decided to work for themselves — William Deutz and Pierre-Hubert Geldermann. The style has not changed since: restrained, polished champagne without a single theatrical gesture. A house that has never tried to be loud.",
 "it": "Due tedeschi vennero ad Aÿ a lavorare per altri, e decisero di lavorare per sé — William Deutz e Pierre-Hubert Geldermann. Da allora lo stile non è cambiato: champagne misurato ed elegante, senza un solo gesto teatrale. Una maison che non ha mai cercato di alzare la voce.",
 "fr": "Deux Allemands sont venus à Aÿ travailler pour d'autres, puis ont décidé de travailler pour eux-mêmes — William Deutz et Pierre-Hubert Geldermann. Le style n'a pas changé depuis : un champagne retenu, poli, sans un seul geste théâtral. Une maison qui n'a jamais cherché à parler fort.",
 "de": "Zwei Deutsche kamen nach Aÿ, um für andere zu arbeiten, und beschlossen, für sich zu arbeiten — William Deutz und Pierre-Hubert Geldermann. Der Stil hat sich seither nicht geändert: zurückhaltender, geschliffener Champagner ohne eine einzige theatralische Geste. Ein Haus, das nie laut sein wollte.",
 "sl": "Dva Nemca sta prišla v Aÿ delat za druge, potem pa se odločila delati zase — William Deutz in Pierre-Hubert Geldermann. Slog se odtlej ni spremenil: zadržan, uglajen šampanjec brez ene same teatralne geste. Hiša, ki nikoli ni skušala biti glasna.",
 "es": "Dos alemanes llegaron a Aÿ a trabajar para otros y decidieron trabajar para sí — William Deutz y Pierre-Hubert Geldermann. El estilo no ha cambiado desde entonces: un champán contenido, pulido, sin un solo gesto teatral. Una casa que nunca ha querido hablar alto.",
 "zh": "两位德国人来到艾伊，本是为别人打工，后来决定为自己干——威廉·德茨与皮埃尔-于贝尔·热尔德曼。此后风格未曾改变：克制、圆熟，没有一丝戏剧化的姿态。一家从不试图大声说话的酒庄。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]

for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-16s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))

out = json.dumps(data, ensure_ascii=False, indent=1) + "\n"
open(p, "w", encoding="utf-8", newline="").write(out.replace("\n", "\r\n"))
print("\nwritten")
