# -*- coding: utf-8 -*-
"""Japan, Jamaica, Barbados, Mexico, Haiti — fifteen cards (2026-08-12).

Each keeps the hook it already had, since those were good, and gains the second
beat it was missing. New rule from today applied throughout: the most appealing
line first, research behind it.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

# ---------------- Japan ----------------

NEW["Mars Shinshu"] = {
 "hr": "Najviše smještena destilerija viskija u Japanu, na oko 800 metara u Japanskim Alpama: zrak je rijedak, ljeta kratka, zima duga, pa bačva ovdje radi sporo i to se u čaši čuje. Gotovo 20 godina uopće nije radila — ugašena je kad je viski u Japanu prestao ići, a upaljena ponovno 2011., taman kad je počeo ići svima.",
 "en": "The highest whisky distillery in Japan, at around 800 metres in the Japanese Alps: thin air, short summers, long winters, so the cask works slowly here and you can hear it in the glass. For nearly 20 years it did not work at all — shut when whisky stopped selling in Japan, and lit again in 2011, just as it started selling to everyone.",
 "it": "La distilleria di whisky più alta del Giappone, a circa 800 metri sulle Alpi giapponesi: aria rarefatta, estati corte, inverni lunghi, così la botte qui lavora piano e nel bicchiere si sente. Per quasi 20 anni non ha lavorato affatto — spenta quando in Giappone il whisky smise di vendere, riaccesa nel 2011, giusto quando ricominciò a venderlo a tutti.",
 "fr": "La distillerie de whisky la plus haute du Japon, à quelque 800 mètres dans les Alpes japonaises : air raréfié, étés courts, hivers longs, si bien que le fût travaille lentement et que cela s'entend dans le verre. Pendant près de 20 ans, elle n'a pas travaillé du tout — éteinte quand le whisky ne se vendait plus au Japon, rallumée en 2011, juste quand il s'est mis à se vendre partout.",
 "de": "Japans höchstgelegene Whiskybrennerei, auf rund 800 Metern in den Japanischen Alpen: dünne Luft, kurze Sommer, lange Winter, also arbeitet das Fass hier langsam, und man hört es im Glas. Fast 20 Jahre lang arbeitete sie gar nicht — stillgelegt, als Whisky sich in Japan nicht mehr verkaufte, und 2011 wieder angezündet, gerade als er sich überall zu verkaufen begann.",
 "sl": "Najvišje ležeča destilarna viskija na Japonskem, na okoli 800 metrih v Japonskih Alpah: zrak je redek, poletja kratka, zime dolge, zato sod tu dela počasi in to se v kozarcu sliši. Skoraj 20 let sploh ni delala — ugasnili so jo, ko se viski na Japonskem ni več prodajal, in jo leta 2011 spet prižgali, ravno ko se je začel prodajati vsem.",
 "es": "La destilería de whisky más alta de Japón, a unos 800 metros en los Alpes japoneses: aire fino, veranos cortos, inviernos largos, así que aquí la barrica trabaja despacio y se oye en la copa. Durante casi 20 años no trabajó en absoluto — apagada cuando el whisky dejó de venderse en Japón, y encendida de nuevo en 2011, justo cuando empezó a vendérsele a todo el mundo.",
 "zh": "日本海拔最高的威士忌酒厂，位于日本阿尔卑斯约 800 米处：空气稀薄、夏短冬长，桶在这里走得慢，杯中听得出来。它曾有将近 20 年完全停摆——日本威士忌卖不动时熄了火，2011 年重新点燃，恰好赶上全世界都开始买。"
}

NEW["Mars Tsunuki"] = {
 "hr": "Ista kuća namjerno drži dvije krajnosti: ovo je najjužnija destilerija viskija u Japanu, u Kagoshimi, gdje se već stoljeće peče shochu. Vruće je i vlažno, pa bačva radi brzo — suprotno od njihove planinske sestre na sjeveru, koja radi sporo. Isti destilat, dvije klime, dva potpuno različita viskija.",
 "en": "The same house deliberately keeps two extremes: this is the southernmost whisky distillery in Japan, in Kagoshima, where they have been making shochu for a century. It is hot and humid, so the cask works fast — the opposite of their mountain sister in the north, which works slowly. The same spirit, two climates, two entirely different whiskies.",
 "it": "La stessa casa tiene di proposito due estremi: questa è la distilleria di whisky più meridionale del Giappone, a Kagoshima, dove si fa shochu da un secolo. Fa caldo ed è umido, così la botte lavora in fretta — l'opposto della sorella di montagna al nord, che lavora piano. Stesso distillato, due climi, due whisky del tutto diversi.",
 "fr": "La même maison entretient délibérément deux extrêmes : voici la distillerie de whisky la plus au sud du Japon, à Kagoshima, où l'on fait du shochu depuis un siècle. Il fait chaud et humide, le fût travaille donc vite — l'inverse de sa sœur de montagne au nord, qui travaille lentement. Le même distillat, deux climats, deux whiskies entièrement différents.",
 "de": "Dasselbe Haus hält mit Absicht zwei Extreme: Dies ist Japans südlichste Whiskybrennerei, in Kagoshima, wo man seit einem Jahrhundert Shochu brennt. Es ist heiß und feucht, also arbeitet das Fass schnell — das Gegenteil der Bergschwester im Norden, die langsam arbeitet. Dasselbe Destillat, zwei Klimata, zwei völlig verschiedene Whiskys.",
 "sl": "Ista hiša namenoma drži dve skrajnosti: to je najjužnejša destilarna viskija na Japonskem, v Kagošimi, kjer že stoletje delajo šoču. Vroče je in vlažno, zato sod dela hitro — nasprotno od njihove gorske sestre na severu, ki dela počasi. Isti destilat, dve podnebji, dva povsem različna viskija.",
 "es": "La misma casa mantiene a propósito dos extremos: esta es la destilería de whisky más meridional de Japón, en Kagoshima, donde llevan un siglo haciendo shochu. Hace calor y humedad, así que la barrica trabaja deprisa — lo contrario de su hermana de montaña en el norte, que trabaja despacio. El mismo destilado, dos climas, dos whiskies completamente distintos.",
 "zh": "同一家公司刻意握着两个极端：这是日本最南端的威士忌酒厂，位于鹿儿岛——他们在那里做烧酎已有一个世纪。这里又热又湿，桶因此走得快——与北边那座山中的姊妹厂正好相反，那边走得极慢。同样的原酒，两种气候，两款完全不同的威士忌。"
}

NEW["Nine Leaves"] = {
 "hr": "Jedan čovjek, jedan kotao, kraj jezera Biwa. Yoshiharu Takeuchi sam kuha, destilira, puni i lijepi etikete — vjerojatno najmanja destilerija ruma na svijetu. Bačve prazni dvaput godišnje, u proljeće i u jesen, i na bocu stavlja koje je to punjenje, jer u tako maloj kući nijedno nije isto kao prošlo.",
 "en": "One man, one still, beside Lake Biwa. Yoshiharu Takeuchi cooks, distils, bottles and labels it all himself — probably the smallest rum distillery in the world. He empties the casks twice a year, in spring and in autumn, and puts on the label which release it is, because in a house this small no two are the same.",
 "it": "Un uomo, un alambicco, in riva al lago Biwa. Yoshiharu Takeuchi cuoce, distilla, imbottiglia ed etichetta tutto da solo — probabilmente la più piccola distilleria di rum al mondo. Svuota le botti due volte l'anno, in primavera e in autunno, e in etichetta scrive di quale imbottigliamento si tratti, perché in una casa così piccola nessuno è uguale al precedente.",
 "fr": "Un homme, un alambic, au bord du lac Biwa. Yoshiharu Takeuchi cuit, distille, embouteille et étiquette tout lui-même — probablement la plus petite distillerie de rhum au monde. Il vide les fûts deux fois par an, au printemps et à l'automne, et indique sur l'étiquette de quelle mise il s'agit, car dans une maison aussi petite aucune ne ressemble à la précédente.",
 "de": "Ein Mann, eine Brennblase, am Biwa-See. Yoshiharu Takeuchi kocht, brennt, füllt und etikettiert alles selbst — vermutlich die kleinste Rumbrennerei der Welt. Die Fässer leert er zweimal im Jahr, im Frühling und im Herbst, und schreibt auf das Etikett, welche Abfüllung es ist, denn in einem so kleinen Haus gleicht keine der vorigen.",
 "sl": "En človek, en kotel, ob jezeru Biva. Jošiharu Takeuči sam kuha, destilira, polni in lepi etikete — najbrž najmanjša destilarna ruma na svetu. Sode prazni dvakrat na leto, spomladi in jeseni, na steklenico pa zapiše, katero polnjenje je, ker v tako majhni hiši nobeno ni enako prejšnjemu.",
 "es": "Un hombre, un alambique, a la orilla del lago Biwa. Yoshiharu Takeuchi cuece, destila, embotella y etiqueta todo él mismo — probablemente la destilería de ron más pequeña del mundo. Vacía las barricas dos veces al año, en primavera y en otoño, y pone en la etiqueta de qué embotellado se trata, porque en una casa tan pequeña ninguno es igual al anterior.",
 "zh": "一个人，一台蒸馏器，就在琵琶湖边。竹内嘉治自己煮、自己蒸馏、自己装瓶、自己贴标——大概是世界上最小的朗姆酒厂。他一年清两次桶，春天一次、秋天一次，并在酒标上写明是哪一批，因为在这么小的地方，没有哪一批和上一批相同。"
}

NEW["Ohishi"] = {
 "hr": "Riža koja je odležala. Kuća s rijeke Kume u Kumamotu 3 stoljeća peče shochu od riže — a rižin shochu iz te doline zaštićen je kao ime, jednako kao cognac ili scotch, i smije se tako zvati samo odavde. Ohishi ga je počeo ostavljati u bačvama od vina, sherryja i mizunare. Nije viski i ne pravi se da jest.",
 "en": "Rice that has been left to age. The house on the Kuma river in Kumamoto has made rice shochu for 3 centuries — and the rice shochu of that valley is a protected name, like cognac or scotch, that may only come from here. Ohishi began leaving it in wine, sherry and mizunara casks. It is not whisky and does not pretend to be.",
 "it": "Riso invecchiato. La casa sul fiume Kuma, a Kumamoto, fa shochu di riso da 3 secoli — e lo shochu di riso di quella valle è un nome protetto, come il cognac o lo scotch, e può venire solo da qui. Ohishi ha cominciato a lasciarlo in botti di vino, sherry e mizunara. Non è whisky e non finge di esserlo.",
 "fr": "Du riz qu'on a laissé vieillir. La maison de la rivière Kuma, à Kumamoto, fait du shochu de riz depuis 3 siècles — et le shochu de riz de cette vallée est un nom protégé, comme le cognac ou le scotch, qui ne peut venir que d'ici. Ohishi s'est mis à le laisser en fûts de vin, de xérès et de mizunara. Ce n'est pas du whisky et cela ne prétend pas l'être.",
 "de": "Reis, den man hat liegen lassen. Das Haus am Kuma-Fluss in Kumamoto brennt seit 3 Jahrhunderten Reis-Shochu — und der Reis-Shochu dieses Tals ist ein geschützter Name, wie Cognac oder Scotch, der nur von hier kommen darf. Ohishi begann, ihn in Wein-, Sherry- und Mizunara-Fässern liegen zu lassen. Es ist kein Whisky und tut auch nicht so.",
 "sl": "Riž, ki je odležal. Hiša ob reki Kumi v Kumamotu že 3 stoletja dela rižev šoču — rižev šoču iz te doline pa je zaščiteno ime, tako kot konjak ali scotch, in sme prihajati samo od tod. Ohiši ga je začel puščati v sodih od vina, šerija in mizunare. Ni viski in se ne dela, da je.",
 "es": "Arroz que se ha dejado envejecer. La casa del río Kuma, en Kumamoto, lleva 3 siglos haciendo shochu de arroz — y el shochu de arroz de ese valle es un nombre protegido, como el coñac o el scotch, que sólo puede venir de aquí. Ohishi empezó a dejarlo en barricas de vino, jerez y mizunara. No es whisky y no pretende serlo.",
 "zh": "陈放过的米。熊本球磨川畔的这家酒厂做米烧酎已有 3 个世纪——而这条河谷的米烧酎是受保护的名称，像干邑或苏格兰威士忌一样，只能出自这里。大石开始把它放进葡萄酒桶、雪莉桶和水楢桶里陈放。它不是威士忌，也不假装是。"
}

# ---------------- Jamaica ----------------

NEW["Hampden"] = {
 "hr": "Nikad ni koraka prema lakšem ukusu. U Trelawnyju od 1753.: fermentacija koja traje tjednima, hranjena muckom iz vlastite jame, i kotlovi s dvije retorte iz kojih izlazi destilat s najviše estera na svijetu. Dva i pol stoljeća sve je to odlazilo u tuđe kupaže — vlastito ime na bocu Hampden je pustio tek 2018.",
 "en": "Never one step towards an easier taste. In Trelawny since 1753: a fermentation that runs for weeks, fed from its own muck pit, and double-retort pot stills that yield the most ester-rich spirit in the world. For two and a half centuries all of it went into other people's blends — Hampden only let its own name onto a bottle in 2018.",
 "it": "Mai un passo verso un gusto più facile. A Trelawny dal 1753: una fermentazione che dura settimane, nutrita dalla propria fossa del muck, e alambicchi a due retorte da cui esce il distillato più ricco di esteri al mondo. Per due secoli e mezzo tutto finiva nei blend degli altri — il proprio nome in bottiglia Hampden l'ha messo solo nel 2018.",
 "fr": "Jamais un pas vers un goût plus facile. À Trelawny depuis 1753 : une fermentation qui dure des semaines, nourrie de sa propre fosse à muck, et des alambics à deux retortes d'où sort le distillat le plus riche en esters au monde. Deux siècles et demi durant, tout partait dans les assemblages des autres — Hampden n'a mis son nom sur une bouteille qu'en 2018.",
 "de": "Nie einen Schritt Richtung leichteren Geschmack. In Trelawny seit 1753: eine Gärung über Wochen, gefüttert aus der eigenen Muck-Grube, und Pot Stills mit zwei Retorten, aus denen das esterreichste Destillat der Welt kommt. Zweieinhalb Jahrhunderte ging alles in fremde Blends — den eigenen Namen ließ Hampden erst 2018 auf eine Flasche.",
 "sl": "Nikoli koraka proti lažjemu okusu. V Trelawnyju od leta 1753: fermentacija, ki traja tedne, hranjena z mučem iz lastne jame, in kotli z dvema retortama, iz katerih pride destilat z največ estri na svetu. Dve stoletji in pol je vse to odhajalo v tuje zvrsti — lastno ime je Hampden spustil na steklenico šele leta 2018.",
 "es": "Nunca un paso hacia un sabor más fácil. En Trelawny desde 1753: una fermentación que dura semanas, alimentada desde su propio pozo de muck, y alambiques de doble retorta de los que sale el destilado con más ésteres del mundo. Durante dos siglos y medio todo se iba a las mezclas de otros — Hampden no puso su nombre en una botella hasta 2018.",
 "zh": "从不朝着更好入口的方向让一步。自 1753 年就在特里劳尼：发酵长达数周，用自家「muck 坑」里的酸液喂养，双retort 壶式蒸馏器产出全世界酯类含量最高的原酒。两个半世纪里，这些酒全部流进别人的调和酒——Hampden 直到 2018 年才把自家名字放上瓶身。"
}

NEW["Long Pond"] = {
 "hr": "Ovdje se okus mjeri i označava slovima. Long Pond je u Trelawnyju, župi poznatoj po rumovima s najviše estera na svijetu, i svaka receptura ima svoju oznaku — što je viša, to je više onog laka i prezrelog voća koje se ne da zaboraviti. Cambridge je jedna od njih. Destilerija je stara preko 200 godina i uglavnom je radila za druge.",
 "en": "Here the flavour is measured and given a letter. Long Pond is in Trelawny, the parish known for the most ester-rich rums in the world, and every recipe has its own mark — the higher it is, the more of that varnish and overripe fruit you cannot forget. Cambridge is one of them. The distillery is over 200 years old and has mostly worked for other people.",
 "it": "Qui il gusto si misura e si marca con delle lettere. Long Pond sta a Trelawny, la parrocchia nota per i rum più ricchi di esteri al mondo, e ogni ricetta ha la sua sigla — più è alta, più c'è di quella vernice e di quel frutto stramaturo che non si dimentica. Cambridge è una di quelle. La distilleria ha più di 200 anni e ha lavorato quasi sempre per altri.",
 "fr": "Ici, le goût se mesure et reçoit des lettres. Long Pond est à Trelawny, la paroisse connue pour les rhums les plus riches en esters au monde, et chaque recette a sa marque — plus elle est haute, plus il y a de ce vernis et de ce fruit trop mûr qu'on n'oublie pas. Cambridge en est une. La distillerie a plus de 200 ans et a surtout travaillé pour les autres.",
 "de": "Hier wird der Geschmack gemessen und mit Buchstaben markiert. Long Pond liegt in Trelawny, der Gemeinde, die für die esterreichsten Rums der Welt bekannt ist, und jede Rezeptur hat ihr Kürzel — je höher, desto mehr von diesem Lack und überreifen Obst, das man nicht vergisst. Cambridge ist eines davon. Die Brennerei ist über 200 Jahre alt und hat meist für andere gearbeitet.",
 "sl": "Tu se okus meri in označuje s črkami. Long Pond je v Trelawnyju, župniji, znani po rumih z največ estri na svetu, in vsaka receptura ima svojo oznako — višja ko je, več je tistega laka in prezrelega sadja, ki se ga ne da pozabiti. Cambridge je ena od njih. Destilarna je stara več kot 200 let in je večinoma delala za druge.",
 "es": "Aquí el sabor se mide y se marca con letras. Long Pond está en Trelawny, la parroquia conocida por los rones con más ésteres del mundo, y cada receta tiene su marca — cuanto más alta, más de ese barniz y esa fruta pasada que no se olvida. Cambridge es una de ellas. La destilería tiene más de 200 años y ha trabajado sobre todo para otros.",
 "zh": "在这里，风味是可以被量出来、并用字母标记的。Long Pond 位于特里劳尼——以全世界酯含量最高的朗姆闻名的教区——每一种配方都有自己的代号；代号越高，那股让人忘不掉的清漆味与熟透果香就越浓。Cambridge 就是其中之一。这家酒厂有 200 多年历史，长期为别人代工。"
}

NEW["Velier"] = {
 "hr": "Genova, ne Karibi: Velier ništa ne destilira. Luca Gargano bira bačve po otocima i puni ih bez šećera, bez boje i bez razrjeđivanja — i time je sam promijenio ono što svijet misli da rum jest. Kad je Demerara u Gvajani zatvorila stare kotlove, on je otkupio zalihe i od njih napravio boce koje danas idu na aukcije.",
 "en": "Genoa, not the Caribbean: Velier distils nothing. Luca Gargano picks casks across the islands and bottles them with no sugar, no colour and no dilution — and in doing so changed, single-handedly, what the world thinks rum is. When Demerara in Guyana shut down its old stills, he bought up the stock and turned it into bottles that go to auction today.",
 "it": "Genova, non i Caraibi: Velier non distilla nulla. Luca Gargano sceglie le botti nelle isole e le imbottiglia senza zucchero, senza colore e senza diluizione — e così ha cambiato da solo l'idea che il mondo ha del rum. Quando in Guyana la Demerara chiuse i vecchi alambicchi, lui ne comprò le scorte e ne fece bottiglie che oggi vanno all'asta.",
 "fr": "Gênes, pas les Caraïbes : Velier ne distille rien. Luca Gargano choisit des fûts dans les îles et les met en bouteille sans sucre, sans colorant et sans réduction — et il a changé à lui seul l'idée que le monde se fait du rhum. Quand la Demerara, en Guyana, a arrêté ses vieux alambics, il en a racheté les stocks et en a fait des bouteilles qui passent aujourd'hui en vente aux enchères.",
 "de": "Genua, nicht die Karibik: Velier destilliert nichts. Luca Gargano sucht auf den Inseln Fässer aus und füllt sie ohne Zucker, ohne Farbe und ohne Verdünnung ab — und hat damit im Alleingang verändert, was die Welt für Rum hält. Als Demerara in Guyana seine alten Brennblasen stilllegte, kaufte er die Bestände auf und machte daraus Flaschen, die heute versteigert werden.",
 "sl": "Genova, ne Karibi: Velier ne destilira ničesar. Luca Gargano izbira sode po otokih in jih polni brez sladkorja, brez barve in brez razredčevanja — in s tem je sam spremenil to, kar svet misli, da rum je. Ko je Demerara v Gvajani zaprla stare kotle, je odkupil zaloge in iz njih naredil steklenice, ki danes gredo na dražbe.",
 "es": "Génova, no el Caribe: Velier no destila nada. Luca Gargano elige barricas por las islas y las embotella sin azúcar, sin color y sin dilución — y con eso cambió él solo lo que el mundo cree que es el ron. Cuando Demerara, en Guyana, apagó sus viejos alambiques, él compró las existencias e hizo con ellas botellas que hoy van a subasta.",
 "zh": "热那亚，而不是加勒比：Velier 自己不蒸馏。卢卡·加尔加诺在各个岛上挑桶，然后不加糖、不加色、不稀释地装瓶——凭一己之力改变了世界对朗姆的看法。当圭亚那的德梅拉拉关掉那些老蒸馏器时，他买下了库存，做成了如今在拍卖会上流转的酒。"
}

# ---------------- Barbados ----------------

NEW["Foursquare"] = {
 "hr": "Richard Seale je gotovo sam izborio da se u rumu piše što je u boci: bez dodanog šećera, bez boje, bez izgovora — i punjenja u jačini u kojoj su izašla iz bačve. Godinama je s tim bio manjina koju industrija nije htjela čuti; danas se po njegovim pravilima ravna pola svijeta. Destilerija u St Philipu stoji na staroj plantaži šećera.",
 "en": "Richard Seale all but single-handedly forced rum to say what is in the bottle: no added sugar, no colouring, no excuses — and bottlings at the strength they left the cask. For years he was a minority the industry did not want to hear; today half the world follows his rules. The distillery in St Philip stands on an old sugar plantation.",
 "it": "Richard Seale ha imposto quasi da solo che nel rum si scriva cosa c'è nella bottiglia: niente zucchero aggiunto, niente colore, niente scuse — e imbottigliamenti alla gradazione con cui sono usciti dalla botte. Per anni è stato una minoranza che l'industria non voleva sentire; oggi mezzo mondo segue le sue regole. La distilleria a St Philip sorge su una vecchia piantagione di canna.",
 "fr": "Richard Seale a presque à lui seul imposé que le rhum dise ce qu'il y a dans la bouteille : pas de sucre ajouté, pas de colorant, pas d'excuses — et des mises à la force du fût. Des années durant, il fut une minorité que l'industrie ne voulait pas entendre ; aujourd'hui la moitié du monde suit ses règles. La distillerie de St Philip est bâtie sur une ancienne plantation sucrière.",
 "de": "Richard Seale hat beinahe im Alleingang durchgesetzt, dass Rum sagt, was in der Flasche ist: kein zugesetzter Zucker, keine Farbe, keine Ausreden — und Abfüllungen in der Stärke, in der sie das Fass verlassen haben. Jahrelang war er eine Minderheit, die die Branche nicht hören wollte; heute richtet sich die halbe Welt nach seinen Regeln. Die Brennerei in St Philip steht auf einer alten Zuckerplantage.",
 "sl": "Richard Seale je skoraj sam izboril, da rum pove, kaj je v steklenici: brez dodanega sladkorja, brez barve, brez izgovorov — in polnitve v jakosti, s kakršno so prišle iz soda. Leta je bil manjšina, ki je industrija ni hotela slišati; danes se po njegovih pravilih ravna pol sveta. Destilarna v St Philipu stoji na stari sladkorni plantaži.",
 "es": "Richard Seale impuso casi él solo que el ron diga lo que hay en la botella: sin azúcar añadido, sin color, sin excusas — y embotellados a la fuerza con que salieron de la barrica. Durante años fue una minoría que la industria no quería oír; hoy medio mundo sigue sus reglas. La destilería de St Philip se levanta sobre una vieja plantación de azúcar.",
 "zh": "理查德·西尔几乎是凭一己之力，逼着朗姆酒说清瓶子里到底是什么：不加糖、不加色、不找借口——而且以出桶时的强度装瓶。多年来他是行业不愿听的少数派；如今半个世界都按他的规矩来。位于圣菲利普的酒厂，就建在一座旧糖厂庄园之上。"
}

NEW["Mount Gay"] = {
 "hr": "Papir iz 1703. čini ovu kuću najstarijom rumarskom markom koja još radi — starijom od svih viskija i konjaka na ovoj karti. Koraljni otok filtrira vlastitu vodu, i to je s melasom cijeli recept. Boca koju ovdje točimo zove se The Last Ward, po Franku Wardu, posljednjem iz obitelji koja je kućom upravljala naraštajima.",
 "en": "A deed from 1703 makes this the oldest rum brand still working — older than every whisky and cognac on this list. The coral island filters its own water, and that, with molasses, is the whole recipe. The bottle we pour is called The Last Ward, after Frank Ward, the last of the family that ran the house for generations.",
 "it": "Un atto del 1703 fa di questa la più antica marca di rum ancora in attività — più antica di ogni whisky e cognac su questa carta. L'isola corallina filtra la propria acqua, e questo, con la melassa, è tutta la ricetta. La bottiglia che versiamo si chiama The Last Ward, da Frank Ward, l'ultimo della famiglia che ha guidato la casa per generazioni.",
 "fr": "Un acte de 1703 fait de cette maison la plus ancienne marque de rhum encore en activité — plus ancienne que tous les whiskies et cognacs de cette carte. L'île de corail filtre sa propre eau, et cela, avec la mélasse, constitue toute la recette. La bouteille que nous servons s'appelle The Last Ward, d'après Frank Ward, le dernier de la famille qui a mené la maison pendant des générations.",
 "de": "Eine Urkunde von 1703 macht dies zur ältesten noch arbeitenden Rummarke — älter als jeder Whisky und Cognac auf dieser Karte. Die Koralleninsel filtert ihr Wasser selbst, und das ist mit Melasse das ganze Rezept. Die Flasche, die wir ausschenken, heißt The Last Ward, nach Frank Ward, dem Letzten der Familie, die das Haus über Generationen führte.",
 "sl": "Listina iz leta 1703 dela to hišo za najstarejšo rumovo znamko, ki še dela — starejšo od vseh viskijev in konjakov na tej karti. Koralni otok filtrira lastno vodo, in to je z melaso cel recept. Steklenica, ki jo točimo, se imenuje The Last Ward, po Franku Wardu, zadnjem iz družine, ki je hišo vodila rodove.",
 "es": "Una escritura de 1703 hace de esta la marca de ron más antigua que sigue en activo — más antigua que todos los whiskies y coñacs de esta carta. La isla de coral filtra su propia agua, y eso, con la melaza, es toda la receta. La botella que servimos se llama The Last Ward, por Frank Ward, el último de la familia que dirigió la casa durante generaciones.",
 "zh": "一纸 1703 年的地契，让它成为至今仍在运转的最古老朗姆品牌——比这份酒单上任何威士忌和干邑都老。珊瑚岛替它过滤了自己的水，而这与糖蜜，就是全部配方。我们倒的这瓶叫 The Last Ward，取自弗兰克·沃德——那个执掌酒厂数代的家族中的最后一人。"
}

NEW["Veritas"] = {
 "hr": "Dvije kuće koje se inače nadmeću spojile su destilate u jednu bijelu bocu: Foursquare s Barbadosa i Hampden s Jamajke, dva potpuno suprotna shvaćanja ruma. Bez šećera i bez boje, punjeno u 47% — bijeli rum kakav je bio prije nego što je postao bezokusna baza za koktel.",
 "en": "Two houses that normally compete put their spirits into one white bottle: Foursquare from Barbados and Hampden from Jamaica, two entirely opposite ideas of rum. No sugar and no colour, bottled at 47% — white rum as it was before it became a flavourless base for a cocktail.",
 "it": "Due case che di solito si fanno concorrenza hanno unito i distillati in una sola bottiglia bianca: Foursquare da Barbados e Hampden dalla Giamaica, due idee di rum del tutto opposte. Senza zucchero e senza colore, imbottigliato a 47% — rum bianco com'era prima di diventare una base insapore da cocktail.",
 "fr": "Deux maisons qui d'ordinaire se disputent ont réuni leurs distillats dans une seule bouteille blanche : Foursquare de la Barbade et Hampden de la Jamaïque, deux idées du rhum entièrement opposées. Sans sucre et sans colorant, à 47% — le rhum blanc tel qu'il était avant de devenir une base sans goût pour cocktail.",
 "de": "Zwei Häuser, die sonst konkurrieren, haben ihre Destillate in eine weiße Flasche gebracht: Foursquare aus Barbados und Hampden aus Jamaika, zwei völlig gegensätzliche Auffassungen von Rum. Ohne Zucker und ohne Farbe, mit 47% gefüllt — weißer Rum, wie er war, bevor er zur geschmacklosen Cocktailbasis wurde.",
 "sl": "Dve hiši, ki si sicer konkurirata, sta destilata združili v eno belo steklenico: Foursquare z Barbadosa in Hampden z Jamajke, dve povsem nasprotni razumevanji ruma. Brez sladkorja in brez barve, polnjeno pri 47% — beli rum, kakršen je bil, preden je postal brezokusna osnova za koktajl.",
 "es": "Dos casas que normalmente compiten juntaron sus destilados en una sola botella blanca: Foursquare de Barbados y Hampden de Jamaica, dos ideas del ron completamente opuestas. Sin azúcar y sin color, embotellado a 47% — ron blanco como era antes de convertirse en una base sin sabor para cóctel.",
 "zh": "两家平常互相较劲的酒厂，把各自的原酒装进了同一只白瓶：巴巴多斯的 Foursquare 与牙买加的 Hampden——两种完全相反的朗姆观。不加糖、不加色，以 47% 装瓶——这是白朗姆在沦为无味调酒基底之前的样子。"
}

# ---------------- Mexico ----------------

NEW["Cimarrón"] = {
 "hr": "Desetljećima su uzgajali agavu za tuđe marke, a onda odlučili napraviti i svoju. Los Altos u Jalisci leži visoko, pa agava ondje dozrijeva sporije i dolazi slađa; kuća je peče u zidanoj peći, bez aditiva i bez šminke. Tequila kakvu piju oni koji je i uzgajaju — a ne ona koja se prodaje po boci, nego po imenu.",
 "en": "For decades they grew agave for other people's brands, then decided to make one of their own. Los Altos in Jalisco lies high, so the agave ripens more slowly there and comes sweeter; the house bakes it in a brick oven, with no additives and no make-up. The tequila drunk by the people who grow it — not the kind sold by the name rather than the bottle.",
 "it": "Per decenni hanno coltivato agave per i marchi altrui, poi hanno deciso di farne uno loro. Los Altos, in Jalisco, sta in alto, così l'agave matura più lentamente ed è più dolce; la casa la cuoce in forno di mattoni, senza additivi e senza trucco. La tequila che bevono quelli che la coltivano — non quella che si vende per il nome invece che per la bottiglia.",
 "fr": "Pendant des décennies, ils ont cultivé l'agave pour les marques des autres, puis ont décidé d'en faire une à eux. Los Altos, au Jalisco, est en altitude : l'agave y mûrit plus lentement et arrive plus sucrée ; la maison la cuit au four de briques, sans additifs et sans fard. La tequila que boivent ceux qui la cultivent — pas celle qui se vend pour le nom plutôt que pour la bouteille.",
 "de": "Jahrzehntelang bauten sie Agave für fremde Marken an, dann beschlossen sie, eine eigene zu machen. Los Altos in Jalisco liegt hoch, die Agave reift dort langsamer und kommt süßer; das Haus backt sie im Ziegelofen, ohne Zusätze und ohne Schminke. Der Tequila, den die trinken, die ihn anbauen — nicht der, der über den Namen verkauft wird statt über die Flasche.",
 "sl": "Desetletja so gojili agavo za tuje znamke, potem pa se odločili narediti še svojo. Los Altos v Jalisci leži visoko, zato agava tam dozoreva počasneje in je slajša; hiša jo peče v zidani peči, brez dodatkov in brez šminke. Tekila, kakršno pijejo tisti, ki jo tudi gojijo — in ne tista, ki se prodaja po imenu namesto po steklenici.",
 "es": "Durante décadas cultivaron agave para marcas ajenas, y luego decidieron hacer la suya. Los Altos, en Jalisco, está en altura, así que el agave madura más despacio y llega más dulce; la casa lo cuece en horno de mampostería, sin aditivos y sin maquillaje. El tequila que beben quienes lo cultivan — no el que se vende por el nombre en vez de por la botella.",
 "zh": "他们为别人的品牌种了几十年龙舌兰，后来决定做一个自己的。哈利斯科的 Los Altos 地势高，龙舌兰成熟得更慢、也更甜；酒厂用砖砌炉窑烘烤，不加添加剂，不施粉黛。这是种龙舌兰的人自己喝的特其拉——而不是靠名字、而非靠瓶中之物卖出去的那种。"
}

NEW["Del Maguey"] = {
 "hr": "Prije njega mezcal se izvozio kao anonimna roba s crvom u boci. Ron Cooper, američki umjetnik koji je u Oaxaci proveo godine, počeo ga je osamdesetih puniti selo po selo i na etiketu stavljati odakle je i tko ga je pekao. Danas svaka boca nosi ime sela i palenquera — a kategorija koju je time otvorio postala je sve što mezcal danas jest.",
 "en": "Before him, mezcal was exported as anonymous goods with a worm in the bottle. Ron Cooper, an American artist who spent years in Oaxaca, began in the 1980s to bottle it village by village and to put on the label where it came from and who had made it. Today every bottle carries the name of the village and of the palenquero — and the category he opened became everything mezcal now is.",
 "it": "Prima di lui il mezcal si esportava come merce anonima col verme nella bottiglia. Ron Cooper, artista americano che passò anni a Oaxaca, cominciò negli anni Ottanta a imbottigliarlo villaggio per villaggio e a scrivere in etichetta da dove veniva e chi l'aveva fatto. Oggi ogni bottiglia porta il nome del villaggio e del palenquero — e la categoria che ha aperto è diventata tutto ciò che il mezcal è oggi.",
 "fr": "Avant lui, le mezcal s'exportait comme une marchandise anonyme avec un ver dans la bouteille. Ron Cooper, artiste américain qui a passé des années à Oaxaca, s'est mis dans les années 1980 à l'embouteiller village par village et à inscrire sur l'étiquette d'où il venait et qui l'avait fait. Aujourd'hui, chaque bouteille porte le nom du village et du palenquero — et la catégorie qu'il a ouverte est devenue tout ce qu'est le mezcal.",
 "de": "Vor ihm wurde Mezcal als anonyme Ware mit einem Wurm in der Flasche exportiert. Ron Cooper, ein amerikanischer Künstler, der Jahre in Oaxaca verbrachte, begann in den 1980ern, ihn Dorf für Dorf abzufüllen und aufs Etikett zu schreiben, woher er kommt und wer ihn gemacht hat. Heute trägt jede Flasche den Namen des Dorfes und des Palenquero — und die Kategorie, die er damit öffnete, ist alles, was Mezcal heute ist.",
 "sl": "Pred njim se je mezcal izvažal kot anonimno blago s črvom v steklenici. Ron Cooper, ameriški umetnik, ki je v Oaxaci preživel leta, ga je v osemdesetih začel polniti vas za vasjo in na etiketo pisati, od kod je in kdo ga je naredil. Danes vsaka steklenica nosi ime vasi in palenquera — kategorija, ki jo je odprl, pa je postala vse, kar mezcal danes je.",
 "es": "Antes de él, el mezcal se exportaba como mercancía anónima con un gusano en la botella. Ron Cooper, artista estadounidense que pasó años en Oaxaca, empezó en los años ochenta a embotellarlo pueblo por pueblo y a poner en la etiqueta de dónde venía y quién lo había hecho. Hoy cada botella lleva el nombre del pueblo y del palenquero — y la categoría que abrió se convirtió en todo lo que el mezcal es hoy.",
 "zh": "在他之前，梅斯卡尔是作为匿名货物出口的，瓶里还泡着一条虫。美国艺术家罗恩·库珀在瓦哈卡待了多年，八十年代开始按村子逐一装瓶，并把产地与酿造者写上酒标。如今每一瓶都印着村名和 palenquero 的名字——而他开创的这个品类，已经成了今天梅斯卡尔的全部。"
}

NEW["Bruxo"] = {
 "hr": "Ime znači vračar, a dim u čaši nije aroma koja se dodaje nego trag vatre u zemlji: agava se peče u zemljanoj peći na drva, pa melje kamenim kolom koje vuče konj. U Oaxaci se tako radi stoljećima, jer drukčije se i ne može — struje u tim selima nema, a peć i konj ne kvare se.",
 "en": "The name means sorcerer, and the smoke in the glass is not an aroma anyone adds but the trace of a fire in the ground: the agave is baked in an earthen wood-fired pit, then crushed by a stone wheel pulled by a horse. Oaxaca has worked this way for centuries, because there is no other way — those villages have no electricity, and a pit and a horse do not break down.",
 "it": "Il nome significa stregone, e il fumo nel bicchiere non è un aroma che si aggiunge ma la traccia di un fuoco nella terra: l'agave si cuoce in una fossa di terra a legna, poi si macina con una ruota di pietra tirata da un cavallo. A Oaxaca si fa così da secoli, perché altrimenti non si può — in quei villaggi non c'è corrente, e la fossa e il cavallo non si guastano.",
 "fr": "Le nom veut dire sorcier, et la fumée dans le verre n'est pas un arôme qu'on ajoute mais la trace d'un feu dans la terre : l'agave est cuite dans une fosse de terre au bois, puis broyée par une meule de pierre tirée par un cheval. À Oaxaca on fait ainsi depuis des siècles, parce qu'on ne peut pas faire autrement — ces villages n'ont pas l'électricité, et une fosse et un cheval ne tombent pas en panne.",
 "de": "Der Name heißt Hexer, und der Rauch im Glas ist kein zugesetztes Aroma, sondern die Spur eines Feuers in der Erde: Die Agave wird in einer erdigen Holzgrube gebacken und dann von einem Steinrad zermahlen, das ein Pferd zieht. In Oaxaca arbeitet man so seit Jahrhunderten, weil es anders nicht geht — in diesen Dörfern gibt es keinen Strom, und eine Grube und ein Pferd fallen nicht aus.",
 "sl": "Ime pomeni čarovnik, dim v kozarcu pa ni aroma, ki bi se dodala, ampak sled ognja v zemlji: agava se peče v zemeljski jami na drva, nato jo zmelje kamnito kolo, ki ga vleče konj. V Oaxaci delajo tako že stoletja, ker drugače ne gre — v teh vaseh ni elektrike, jama in konj pa se ne pokvarita.",
 "es": "El nombre significa brujo, y el humo en la copa no es un aroma que se añada sino el rastro de un fuego en la tierra: el agave se cuece en un horno de tierra a leña y luego se muele con una rueda de piedra tirada por un caballo. En Oaxaca se hace así desde hace siglos, porque no se puede de otro modo — en esos pueblos no hay electricidad, y un horno y un caballo no se averían.",
 "zh": "这名字的意思是「巫师」，而杯中的烟并不是谁加进去的香气，而是地里那团火留下的痕迹：龙舌兰在土坑里以柴火焖烤，再由马拉着石磨碾碎。瓦哈卡这样做已有几个世纪，因为别无他法——那些村子没有电，而土坑和马不会坏。"
}

# ---------------- Haiti ----------------

NEW["Clairin"] = {
 "hr": "Rum kakav je bio prije industrije: trska rezana rukom, mljevena isti dan, vrenje s divljim kvascima s polja, jedna destilacija, ništa dodano. Na Haitiju radi nekoliko stotina takvih malih destilerija i nijedna nije čula za onu drugu; Velier je 2014. svijetu pokazao prve tri, i sve tri su na ovoj karti — Sajous, Vaval i Casimir, po ljudima koji ih peku.",
 "en": "Rum as it was before industry: cane cut by hand, milled the same day, fermented with the wild yeasts of the field, distilled once, nothing added. Haiti has several hundred such small distilleries and not one has heard of the next; in 2014 Velier showed the world the first three, and all three are on this list — Sajous, Vaval and Casimir, named after the men who make them.",
 "it": "Rum com'era prima dell'industria: canna tagliata a mano, macinata lo stesso giorno, fermentata con i lieviti selvatici del campo, una sola distillazione, niente di aggiunto. Ad Haiti ci sono alcune centinaia di queste piccole distillerie e nessuna sa dell'altra; nel 2014 Velier ne ha mostrate al mondo le prime tre, e tutte e tre sono su questa carta — Sajous, Vaval e Casimir, dal nome di chi le fa.",
 "fr": "Le rhum tel qu'il était avant l'industrie : canne coupée à la main, broyée le jour même, fermentée avec les levures sauvages du champ, une seule distillation, rien d'ajouté. Haïti compte plusieurs centaines de ces petites distilleries et aucune ne connaît la suivante ; en 2014, Velier en a montré les trois premières au monde, et les trois sont sur cette carte — Sajous, Vaval et Casimir, du nom de ceux qui les font.",
 "de": "Rum, wie er vor der Industrie war: Zuckerrohr von Hand geschnitten, am selben Tag gemahlen, mit den wilden Hefen des Feldes vergoren, einmal gebrannt, nichts zugesetzt. Auf Haiti gibt es einige hundert solcher kleinen Brennereien, und keine weiß von der anderen; 2014 zeigte Velier der Welt die ersten drei, und alle drei stehen auf dieser Karte — Sajous, Vaval und Casimir, nach den Männern, die sie brennen.",
 "sl": "Rum, kakršen je bil pred industrijo: trs, rezan z roko, zmlet isti dan, vrenje z divjimi kvasovkami s polja, ena destilacija, nič dodanega. Na Haitiju dela nekaj sto takih majhnih destilarn in nobena ne ve za drugo; Velier je leta 2014 svetu pokazal prve tri, in vse tri so na tej karti — Sajous, Vaval in Casimir, po ljudeh, ki jih delajo.",
 "es": "Ron como era antes de la industria: caña cortada a mano, molida el mismo día, fermentada con las levaduras salvajes del campo, una sola destilación, nada añadido. Haití tiene varios cientos de esas pequeñas destilerías y ninguna sabe de la otra; en 2014 Velier enseñó al mundo las tres primeras, y las tres están en esta carta — Sajous, Vaval y Casimir, por los hombres que las hacen.",
 "zh": "工业化之前的朗姆就是这个样子：甘蔗手工砍下，当天压榨，用田里的野生酵母发酵，只蒸馏一次，什么也不加。海地有几百家这样的小酒坊，彼此互不相识；2014 年，Velier 把最早的三家介绍给世界，而这三家都在这份酒单上——Sajous、Vaval 与 Casimir，名字取自酿它们的人。"
}

NEW["Chelo"] = {
 "hr": "Na Haitiju se rum još pravi kako se pravio prije nego što je itko izmislio industriju: trska iz susjedstva, divlja fermentacija, mali kotao na drva. Ništa se ne standardizira, pa svaka šarža zvuči malo drugačije — i to se ovdje ne smatra greškom nego potpisom. Ovaj je, za razliku od bistrog clairina, odležao u bačvi.",
 "en": "In Haiti rum is still made the way it was made before anyone invented industry: cane from next door, wild fermentation, a small wood-fired still. Nothing is standardised, so every batch sounds a little different — and that is taken here as a signature rather than a fault. This one, unlike clear clairin, has spent time in a cask.",
 "it": "Ad Haiti il rum si fa ancora come si faceva prima che qualcuno inventasse l'industria: canna del vicinato, fermentazione selvatica, un piccolo alambicco a legna. Nulla è standardizzato, così ogni partita suona un po' diversa — e qui non è un difetto ma una firma. Questo, a differenza del clairin limpido, è passato per la botte.",
 "fr": "En Haïti, le rhum se fait encore comme avant que quiconque n'invente l'industrie : de la canne du voisinage, une fermentation sauvage, un petit alambic au bois. Rien n'est standardisé, chaque lot sonne donc un peu différemment — et ici ce n'est pas un défaut mais une signature. Celui-ci, contrairement au clairin clair, a passé du temps en fût.",
 "de": "Auf Haiti wird Rum noch so gemacht, wie er gemacht wurde, bevor jemand die Industrie erfand: Zuckerrohr aus der Nachbarschaft, wilde Gärung, eine kleine holzbefeuerte Brennblase. Nichts ist standardisiert, also klingt jede Charge ein wenig anders — und das gilt hier als Signatur, nicht als Fehler. Dieser hier hat, anders als klarer Clairin, im Fass gelegen.",
 "sl": "Na Haitiju rum še vedno delajo tako, kot so ga delali, preden je kdorkoli iznašel industrijo: trs iz soseščine, divja fermentacija, majhen kotel na drva. Nič ni standardizirano, zato vsaka šarža zveni malo drugače — in to tu ni napaka, ampak podpis. Ta je, drugače kot bistri clairin, odležal v sodu.",
 "es": "En Haití el ron se sigue haciendo como se hacía antes de que nadie inventara la industria: caña del vecindario, fermentación salvaje, un alambique pequeño a leña. Nada se estandariza, así que cada lote suena un poco distinto — y aquí eso no es un defecto sino una firma. Este, a diferencia del clairin transparente, ha pasado por barrica.",
 "zh": "在海地，朗姆仍旧按照工业出现之前的方式制作：邻家的甘蔗、野生发酵、一台烧柴的小蒸馏器。什么都不标准化，所以每一批听起来都略有不同——在这里，这不算缺陷，而算签名。与清透的 clairin 不同，这一款在桶里待过。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-16s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
