# -*- coding: utf-8 -*-
"""Eight distillery cards given the tone the wines got (2026-08-12).

The German three the owner likes are 300–430 characters and each turns on one
story; the ones he flagged were 170–220 and turned on nothing. Facts verified
where I was not certain: Gibson's is distilled in England and only owned in
France (la-martiniquaise.com), Beaulon's park and its blue ponds are a listed
"jardin remarquable" with banana trees in Charente (chateau-de-beaulon.fr),
and Forgeron's own history page supplies the 1965 line that makes the card.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Gibson's"] = {
 "hr": "Engleski gin u francuskim rukama — i najprodavaniji gin u Francuskoj, što je otprilike kao da Francuzi najviše piju engleski gin, a Englezi to ne znaju. Destilira se u Engleskoj po istoj recepturi: borovica sprijeda, korijandar iza nje, i ništa što bi odvlačilo pažnju. Gin za one koji od gin-tonica traže gin, a ne buket.",
 "en": "An English gin in French hands — and the best-selling gin in France, which is roughly to say that the French drink more English gin than anyone, and the English have not noticed. It is distilled in England to the same recipe: juniper in front, coriander behind it, and nothing to draw the attention away. A gin for people who want gin in their gin and tonic, not a bouquet.",
 "it": "Un gin inglese in mani francesi — ed è il gin più venduto in Francia, che è come dire che i francesi bevono gin inglese più di chiunque altro, e gli inglesi non se ne sono accorti. Si distilla in Inghilterra secondo la stessa ricetta: ginepro davanti, coriandolo dietro, e nulla che distragga. Un gin per chi nel gin tonic cerca il gin, non il bouquet.",
 "fr": "Un gin anglais en mains françaises — et le gin le plus vendu en France, ce qui revient à dire que les Français boivent plus de gin anglais que quiconque, et que les Anglais ne l'ont pas remarqué. Il est distillé en Angleterre selon la même recette : le genièvre devant, la coriandre derrière, et rien qui détourne l'attention. Un gin pour ceux qui cherchent du gin dans leur gin tonic, pas un bouquet.",
 "de": "Ein englischer Gin in französischer Hand — und der meistverkaufte Gin Frankreichs, was ungefähr heißt: Die Franzosen trinken mehr englischen Gin als alle anderen, und die Engländer haben es nicht bemerkt. Destilliert wird er in England nach demselben Rezept: Wacholder vorn, Koriander dahinter, und nichts, was ablenkt. Ein Gin für alle, die im Gin Tonic Gin wollen und kein Bouquet.",
 "sl": "Angleški gin v francoskih rokah — in najbolje prodajani gin v Franciji, kar je približno tako, kot da Francozi pijejo angleški gin bolj kot kdorkoli, Angleži pa tega niso opazili. Destilira se v Angliji po istem receptu: brinje spredaj, koriander za njim, in nič, kar bi odvračalo pozornost. Gin za tiste, ki v gin toniku iščejo gin, ne šopka.",
 "es": "Una ginebra inglesa en manos francesas — y la más vendida de Francia, lo que viene a decir que los franceses beben más ginebra inglesa que nadie y los ingleses no se han enterado. Se destila en Inglaterra con la misma receta: el enebro delante, el cilantro detrás, y nada que distraiga. Una ginebra para quien en el gin-tonic busca ginebra, no un ramo de flores.",
 "zh": "一款落在法国人手里的英格兰金酒——而且是法国销量第一的金酒；也就是说，法国人喝英格兰金酒喝得比谁都多，而英格兰人并不知道。它仍在英格兰按同一配方蒸馏：杜松在前，芫荽在后，没有任何分散注意力的东西。这是给那些在金汤力里想喝到金酒、而不是花束的人准备的。"
}

NEW["Château de Beaulon"] = {
 "hr": "U parku rastu banane. Nekoliko koraka od stoljetnih jasenova, u Charenteu, zahvaljujući mikroklimi koju drže Fontaines Bleues — jezerca koja alge boje plavo i po kojima je cijeli perivoj proglašen spomenikom. Isti mir vlada i u podrumu: bačve leže desetljećima u vlazi, pa cognac izlazi mekan umjesto oštar. Dvorac je iz 15. stoljeća.",
 "en": "There are banana trees in the park. A few steps from century-old ash trees, in the Charente, thanks to a microclimate held by the Fontaines Bleues — ponds tinted blue by algae, for which the whole park is a listed monument. The same calm rules the cellar: the casks lie for decades in the damp, so the cognac comes out soft instead of sharp. The château is 15th century.",
 "it": "Nel parco crescono banani. A pochi passi da frassini secolari, nella Charente, grazie a un microclima tenuto dalle Fontaines Bleues — stagni che le alghe tingono di azzurro e per i quali tutto il parco è monumento tutelato. La stessa calma regna in cantina: le botti restano decenni nell'umido, e il cognac esce morbido invece che tagliente. Il castello è del Quattrocento.",
 "fr": "Il pousse des bananiers dans le parc. À quelques pas de frênes centenaires, en Charente, grâce au microclimat que tiennent les Fontaines Bleues — des étangs que les algues teintent de bleu et pour lesquels le parc entier est classé. Le même calme règne au chai : les fûts reposent des décennies dans l'humidité, et le cognac en sort tendre au lieu d'être tranchant. Le château est du XVe siècle.",
 "de": "Im Park wachsen Bananen. Ein paar Schritte von hundertjährigen Eschen entfernt, in der Charente, dank eines Mikroklimas, das die Fontaines Bleues halten — Teiche, die Algen blau färben und derentwegen der ganze Park unter Denkmalschutz steht. Dieselbe Ruhe herrscht im Keller: Die Fässer liegen jahrzehntelang im Feuchten, und der Cognac kommt weich statt scharf heraus. Das Schloss ist aus dem 15. Jahrhundert.",
 "sl": "V parku rastejo banane. Nekaj korakov od stoletnih jesenov, v Charentu, po zaslugi mikroklime, ki jo držijo Fontaines Bleues — jezerca, ki jih alge obarvajo modro in zaradi katerih je ves park razglašen za spomenik. Enak mir vlada v kleti: sodi ležijo desetletja v vlagi, in konjak pride ven mehak namesto oster. Grad je iz 15. stoletja.",
 "es": "En el parque crecen bananos. A unos pasos de fresnos centenarios, en la Charente, gracias al microclima que sostienen las Fontaines Bleues — estanques que las algas tiñen de azul y por los que todo el parque está protegido. La misma calma reina en la bodega: las barricas reposan décadas en la humedad, y el coñac sale suave en vez de afilado. El castillo es del siglo XV.",
 "zh": "园子里长着香蕉树。就在百年白蜡树旁几步远的地方，在夏朗德——靠的是「蓝泉」（Fontaines Bleues）撑起的小气候：那几方被藻类染成蓝色的池塘，也让整座园林被列为受保护古迹。酒窖里是同一种从容：桶在潮气里一躺几十年，干邑出来是柔的，而不是冲的。城堡建于 15 世纪。"
}

NEW["Michel Forgeron"] = {
 "hr": "Godine 1965. Michel Forgeron posadio je svu svoju zemlju u lozu, pa u kuću doveo ženu i kotao — tim redom, kako sami pričaju. Prvu bocu pod vlastitim imenom napunio je tek 12 godina poslije. Od 2 hektara narastao je na 24, sva u Grande Champagne i sva u krugu od 5 km oko kuće. U kraju u kojem velike kuće otkupljuju tuđe, oni ne prodaju nikome: sami uzgajaju, sami destiliraju, sami čekaju.",
 "en": "In 1965 Michel Forgeron planted all his land to vines, then brought home a wife and a still — in that order, as the family tells it. His first bottle under his own name came 12 years later. From 2 hectares he grew to 24, all in Grande Champagne and all within 5 km of the house. In a region where the great houses buy in other people's, they sell to nobody: they grow it, distil it and wait it out themselves.",
 "it": "Nel 1965 Michel Forgeron piantò a vigna tutta la sua terra, poi portò in casa una moglie e un alambicco — in quest'ordine, come racconta la famiglia. La prima bottiglia col proprio nome arrivò 12 anni dopo. Da 2 ettari è passato a 24, tutti in Grande Champagne e tutti entro 5 km da casa. In una zona dove le grandi case comprano l'altrui, loro non vendono a nessuno: coltivano, distillano e aspettano da soli.",
 "fr": "En 1965, Michel Forgeron a planté toute sa terre en vigne, puis il a fait entrer chez lui une femme et un alambic — dans cet ordre, tel que la famille le raconte. Sa première bouteille à son nom est venue 12 ans plus tard. De 2 hectares il est passé à 24, tous en Grande Champagne et tous dans un rayon de 5 km autour de la maison. Dans une région où les grandes maisons achètent celui des autres, eux ne vendent à personne : ils cultivent, distillent et attendent eux-mêmes.",
 "de": "1965 bepflanzte Michel Forgeron sein ganzes Land mit Reben und holte dann eine Frau und eine Brennblase ins Haus — in dieser Reihenfolge, so erzählt es die Familie. Die erste Flasche unter eigenem Namen kam 12 Jahre später. Aus 2 Hektar wurden 24, alle in der Grande Champagne und alle im Umkreis von 5 km ums Haus. In einer Gegend, in der die großen Häuser den Brand anderer aufkaufen, verkaufen sie an niemanden: Sie bauen selbst an, brennen selbst und warten selbst.",
 "sl": "Leta 1965 je Michel Forgeron vso svojo zemljo zasadil s trto, nato pa v hišo pripeljal ženo in kotel — v tem vrstnem redu, kot pripoveduje družina. Prvo steklenico pod lastnim imenom je napolnil šele 12 let pozneje. Z 2 hektarov je zrasel na 24, vse v Grande Champagne in vse v krogu 5 km okoli hiše. V kraju, kjer velike hiše odkupujejo tuje, oni ne prodajajo nikomur: sami pridelujejo, sami žgejo, sami čakajo.",
 "es": "En 1965 Michel Forgeron plantó de viña toda su tierra, y luego metió en casa una mujer y un alambique — en ese orden, según lo cuenta la familia. Su primera botella con nombre propio llegó 12 años después. De 2 hectáreas pasó a 24, todas en Grande Champagne y todas en un radio de 5 km alrededor de la casa. En una comarca donde las grandes casas compran lo de los demás, ellos no venden a nadie: cultivan, destilan y esperan ellos mismos.",
 "zh": "1965 年，米歇尔·福热龙把自己所有的地都种上了葡萄，然后把妻子和一台蒸馏器领进了门——按家里人的说法，顺序就是这样。用自己名字装的第一瓶，要等到 12 年之后。从 2 公顷长到 24 公顷，全在大香槟区，且都在住宅方圆 5 公里之内。在这片大厂靠收购别人原酒过日子的地方，他们不卖给任何人：自己种，自己蒸馏，自己等。"
}

NEW["Mulassano"] = {
 "hr": "Tramezzino — sendvič bez korice koji danas jede cijela Italija — izmišljen je za šankom kafića Mulassano na Piazzi Castello, a ime mu je dao Gabriele D'Annunzio, jer riječ *sandwich* nije bila dovoljno talijanska. Vermuti koji nose to ime rade se u Piemontu po povijesnim recepturama, na bazi pijemontskog bijelog vina — ne neutralnog alkohola.",
 "en": "The tramezzino — the crustless sandwich all Italy eats today — was invented at the counter of Caffè Mulassano on Piazza Castello, and it was Gabriele D'Annunzio who named it, because the word *sandwich* was not Italian enough. The vermouths that carry the name are made in Piedmont to historic recipes, on a base of Piedmontese white wine rather than neutral alcohol.",
 "it": "Il tramezzino — il panino senza crosta che oggi mangia tutta l'Italia — fu inventato al banco del Caffè Mulassano in piazza Castello, e a battezzarlo fu Gabriele D'Annunzio, perché la parola *sandwich* non era abbastanza italiana. I vermouth che ne portano il nome si fanno in Piemonte su ricette storiche, a base di vino bianco piemontese e non di alcol neutro.",
 "fr": "Le tramezzino — le sandwich sans croûte que toute l'Italie mange aujourd'hui — a été inventé au comptoir du Caffè Mulassano, piazza Castello, et c'est Gabriele D'Annunzio qui l'a baptisé, parce que le mot *sandwich* n'était pas assez italien. Les vermouths qui portent ce nom se font en Piémont selon des recettes historiques, sur une base de vin blanc piémontais et non d'alcool neutre.",
 "de": "Das Tramezzino — das rindenlose Sandwich, das heute ganz Italien isst — wurde am Tresen des Caffè Mulassano an der Piazza Castello erfunden, und getauft hat es Gabriele D'Annunzio, weil das Wort *Sandwich* nicht italienisch genug war. Die Wermuts, die diesen Namen tragen, entstehen im Piemont nach historischen Rezepturen, auf der Basis piemontesischen Weißweins statt neutralen Alkohols.",
 "sl": "Tramezzino — sendvič brez skorje, ki ga danes je vsa Italija — so izumili za šankom kavarne Mulassano na Piazzi Castello, ime pa mu je dal Gabriele D'Annunzio, ker beseda *sandwich* ni bila dovolj italijanska. Vermuti, ki nosijo to ime, nastajajo v Piemontu po zgodovinskih recepturah, na osnovi piemontskega belega vina in ne nevtralnega alkohola.",
 "es": "El tramezzino — el sándwich sin corteza que hoy come toda Italia — se inventó en la barra del Caffè Mulassano, en la piazza Castello, y quien lo bautizó fue Gabriele D'Annunzio, porque la palabra *sandwich* no era bastante italiana. Los vermuts que llevan ese nombre se hacen en el Piamonte con recetas históricas, sobre una base de vino blanco piamontés y no de alcohol neutro.",
 "zh": "tramezzino——如今全意大利都在吃的那种去边三明治——就是在城堡广场上 Mulassano 咖啡馆的吧台边发明的，而给它起名的是加布里埃莱·邓南遮，因为 *sandwich* 这个词不够意大利。挂着这个名字的味美思在皮埃蒙特按历史配方制作，基酒用的是皮埃蒙特白葡萄酒，而不是中性酒精。"
}

NEW["Lorenzo Inga"] = {
 "hr": "Grappa je na loš glas došla zbog čekanja: komina koja danima stoji oksidira, i to se poslije ne da popraviti nikakvim kotlom. Ovdje se bere svježa i destilira odmah, iste jeseni, dok još miriše na grožđe a ne na podrum. Pijemontska kuća koja radi upravo ono što je grappi bilo potrebno da je ljudi ponovno počnu naručivati.",
 "en": "Grappa got its bad name by waiting: pomace left standing for days oxidises, and no still afterwards can undo it. Here it is taken fresh and distilled at once, the same autumn, while it still smells of grapes and not of the cellar. A Piedmontese house doing exactly what grappa needed in order for people to start ordering it again.",
 "it": "La grappa si è fatta la cattiva fama aspettando: la vinaccia lasciata ferma per giorni si ossida, e dopo non c'è alambicco che rimedi. Qui la si prende fresca e si distilla subito, nello stesso autunno, quando profuma ancora di uva e non di cantina. Una casa piemontese che fa esattamente ciò di cui la grappa aveva bisogno perché la gente tornasse a ordinarla.",
 "fr": "La grappa doit sa mauvaise réputation à l'attente : un marc laissé plusieurs jours s'oxyde, et aucun alambic n'y remédie ensuite. Ici, on le prend frais et on le distille aussitôt, le même automne, quand il sent encore le raisin et non la cave. Une maison piémontaise qui fait précisément ce dont la grappa avait besoin pour qu'on se remette à en commander.",
 "de": "Ihren schlechten Ruf hat die Grappa vom Warten: Trester, der tagelang steht, oxidiert, und keine Brennblase macht das hinterher wieder gut. Hier wird er frisch geholt und sofort gebrannt, im selben Herbst, solange er noch nach Trauben riecht und nicht nach Keller. Ein piemontesisches Haus, das genau das tut, was die Grappa brauchte, damit man sie wieder bestellt.",
 "sl": "Grappa je na slab glas prišla zaradi čakanja: tropine, ki stojijo več dni, oksidirajo, in tega pozneje ne popravi noben kotel. Tu jih vzamejo sveže in destilirajo takoj, isto jesen, dokler še dišijo po grozdju in ne po kleti. Piemontska hiša, ki dela natanko to, kar je grappa potrebovala, da bi jo ljudje spet začeli naročati.",
 "es": "La grappa se ganó su mala fama esperando: el orujo que se deja días se oxida, y después no hay alambique que lo arregle. Aquí se toma fresco y se destila enseguida, el mismo otoño, cuando aún huele a uva y no a bodega. Una casa piamontesa que hace exactamente lo que la grappa necesitaba para que la gente volviera a pedirla.",
 "zh": "格拉帕的坏名声，是等出来的：果渣放上几天就会氧化，之后再好的蒸馏器也救不回来。这里的果渣是新鲜取来、当即蒸馏的，就在同一个秋天，趁它闻起来还是葡萄，而不是地窖。一家皮埃蒙特酒厂，做的正是格拉帕要让人重新点单所需要的事。"
}

NEW["Aviation"] = {
 "hr": "Gin koji je namjerno spustio borovicu s prvog mjesta: umjesto oštrog londonskog uboda dolaze lavanda, kardamom i sarsaparila. Amerikanci tu školu zovu New Western, a Aviation ju je iz Portlanda i otvorio. Godine 2018. kupio ga je Ryan Reynolds, snimio nekoliko reklama i dvije godine poslije prodao ga za 610 milijuna dolara — što je vjerojatno najbolje plaćeni gin-tonic u povijesti.",
 "en": "A gin that deliberately took juniper off the front: instead of the sharp London jab come lavender, cardamom and sarsaparilla. Americans call the school New Western, and Aviation opened it, out of Portland. In 2018 Ryan Reynolds bought it, made a few adverts, and sold it two years later for 610 million dollars — probably the best-paid gin and tonic in history.",
 "it": "Un gin che ha tolto di proposito il ginepro dal primo posto: al posto della stoccata londinese arrivano lavanda, cardamomo e salsapariglia. Gli americani chiamano quella scuola New Western, e ad aprirla è stato Aviation, da Portland. Nel 2018 lo comprò Ryan Reynolds, girò qualche spot e due anni dopo lo rivendette per 610 milioni di dollari — probabilmente il gin tonic meglio pagato della storia.",
 "fr": "Un gin qui a délibérément retiré le genièvre du premier rang : à la place du coup de poing londonien viennent la lavande, la cardamome et la salsepareille. Les Américains appellent cette école New Western, et c'est Aviation qui l'a ouverte, depuis Portland. En 2018, Ryan Reynolds l'a racheté, a tourné quelques publicités et l'a revendu deux ans plus tard 610 millions de dollars — probablement le gin tonic le mieux payé de l'histoire.",
 "de": "Ein Gin, der den Wacholder mit Absicht aus der ersten Reihe genommen hat: statt des scharfen Londoner Stichs kommen Lavendel, Kardamom und Sarsaparille. Die Amerikaner nennen diese Schule New Western, und eröffnet hat sie Aviation, aus Portland. 2018 kaufte Ryan Reynolds die Marke, drehte ein paar Werbespots und verkaufte sie zwei Jahre später für 610 Millionen Dollar — vermutlich der bestbezahlte Gin Tonic der Geschichte.",
 "sl": "Gin, ki je brinje namenoma umaknil s prvega mesta: namesto ostrega londonskega vboda pridejo sivka, kardamom in sarsaparila. Američani to šolo imenujejo New Western, odprl pa jo je prav Aviation iz Portlanda. Leta 2018 ga je kupil Ryan Reynolds, posnel nekaj reklam in ga dve leti pozneje prodal za 610 milijonov dolarjev — najbrž najbolje plačan gin tonik v zgodovini.",
 "es": "Una ginebra que quitó el enebro del primer puesto a propósito: en lugar del pinchazo londinense llegan lavanda, cardamomo y zarzaparrilla. Los americanos llaman a esa escuela New Western, y fue Aviation, desde Portland, quien la abrió. En 2018 la compró Ryan Reynolds, rodó unos anuncios y dos años después la vendió por 610 millones de dólares — probablemente el gin-tonic mejor pagado de la historia.",
 "zh": "一款故意把杜松从首位撤下的金酒：取代伦敦式那一记锐利刺击的，是薰衣草、豆蔻与菝葜。美国人管这个流派叫 New Western，而开创它的正是来自波特兰的 Aviation。2018 年，瑞安·雷诺兹买下了它，拍了几支广告，两年后以 6.1 亿美元卖出——大概是史上报酬最高的一杯金汤力。"
}

NEW["Westward"] = {
 "hr": "Viski koji počinje kao pivo, i to nije figura: sladovinu vare kao ale, s pivskim kvascem, i puste je da fermentira danima prije nego što uopće uđe u kotao. Kuću je u Portlandu otvorio pivar, pa se to i osjeti — kruh, breskva, voće kakvog u škotskom maltu nema. Američki single malt koji ne pokušava zvučati škotski.",
 "en": "A whiskey that starts as beer, and not figuratively: the wash is brewed like an ale, with ale yeast, and left to ferment for days before it ever reaches the still. The house was opened in Portland by a brewer, and it shows — bread, peach, a fruit Scottish malt does not have. An American single malt that does not try to sound Scottish.",
 "it": "Un whisky che comincia come birra, e non per modo di dire: il mosto si fa come una ale, con lievito da birra, e lo si lascia fermentare per giorni prima ancora che entri nell'alambicco. La casa l'ha aperta a Portland un birraio, e si sente — pane, pesca, una frutta che il malto scozzese non ha. Un single malt americano che non prova a suonare scozzese.",
 "fr": "Un whiskey qui commence comme une bière, et pas au figuré : le moût est brassé comme une ale, avec des levures de brasserie, et fermente plusieurs jours avant même d'entrer dans l'alambic. La maison a été ouverte à Portland par un brasseur, et cela s'entend — du pain, de la pêche, un fruit que le malt écossais n'a pas. Un single malt américain qui n'essaie pas de sonner écossais.",
 "de": "Ein Whiskey, der als Bier beginnt, und das nicht im übertragenen Sinn: Die Maische wird wie ein Ale gebraut, mit Bierhefe, und gärt tagelang, bevor sie überhaupt in die Brennblase kommt. Gegründet hat das Haus in Portland ein Brauer, und man schmeckt es — Brot, Pfirsich, eine Frucht, die schottischer Malt nicht hat. Ein amerikanischer Single Malt, der nicht versucht, schottisch zu klingen.",
 "sl": "Viski, ki se začne kot pivo, in to ni figura: drozgo skuhajo kot ale, s pivskim kvasom, in jo pustijo vreti več dni, preden sploh pride v kotel. Hišo je v Portlandu odprl pivovar, in to se pozna — kruh, breskev, sadje, kakršnega škotski slad nima. Ameriški single malt, ki se ne trudi zveneti škotsko.",
 "es": "Un whisky que empieza como cerveza, y no en sentido figurado: el mosto se elabora como una ale, con levadura cervecera, y se deja fermentar días antes de llegar siquiera al alambique. La casa la abrió en Portland un cervecero, y se nota — pan, melocotón, una fruta que el malta escocés no tiene. Un single malt americano que no intenta sonar escocés.",
 "zh": "一款从啤酒开始的威士忌，而且不是比喻：酒汁像艾尔啤酒那样酿造，用啤酒酵母，先发酵好几天，才进蒸馏器。这家酒厂在波特兰由一位酿酒师（啤酒的那种）创办，喝得出来——面包、桃子，一种苏格兰麦芽威士忌没有的果味。一款不试图听起来像苏格兰的美国单一麦芽。"
}

NEW["Redemption"] = {
 "hr": "Raž je bila američko piće prije nego što je prohibicija gotovo izbrisala — i tek se sad vraća. Ime na boci nije ime destilerije: raž dolazi iz Indiane, iz pogona koji tiho puni pola američkog tržišta, a Redemption bira bačve i drži postotak raži visoko, ondje gdje ga većina spušta. Iskren posrednik u kategoriji punoj njih.",
 "en": "Rye was the American drink before Prohibition all but wiped it out — and it is only now coming back. The name on the bottle is not the name of a distillery: the rye comes from Indiana, from a plant that quietly fills half the American market, and Redemption picks the barrels and keeps the rye percentage high where most keep it low. An honest middleman in a category full of them.",
 "it": "La segale era la bevanda americana prima che il proibizionismo la cancellasse quasi del tutto — e solo adesso sta tornando. Il nome in etichetta non è quello di una distilleria: il rye viene dall'Indiana, da uno stabilimento che riempie in silenzio metà del mercato americano, e Redemption sceglie le botti e tiene alta la percentuale di segale dove i più la tengono bassa. Un intermediario onesto in una categoria che ne è piena.",
 "fr": "Le seigle était la boisson américaine avant que la prohibition ne l'efface presque — et il ne revient que maintenant. Le nom sur la bouteille n'est pas celui d'une distillerie : le rye vient de l'Indiana, d'une usine qui remplit discrètement la moitié du marché américain, et Redemption choisit les fûts et garde le taux de seigle haut là où la plupart le baissent. Un intermédiaire honnête dans une catégorie qui en regorge.",
 "de": "Roggen war das amerikanische Getränk, bevor die Prohibition ihn beinahe auslöschte — und erst jetzt kommt er zurück. Der Name auf der Flasche ist kein Brennereiname: Der Rye stammt aus Indiana, aus einem Werk, das leise den halben US-Markt füllt, und Redemption wählt die Fässer aus und hält den Roggenanteil hoch, wo ihn die meisten niedrig halten. Ein ehrlicher Zwischenhändler in einer Kategorie voller Zwischenhändler.",
 "sl": "Rž je bila ameriška pijača, preden jo je prohibicija skoraj izbrisala — in šele zdaj se vrača. Ime na steklenici ni ime destilarne: rž prihaja iz Indiane, iz obrata, ki tiho polni polovico ameriškega trga, Redemption pa izbira sode in odstotek rži drži visoko tam, kjer ga večina spušča. Pošten posrednik v kategoriji, ki jih je polna.",
 "es": "El centeno era la bebida americana antes de que la ley seca casi lo borrara — y sólo ahora vuelve. El nombre de la botella no es el de una destilería: el rye viene de Indiana, de una planta que llena en silencio medio mercado americano, y Redemption elige las barricas y mantiene alto el porcentaje de centeno donde la mayoría lo baja. Un intermediario honesto en una categoría llena de ellos.",
 "zh": "在禁酒令几乎把它抹去之前，黑麦本是美国人的酒——如今才刚刚回来。瓶上的名字并不是某家酒厂的名字：原酒来自印第安纳一家安静地供应了半个美国市场的工厂，而 Redemption 负责挑桶，并在别人普遍压低黑麦比例的地方把它保持得很高。在一个满是中间商的品类里，这是个诚实的中间商。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-20s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
