# -*- coding: utf-8 -*-
"""Spirits, batch two (2026-08-12): Mulassano's missing link, Aviation opening
where the owner wants it, and the Scottish five plus the singles.

Mulassano: the café and the vermouth are connected by a person. Pietro
Bordiga, who had just founded his distillery in Cuneo, worked out a recipe
*for* Amilcare Mulassano, to be poured to the café's guests — and Bordiga
still makes it. That is the sentence the card was missing.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Mulassano"] = {
 "hr": "Tramezzino — sendvič bez korice koji danas jede cijela Italija — izmišljen je za šankom ovog kafića na Piazzi Castello, a ime mu je dao Gabriele D'Annunzio, jer *sandwich* nije bio dovoljno talijanski. Vermut je nastao na isti način: Pietro Bordiga, koji je upravo bio otvorio destileriju u Cuneu, složio je recepturu za Amilcarea Mulassana, za goste kafića. Bordiga ga i danas radi, s alpskim biljem branim rukom.",
 "en": "The tramezzino — the crustless sandwich all Italy eats today — was invented at the counter of this café on Piazza Castello, and Gabriele D'Annunzio named it, because *sandwich* was not Italian enough. The vermouth came about the same way: Pietro Bordiga, who had just opened his distillery in Cuneo, worked out a recipe for Amilcare Mulassano, to be poured to the café's guests. Bordiga still makes it, with alpine botanicals picked by hand.",
 "it": "Il tramezzino — il panino senza crosta che oggi mangia tutta l'Italia — fu inventato al banco di questo caffè in piazza Castello, e a battezzarlo fu Gabriele D'Annunzio, perché *sandwich* non era abbastanza italiano. Il vermouth è nato allo stesso modo: Pietro Bordiga, che aveva appena aperto la distilleria a Cuneo, mise a punto una ricetta per Amilcare Mulassano, da servire agli ospiti del caffè. Bordiga lo fa ancora, con erbe alpine raccolte a mano.",
 "fr": "Le tramezzino — le sandwich sans croûte que toute l'Italie mange aujourd'hui — a été inventé au comptoir de ce café, piazza Castello, et c'est Gabriele D'Annunzio qui l'a baptisé, parce que *sandwich* n'était pas assez italien. Le vermouth est né de la même façon : Pietro Bordiga, qui venait d'ouvrir sa distillerie à Cuneo, a mis au point une recette pour Amilcare Mulassano, destinée aux clients du café. Bordiga le fait toujours, avec des plantes alpines cueillies à la main.",
 "de": "Das Tramezzino — das rindenlose Sandwich, das heute ganz Italien isst — wurde am Tresen dieses Cafés an der Piazza Castello erfunden, und getauft hat es Gabriele D'Annunzio, weil *Sandwich* nicht italienisch genug war. Der Wermut entstand auf dieselbe Weise: Pietro Bordiga, der eben seine Brennerei in Cuneo eröffnet hatte, entwarf ein Rezept für Amilcare Mulassano, für die Gäste des Cafés. Bordiga macht ihn bis heute, mit von Hand gepflückten Alpenkräutern.",
 "sl": "Tramezzino — sendvič brez skorje, ki ga danes je vsa Italija — so izumili za šankom te kavarne na Piazzi Castello, ime pa mu je dal Gabriele D'Annunzio, ker *sandwich* ni bil dovolj italijanski. Vermut je nastal na isti način: Pietro Bordiga, ki je prav takrat odprl destilarno v Cuneu, je sestavil recepturo za Amilcareja Mulassana, za goste kavarne. Bordiga ga dela še danes, z ročno nabranimi alpskimi zelišči.",
 "es": "El tramezzino — el sándwich sin corteza que hoy come toda Italia — se inventó en la barra de este café de la piazza Castello, y lo bautizó Gabriele D'Annunzio, porque *sandwich* no era bastante italiano. El vermut nació igual: Pietro Bordiga, que acababa de abrir su destilería en Cuneo, compuso una receta para Amilcare Mulassano, para los clientes del café. Bordiga lo sigue haciendo, con hierbas alpinas recogidas a mano.",
 "zh": "tramezzino——如今全意大利都在吃的那种去边三明治——就是在城堡广场这家咖啡馆的吧台边发明的，命名者是加布里埃莱·邓南遮，因为 *sandwich* 不够意大利。味美思的来历一样：刚在库内奥开设酒厂的皮埃特罗·博尔迪加，为阿米尔卡雷·穆拉萨诺配了一份方子，供咖啡馆的客人喝。这酒至今仍由 Bordiga 制作，用的是手工采摘的阿尔卑斯草药。"
}

NEW["Aviation"] = {
 "hr": "Ryan Reynolds kupio ga je 2018., snimio nekoliko reklama i dvije godine poslije prodao za 610 milijuna dolara — vjerojatno najbolje plaćeni gin-tonic u povijesti. Ono što je kupio nastalo je u Portlandu desetljeće ranije: gin koji je namjerno spustio borovicu s prvog mjesta, pa umjesto oštrog londonskog uboda dolaze lavanda, kardamom i sarsaparila. Amerikanci tu školu zovu New Western, a Aviation ju je i otvorio.",
 "en": "Ryan Reynolds bought it in 2018, made a few adverts and sold it two years later for 610 million dollars — probably the best-paid gin and tonic in history. What he bought had been made in Portland a decade earlier: a gin that deliberately took juniper off the front, so that instead of the sharp London jab come lavender, cardamom and sarsaparilla. Americans call the school New Western, and Aviation is the one that opened it.",
 "it": "Ryan Reynolds lo comprò nel 2018, girò qualche spot e due anni dopo lo rivendette per 610 milioni di dollari — probabilmente il gin tonic meglio pagato della storia. Ciò che aveva comprato era nato a Portland un decennio prima: un gin che ha tolto di proposito il ginepro dal primo posto, così al posto della stoccata londinese arrivano lavanda, cardamomo e salsapariglia. Gli americani chiamano quella scuola New Western, e ad aprirla è stato Aviation.",
 "fr": "Ryan Reynolds l'a racheté en 2018, a tourné quelques publicités et l'a revendu deux ans plus tard 610 millions de dollars — probablement le gin tonic le mieux payé de l'histoire. Ce qu'il avait acheté était né à Portland dix ans plus tôt : un gin qui a délibérément retiré le genièvre du premier rang, si bien qu'à la place du coup de poing londonien viennent la lavande, la cardamome et la salsepareille. Les Américains appellent cette école New Western, et c'est Aviation qui l'a ouverte.",
 "de": "Ryan Reynolds kaufte die Marke 2018, drehte ein paar Werbespots und verkaufte sie zwei Jahre später für 610 Millionen Dollar — vermutlich der bestbezahlte Gin Tonic der Geschichte. Was er gekauft hatte, war ein Jahrzehnt zuvor in Portland entstanden: ein Gin, der den Wacholder mit Absicht aus der ersten Reihe nahm, sodass statt des scharfen Londoner Stichs Lavendel, Kardamom und Sarsaparille kommen. Die Amerikaner nennen diese Schule New Western — eröffnet hat sie Aviation.",
 "sl": "Ryan Reynolds ga je kupil leta 2018, posnel nekaj reklam in ga dve leti pozneje prodal za 610 milijonov dolarjev — najbrž najbolje plačan gin tonik v zgodovini. To, kar je kupil, je nastalo v Portlandu desetletje prej: gin, ki je brinje namenoma umaknil s prvega mesta, tako da namesto ostrega londonskega vboda pridejo sivka, kardamom in sarsaparila. Američani to šolo imenujejo New Western, odprl pa jo je prav Aviation.",
 "es": "Ryan Reynolds la compró en 2018, rodó unos anuncios y dos años después la vendió por 610 millones de dólares — probablemente el gin-tonic mejor pagado de la historia. Lo que compró había nacido en Portland una década antes: una ginebra que quitó el enebro del primer puesto a propósito, de modo que en lugar del pinchazo londinense llegan lavanda, cardamomo y zarzaparrilla. Los americanos llaman a esa escuela New Western, y quien la abrió fue Aviation.",
 "zh": "瑞安·雷诺兹 2018 年买下它，拍了几支广告，两年后以 6.1 亿美元卖出——大概是史上报酬最高的一杯金汤力。而他买下的这东西，十年前诞生在波特兰：一款故意把杜松从首位撤下的金酒，于是取代伦敦式那记锐利刺击的，是薰衣草、豆蔻与菝葜。美国人管这个流派叫 New Western，开创它的正是 Aviation。"
}

# ---- Scotland ---------------------------------------------------------------

NEW["Kilchoman"] = {
 "hr": "Prva nova destilerija na Islayu nakon 124 godine, otvorena 2005. na farmi koja i danas sije vlastiti ječam, sama ga slaguje na podu i sve ostalo radi unutar istog dvorišta — jedina na otoku koja cijeli put od sjemena do boce prijeđe bez izlaska kroz kapiju. Ostali kupuju slad s kopna. Farma koja peče viski, ne tvornica koja glumi farmu.",
 "en": "The first new distillery on Islay in 124 years, opened in 2005 on a farm that still sows its own barley, floor-malts it and does everything else inside the same yard — the only one on the island that goes from seed to bottle without passing through the gate. The others buy their malt from the mainland. A farm that makes whisky, not a factory playing at being a farm.",
 "it": "La prima distilleria nuova a Islay dopo 124 anni, aperta nel 2005 in una fattoria che semina ancora il proprio orzo, lo malta sul pavimento e fa tutto il resto dentro la stessa corte — l'unica sull'isola che vada dal seme alla bottiglia senza uscire dal cancello. Gli altri comprano il malto dalla terraferma. Una fattoria che fa whisky, non una fabbrica che gioca a fare la fattoria.",
 "fr": "La première distillerie nouvelle à Islay depuis 124 ans, ouverte en 2005 sur une ferme qui sème encore son propre orge, le malte sur aire et fait tout le reste dans la même cour — la seule de l'île à aller de la graine à la bouteille sans franchir le portail. Les autres achètent leur malt sur le continent. Une ferme qui fait du whisky, pas une usine qui joue à la ferme.",
 "de": "Die erste neue Brennerei auf Islay seit 124 Jahren, 2005 auf einem Hof eröffnet, der bis heute seine eigene Gerste sät, sie auf der Tenne mälzt und alles Weitere im selben Hof erledigt — die einzige der Insel, die vom Korn bis zur Flasche kein Tor passiert. Die anderen kaufen ihr Malz vom Festland. Ein Hof, der Whisky macht, keine Fabrik, die Hof spielt.",
 "sl": "Prva nova destilarna na Islayu po 124 letih, odprta leta 2005 na kmetiji, ki še vedno seje lasten ječmen, ga sama slaja na tleh in vse drugo opravi znotraj istega dvorišča — edina na otoku, ki pot od semena do steklenice prehodi brez izhoda skozi vrata. Drugi slad kupujejo s celine. Kmetija, ki dela viski, ne tovarna, ki se gre kmetijo.",
 "es": "La primera destilería nueva en Islay en 124 años, abierta en 2005 en una granja que aún siembra su propia cebada, la maltea en suelo y hace todo lo demás dentro del mismo patio — la única de la isla que va de la semilla a la botella sin cruzar la verja. Los demás compran la malta en el continente. Una granja que hace whisky, no una fábrica que juega a ser granja.",
 "zh": "艾雷岛 124 年来的第一家新酒厂，2005 年开在一座农场里：这里至今自种大麦、自行地板发麦，其余工序也全在同一个院子里完成——全岛唯一一家从种子到装瓶都不出大门的酒厂。其他人都从本岛之外买麦芽。这是一座做威士忌的农场，而不是一间扮成农场的工厂。"
}

NEW["Glenrothes"] = {
 "hr": "Stoljeće je radio za tuđe kupaže — bez njega ne bi bilo ni Cutty Sarka ni Famous Grousea — i tek onda pustio vlastito ime na bocu. Zato ovdje broje berbe, ne godine: svaka boca kaže kad je destilirana, kao vino, jer kuća drži da 1998. i 2015. nisu ista stvar ni kad su jednako stare. Speyside bez dima i bez pokazivanja.",
 "en": "For a century it worked for other people's blends — there would be no Cutty Sark and no Famous Grouse without it — and only then let its own name onto the bottle. Which is why they count vintages here, not years: every bottle says when it was distilled, like wine, because the house holds that 1998 and 2015 are not the same thing even when they are the same age. Speyside without smoke and without showing off.",
 "it": "Per un secolo ha lavorato per i blend degli altri — senza di lui non ci sarebbero né Cutty Sark né Famous Grouse — e solo dopo ha messo il proprio nome in bottiglia. Per questo qui contano le annate, non gli anni: ogni bottiglia dice quando è stata distillata, come un vino, perché la casa ritiene che il 1998 e il 2015 non siano la stessa cosa nemmeno alla stessa età. Speyside senza fumo e senza mettersi in mostra.",
 "fr": "Un siècle durant, elle a travaillé pour les assemblages des autres — sans elle, pas de Cutty Sark ni de Famous Grouse — et n'a mis son nom sur la bouteille qu'ensuite. D'où les millésimes plutôt que les âges : chaque bouteille dit quand elle a été distillée, comme un vin, parce que la maison tient que 1998 et 2015 ne sont pas la même chose, même au même âge. Un Speyside sans fumée et sans esbroufe.",
 "de": "Ein Jahrhundert lang arbeitete sie für fremde Blends — ohne sie gäbe es weder Cutty Sark noch Famous Grouse — und ließ erst danach den eigenen Namen auf die Flasche. Darum zählt man hier Jahrgänge, nicht Jahre: Jede Flasche sagt, wann sie gebrannt wurde, wie bei Wein, weil das Haus findet, 1998 und 2015 seien nicht dasselbe, auch wenn sie gleich alt sind. Speyside ohne Rauch und ohne Auftritt.",
 "sl": "Stoletje je delala za tuje zvrsti — brez nje ne bi bilo ne Cutty Sarka ne Famous Grousea — in šele nato spustila lastno ime na steklenico. Zato tu štejejo letnike, ne let: vsaka steklenica pove, kdaj je bila destilirana, kot pri vinu, ker hiša meni, da 1998 in 2015 nista ista stvar niti pri isti starosti. Speyside brez dima in brez razkazovanja.",
 "es": "Durante un siglo trabajó para las mezclas de otros — sin ella no habría ni Cutty Sark ni Famous Grouse — y sólo después dejó su nombre en la botella. Por eso aquí cuentan añadas, no años: cada botella dice cuándo se destiló, como un vino, porque la casa sostiene que 1998 y 2015 no son lo mismo ni siquiera con la misma edad. Speyside sin humo y sin exhibirse.",
 "zh": "它为别人的调和威士忌干了一个世纪——没有它，就没有顺风，也没有威雀——之后才把自己的名字放上瓶身。所以这里数的是年份，不是酒龄：每一瓶都写明何时蒸馏，像葡萄酒一样，因为酒厂认为 1998 与 2015 即便同龄也不是一回事。这是不带烟熏、也不炫技的斯佩塞。"
}

NEW["Isle of Jura"] = {
 "hr": "Otok s jednom cestom, jednom destilerijom, dvjestotinjak ljudi i nekoliko tisuća jelena. George Orwell došao je tu 1946. u kuću bez struje i telefona na sjevernom kraju otoka, do koje se zadnjih 11 kilometara ide pješice, i napisao 1984. Sam ju je opisao kao mjesto „do kojeg se ne da doći”. Viski je isti takav: bez dima, bez žurbe, bez publike.",
 "en": "An island with one road, one distillery, some two hundred people and several thousand deer. George Orwell came here in 1946, to a house at the northern end with no electricity and no telephone, the last 11 kilometres of it on foot, and wrote 1984. He described the place himself as \"extremely un-get-at-able\". The whisky is the same: no smoke, no hurry, no audience.",
 "it": "Un'isola con una strada, una distilleria, un paio di centinaia di persone e qualche migliaio di cervi. George Orwell arrivò qui nel 1946, in una casa all'estremità nord senza elettricità né telefono, gli ultimi 11 chilometri a piedi, e ci scrisse 1984. Del posto disse lui stesso che era \"assolutamente irraggiungibile\". Il whisky è uguale: senza fumo, senza fretta, senza pubblico.",
 "fr": "Une île avec une route, une distillerie, quelque deux cents habitants et plusieurs milliers de cerfs. George Orwell est venu ici en 1946, dans une maison de l'extrémité nord sans électricité ni téléphone, les 11 derniers kilomètres à pied, et y a écrit 1984. Il décrivait lui-même l'endroit comme « absolument inaccessible ». Le whisky est pareil : sans fumée, sans hâte, sans public.",
 "de": "Eine Insel mit einer Straße, einer Brennerei, gut zweihundert Menschen und mehreren tausend Hirschen. George Orwell kam 1946 hierher, in ein Haus am Nordende ohne Strom und Telefon, die letzten 11 Kilometer zu Fuß, und schrieb 1984. Den Ort nannte er selbst „völlig unerreichbar“. Der Whisky ist genauso: ohne Rauch, ohne Eile, ohne Publikum.",
 "sl": "Otok z eno cesto, eno destilarno, kakšnimi dvesto ljudmi in nekaj tisoč jeleni. George Orwell je prišel sem leta 1946, v hišo na severnem koncu brez elektrike in telefona, zadnjih 11 kilometrov peš, in napisal 1984. Kraj je sam opisal kot »povsem nedosegljiv«. Viski je enak: brez dima, brez naglice, brez občinstva.",
 "es": "Una isla con una carretera, una destilería, unas doscientas personas y varios miles de ciervos. George Orwell llegó aquí en 1946, a una casa del extremo norte sin electricidad ni teléfono, los últimos 11 kilómetros a pie, y escribió 1984. Del lugar dijo él mismo que era \"absolutamente inalcanzable\". El whisky es igual: sin humo, sin prisa, sin público.",
 "zh": "一座只有一条路、一家酒厂、两百来人和几千头鹿的岛。1946 年，乔治·奥威尔来到这里，住进岛北端一栋没有电、也没有电话的房子——最后 11 公里只能步行——并在那里写下了《1984》。他自己形容那地方「根本到不了」。威士忌也是这样：没有烟熏，不赶时间，也不为观众。"
}

NEW["Bladnoch"] = {
 "hr": "Najjužnija destilerija Škotske, uz rijeku u Wigtownshireu od 1817., zatvarana i otvarana toliko puta da je čudo što još stoji. Zadnji put oživio ju je 2015. Australac David Prior — čovjek koji je novac zaradio na organskom jogurtu, pa ga uložio u Lowlands. U podrumu je zatekao bačve koje su ondje tiho ležale 19 godina. Danas radi tiho, daleko od svih.",
 "en": "Scotland's southernmost distillery, on the river in Wigtownshire since 1817, closed and reopened so many times it is a wonder it still stands. It was last revived in 2015 by the Australian David Prior — a man who made his money in organic yoghurt and put it into the Lowlands. In the warehouse he found casks that had been quietly lying there for 19 years. It works quietly today, far from everyone.",
 "it": "La distilleria più a sud della Scozia, sul fiume nel Wigtownshire dal 1817, chiusa e riaperta tante volte che è un miracolo sia ancora in piedi. L'ultima resurrezione è del 2015, per mano dell'australiano David Prior — uno che ha fatto i soldi con lo yogurt biologico e li ha messi nelle Lowlands. In magazzino ha trovato botti che stavano lì in silenzio da 19 anni. Oggi lavora in silenzio, lontano da tutti.",
 "fr": "La distillerie la plus au sud d'Écosse, au bord de la rivière dans le Wigtownshire depuis 1817, fermée et rouverte tant de fois que c'est un miracle qu'elle tienne encore. La dernière résurrection date de 2015, par l'Australien David Prior — un homme qui a fait fortune dans le yaourt bio et l'a investie dans les Lowlands. Dans le chai, il a trouvé des fûts qui dormaient là depuis 19 ans. Elle travaille aujourd'hui sans bruit, loin de tout.",
 "de": "Die südlichste Brennerei Schottlands, seit 1817 am Fluss in Wigtownshire, so oft geschlossen und wieder geöffnet, dass es ein Wunder ist, dass sie noch steht. Zuletzt weckte sie 2015 der Australier David Prior — ein Mann, der sein Geld mit Bio-Joghurt verdient und es in die Lowlands gesteckt hat. Im Lager fand er Fässer, die dort still 19 Jahre gelegen hatten. Heute arbeitet sie leise, weit weg von allem.",
 "sl": "Najjužnejša destilarna Škotske, ob reki v Wigtownshiru od leta 1817, zaprta in odprta tolikokrat, da je čudež, da še stoji. Nazadnje jo je leta 2015 oživil Avstralec David Prior — človek, ki je denar zaslužil z ekološkim jogurtom in ga vložil v Lowlands. V skladišču je našel sode, ki so tam tiho ležali 19 let. Danes dela tiho, daleč od vseh.",
 "es": "La destilería más meridional de Escocia, junto al río en Wigtownshire desde 1817, cerrada y reabierta tantas veces que es un milagro que siga en pie. La última resurrección es de 2015, obra del australiano David Prior — un hombre que hizo su dinero con yogur ecológico y lo puso en las Lowlands. En la nave encontró barricas que llevaban allí, calladas, 19 años. Hoy trabaja en silencio, lejos de todos.",
 "zh": "苏格兰最南端的酒厂，自 1817 年起就在威格敦郡的河边，关了又开、开了又关，多到能撑到今天堪称奇迹。最近一次让它复活的是澳大利亚人大卫·普赖尔——一个靠有机酸奶赚到钱、又把钱投进低地区的人。他在仓库里发现了一批已经安静躺了 19 年的桶。如今它仍在安静地运转，远离所有人。"
}

NEW["Glenmorangie"] = {
 "hr": "U Tainu stoje najviši kotlovi u Škotskoj — visoki koliko i odrasla žirafa. Samo najlakše pare stignu do vrha, i zato je ovaj viski uvijek bio više cvijet nego dim. Signet ide korak dalje: dio ječma peče se do čokoladnog slada, onakvog kakav se inače koristi za stout, pa se u čaši nađe nešto što u single maltu ne bi trebalo biti — kava.",
 "en": "The tallest stills in Scotland stand at Tain — as tall as a grown giraffe. Only the lightest vapours reach the top, which is why this whisky has always been more flower than smoke. Signet goes a step further: part of the barley is roasted to chocolate malt, the kind normally used for stout, so something turns up in the glass that has no business in a single malt — coffee.",
 "it": "A Tain stanno gli alambicchi più alti di Scozia — alti quanto una giraffa adulta. Solo i vapori più leggeri arrivano in cima, ed è per questo che questo whisky è sempre stato più fiore che fumo. Il Signet va oltre: parte dell'orzo è tostato fino a malto cioccolato, quello che di solito si usa per la stout, e nel bicchiere compare qualcosa che in un single malt non dovrebbe esserci — il caffè.",
 "fr": "À Tain se dressent les plus hauts alambics d'Écosse — hauts comme une girafe adulte. Seules les vapeurs les plus légères atteignent le sommet, et c'est pourquoi ce whisky a toujours été plus fleur que fumée. Le Signet va plus loin : une partie de l'orge est torréfiée en malt chocolat, celui qu'on emploie d'ordinaire pour la stout, et il apparaît dans le verre une chose qui n'a rien à faire dans un single malt — du café.",
 "de": "In Tain stehen die höchsten Brennblasen Schottlands — so hoch wie eine ausgewachsene Giraffe. Nur die leichtesten Dämpfe kommen oben an, und darum war dieser Whisky immer mehr Blüte als Rauch. Signet geht weiter: Ein Teil der Gerste wird zu Schokoladenmalz geröstet, wie man es sonst für Stout nimmt, und im Glas taucht etwas auf, das in einem Single Malt nichts zu suchen hat — Kaffee.",
 "sl": "V Tainu stojijo najvišji kotli na Škotskem — visoki kot odrasla žirafa. Le najlažje pare pridejo do vrha, in prav zato je bil ta viski vedno bolj cvet kot dim. Signet gre še dlje: del ječmena je pražen do čokoladnega slada, takšnega, kakršen se sicer uporablja za stout, in v kozarcu se znajde nekaj, česar v single maltu ne bi smelo biti — kava.",
 "es": "En Tain están los alambiques más altos de Escocia — tan altos como una jirafa adulta. Sólo los vapores más ligeros llegan arriba, y por eso este whisky siempre fue más flor que humo. El Signet va más lejos: parte de la cebada se tuesta hasta malta chocolate, la que se usa normalmente para la stout, y en la copa aparece algo que no debería estar en un single malt — café.",
 "zh": "苏格兰最高的蒸馏器就立在泰恩——高得像一头成年长颈鹿。只有最轻的蒸气能升到顶端，所以这款威士忌向来是花，而不是烟。Signet 更进一步：一部分大麦被烘成巧克力麦芽，也就是通常拿来做世涛的那种，于是杯中出现了一样本不该在单一麦芽里出现的东西——咖啡。"
}

# ---- the singles ------------------------------------------------------------

NEW["Kavalan"] = {
 "hr": "Tajvan je za viski krivo mjesto — vruće, vlažno, bez tresetišta i bez tradicije. Kavalan je 2005. svejedno počeo, a 2010. u Edinburghu, na slijepoj kušnji, pobijedio nekoliko škotskih maltova; sudci su mislili da kušaju Škota. U Yilanu bačva u 3 godine napravi ono za što na Speysideu treba deset, ali se i gubi: anđeoski dio ovdje pojede oko 15 % godišnje, sedam puta više nego u Škotskoj.",
 "en": "Taiwan is the wrong place for whisky — hot, humid, no peat and no tradition. Kavalan started anyway in 2005, and in 2010, at a blind tasting in Edinburgh, beat several Scottish malts; the judges thought they were tasting a Scot. In Yilan a cask does in 3 years what takes ten on Speyside, but it also loses: the angels' share here eats about 15% a year, seven times what it does in Scotland.",
 "it": "Taiwan è il posto sbagliato per il whisky — caldo, umido, senza torba e senza tradizione. Kavalan ha cominciato lo stesso nel 2005, e nel 2010, a una degustazione alla cieca a Edimburgo, ha battuto diversi malti scozzesi; i giudici credevano di assaggiare uno scozzese. A Yilan una botte fa in 3 anni ciò che sullo Speyside richiede dieci anni, ma perde anche: la parte degli angeli qui si mangia circa il 15% l'anno, sette volte più che in Scozia.",
 "fr": "Taïwan est le mauvais endroit pour le whisky — chaud, humide, sans tourbe et sans tradition. Kavalan a commencé quand même en 2005, et en 2010, lors d'une dégustation à l'aveugle à Édimbourg, a battu plusieurs malts écossais ; les juges croyaient goûter un Écossais. À Yilan, un fût fait en 3 ans ce qui en demande dix sur le Speyside, mais il perd aussi : la part des anges dévore ici quelque 15% par an, sept fois plus qu'en Écosse.",
 "de": "Taiwan ist der falsche Ort für Whisky — heiß, feucht, ohne Torf und ohne Tradition. Kavalan fing 2005 trotzdem an und schlug 2010 bei einer Blindprobe in Edinburgh mehrere schottische Malts; die Juroren glaubten, einen Schotten im Glas zu haben. In Yilan schafft ein Fass in 3 Jahren, wofür es an der Speyside zehn braucht, verliert dabei aber auch: Der Engelsanteil frisst hier rund 15% im Jahr, siebenmal so viel wie in Schottland.",
 "sl": "Tajvan je za viski napačen kraj — vroč, vlažen, brez šote in brez tradicije. Kavalan je leta 2005 vseeno začel, leta 2010 pa je na slepi pokušini v Edinburghu premagal več škotskih sladov; sodniki so mislili, da pokušajo Škota. V Yilanu sod v 3 letih naredi to, za kar je na Speysideu potrebnih deset, a tudi izgublja: angelski delež tu poje okoli 15% na leto, sedemkrat več kot na Škotskem.",
 "es": "Taiwán es el sitio equivocado para el whisky — caluroso, húmedo, sin turba y sin tradición. Kavalan empezó igualmente en 2005 y en 2010, en una cata a ciegas en Edimburgo, venció a varios maltas escoceses; los jueces creían estar catando un escocés. En Yilan una barrica hace en 3 años lo que en Speyside pide diez, pero también pierde: la parte de los ángeles se come aquí un 15% al año, siete veces más que en Escocia.",
 "zh": "台湾本是做威士忌的错误地点——又热又湿，没有泥煤，也没有传统。噶玛兰还是在 2005 年开了工，并在 2010 年爱丁堡的一场盲品里击败了数款苏格兰麦芽；评审当时以为自己喝的是苏格兰酒。在宜兰，一只桶 3 年就能做到斯佩塞十年的事，但也在失去：这里的「天使份额」每年吃掉约 15%，是苏格兰的七倍。"
}

NEW["Beenleigh"] = {
 "hr": "Najstarija registrirana destilerija u Australiji, u Queenslandu gdje trska raste bolje nego na Karibima. Prvi kotao, kako priča kuća, skinut je s parobroda koji je rum pekao ilegalno ploveći rijekom — kad su ga uhvatili, oprema je završila na obali i dobila dozvolu. Gotovo ništa odavde ne izađe iz zemlje: Australci svoj rum popiju sami.",
 "en": "Australia's oldest registered distillery, in Queensland, where cane grows better than it does in the Caribbean. The first still, as the house tells it, was taken off a paddle steamer that had been making rum illegally while moving down the river — when they caught it, the equipment ended up on the bank and was given a licence. Almost nothing leaves the country: Australians drink their rum themselves.",
 "it": "La distilleria registrata più antica d'Australia, nel Queensland, dove la canna cresce meglio che ai Caraibi. Il primo alambicco, come racconta la casa, fu tolto da un battello a vapore che distillava rum illegalmente muovendosi lungo il fiume — quando lo presero, l'attrezzatura finì a riva e ottenne una licenza. Quasi nulla esce dal paese: gli australiani il loro rum se lo bevono da soli.",
 "fr": "La plus ancienne distillerie enregistrée d'Australie, dans le Queensland, où la canne pousse mieux qu'aux Caraïbes. Le premier alambic, à en croire la maison, a été démonté d'un vapeur à aubes qui distillait du rhum illégalement en descendant la rivière — quand on l'a pris, le matériel a fini sur la berge et a reçu une licence. Presque rien ne sort du pays : les Australiens boivent leur rhum eux-mêmes.",
 "de": "Australiens älteste registrierte Brennerei, in Queensland, wo das Zuckerrohr besser wächst als in der Karibik. Die erste Brennblase stammt, so erzählt es das Haus, von einem Raddampfer, der auf dem Fluss illegal Rum brannte — als man ihn erwischte, landete die Anlage am Ufer und bekam eine Lizenz. Fast nichts verlässt das Land: Die Australier trinken ihren Rum selbst.",
 "sl": "Najstarejša registrirana destilarna v Avstraliji, v Queenslandu, kjer trs raste bolje kot na Karibih. Prvi kotel so, kot pripoveduje hiša, sneli s parnika, ki je rum žgal ilegalno, medtem ko je plul po reki — ko so ga ujeli, je oprema pristala na bregu in dobila dovoljenje. Iz države ne pride skoraj nič: Avstralci svoj rum popijejo sami.",
 "es": "La destilería registrada más antigua de Australia, en Queensland, donde la caña crece mejor que en el Caribe. El primer alambique, según cuenta la casa, se sacó de un vapor de ruedas que destilaba ron ilegalmente mientras bajaba el río — cuando lo pillaron, el equipo acabó en la orilla y recibió una licencia. Casi nada sale del país: los australianos se beben su ron ellos mismos.",
 "zh": "澳大利亚最古老的注册酒厂，位于昆士兰——甘蔗在那里长得比加勒比还好。按酒厂自己的说法，第一台蒸馏器是从一艘明轮船上拆下来的：那船一边顺河而下、一边非法酿朗姆；被抓之后，设备落到岸上，反倒拿到了执照。这里的酒几乎不出国门：澳大利亚人自己就把它喝光了。"
}

NEW["Appenzeller Alpenbitter"] = {
 "hr": "42 planinske biljke po recepturi iz 1902. koju obitelj drži u glavi, a ne na papiru — kažu da je u svakom trenutku znaju samo dvojica. Bere se po alpskim livadama oko Appenzella, gdje su te livade toliko strme da se kosi ručno. Gorko koje se pije poslije jela jer stvarno pomaže, a ne zato što tako piše na boci.",
 "en": "42 mountain botanicals to a recipe from 1902 that the family keeps in its head rather than on paper — they say only two people know it at any one time. They are gathered on the alpine meadows around Appenzell, where the slopes are steep enough that the mowing is still done by hand. A bitter you drink after a meal because it genuinely helps, not because the label says so.",
 "it": "42 erbe di montagna secondo una ricetta del 1902 che la famiglia tiene in testa e non su carta — dicono che in ogni momento la conoscano solo in due. Si raccolgono sui prati alpini attorno ad Appenzell, dove i pendii sono tanto ripidi che si falcia ancora a mano. Un amaro che si beve a fine pasto perché aiuta davvero, non perché lo dice l'etichetta.",
 "fr": "42 plantes de montagne selon une recette de 1902 que la famille garde en tête et non sur le papier — ils disent qu'à tout moment deux personnes seulement la connaissent. On les cueille sur les prairies alpines autour d'Appenzell, où les pentes sont assez raides pour qu'on fauche encore à la main. Un amer qu'on boit après le repas parce qu'il aide vraiment, pas parce que l'étiquette le dit.",
 "de": "42 Bergkräuter nach einem Rezept von 1902, das die Familie im Kopf behält und nicht auf Papier — es heißt, es kennen immer nur zwei Personen. Gesammelt wird auf den Alpwiesen um Appenzell, wo die Hänge so steil sind, dass noch von Hand gemäht wird. Ein Bitter, den man nach dem Essen trinkt, weil er wirklich hilft, nicht weil es auf dem Etikett steht.",
 "sl": "42 gorskih rastlin po recepturi iz leta 1902, ki jo družina hrani v glavi in ne na papirju — pravijo, da jo v vsakem trenutku poznata samo dva. Nabirajo jih po alpskih travnikih okoli Appenzella, kjer so pobočja tako strma, da se kosi še vedno ročno. Grenčica, ki se pije po jedi, ker res pomaga, ne zato, ker tako piše na steklenici.",
 "es": "42 hierbas de montaña según una receta de 1902 que la familia guarda en la cabeza y no en papel — dicen que en cada momento sólo la conocen dos personas. Se recogen en los prados alpinos alrededor de Appenzell, donde las laderas son tan empinadas que aún se siega a mano. Un amargo que se bebe después de comer porque de verdad ayuda, no porque lo diga la etiqueta.",
 "zh": "42 种山地草药，配方出自 1902 年，由家族记在脑子里而不是纸上——据说任何时候只有两个人知道全部。草药采自阿彭策尔周围的高山草甸，那里的坡陡到至今仍靠手工收割。这是一杯饭后喝的苦酒，因为它真的有用，而不是因为瓶身上这么写。"
}

NEW["Latvijas Balzams"] = {
 "hr": "Riga, pogon iz 1900. koji je preživio dva svjetska rata, jedno carstvo i jednu državu — i u kojem se Stolichnaya puni već preko 70 godina. Ista kuća radi i Rīgas Melnais balzams, crni baltički biljni liker koji je, kaže predaja, izliječio Katarinu Veliku kad se razboljela u Latviji. Votka odavde nema takvu legendu, ali ima istu adresu.",
 "en": "Riga, a plant from 1900 that has outlived two world wars, an empire and a state — and where Stolichnaya has been bottled for over 70 years. The same house makes Rīgas Melnais balzams, the black Baltic herbal liqueur which, so the story goes, cured Catherine the Great when she fell ill in Latvia. The vodka from here has no such legend, but it has the same address.",
 "it": "Riga, uno stabilimento del 1900 che è sopravvissuto a due guerre mondiali, a un impero e a uno Stato — e dove la Stolichnaya si imbottiglia da oltre 70 anni. La stessa casa fa il Rīgas Melnais balzams, il liquore alle erbe nero del Baltico che, così vuole la leggenda, guarì Caterina la Grande quando si ammalò in Lettonia. La vodka di qui non ha una leggenda simile, ma ha lo stesso indirizzo.",
 "fr": "Riga, une usine de 1900 qui a survécu à deux guerres mondiales, à un empire et à un État — et où la Stolichnaya est embouteillée depuis plus de 70 ans. La même maison fait le Rīgas Melnais balzams, la liqueur d'herbes noire de la Baltique qui, dit la légende, guérit Catherine la Grande tombée malade en Lettonie. La vodka d'ici n'a pas de légende pareille, mais elle a la même adresse.",
 "de": "Riga, ein Werk von 1900, das zwei Weltkriege, ein Kaiserreich und einen Staat überstanden hat — und in dem seit über 70 Jahren Stolichnaya abgefüllt wird. Dasselbe Haus macht den Rīgas Melnais balzams, den schwarzen baltischen Kräuterlikör, der, so die Überlieferung, Katharina die Große heilte, als sie in Lettland erkrankte. Der Wodka von hier hat keine solche Legende, aber dieselbe Adresse.",
 "sl": "Riga, obrat iz leta 1900, ki je preživel dve svetovni vojni, en imperij in eno državo — in v katerem Stolichnayo polnijo že več kot 70 let. Ista hiša dela tudi Rīgas Melnais balzams, črni baltski zeliščni liker, ki je, pravi izročilo, ozdravil Katarino Veliko, ko je zbolela v Latviji. Vodka od tod nima takšne legende, ima pa isti naslov.",
 "es": "Riga, una planta de 1900 que ha sobrevivido a dos guerras mundiales, a un imperio y a un Estado — y donde el Stolichnaya se embotella desde hace más de 70 años. La misma casa hace el Rīgas Melnais balzams, el licor de hierbas negro del Báltico que, según cuenta la leyenda, curó a Catalina la Grande cuando enfermó en Letonia. El vodka de aquí no tiene esa leyenda, pero tiene la misma dirección.",
 "zh": "里加，一座建于 1900 年的酒厂，熬过了两次世界大战、一个帝国和一个国家——而 Stolichnaya 在这里已经装瓶超过 70 年。同一家还做「里加黑药酒」（Rīgas Melnais balzams），那款波罗的海的黑色草本利口酒；传说叶卡捷琳娜大帝在拉脱维亚病倒时，正是它治好了她。这里的伏特加没有这样的传说，却有同一个地址。"
}

NEW["Renegade"] = {
 "hr": "Mark Reynier je prije ovoga oživio Bruichladdich, pa Waterford, i oba je puta tvrdio isto: važno je odakle je sirovina. Prije svega toga bio je trgovac vinom — otud i cijela ideja. Na Grenadi je zato zasadio trsku po parcelama, svaku bere i destilira odvojeno i na etiketu stavlja polje umjesto kupaže. Rum kao vino s položaja, po prvi put.",
 "en": "Before this, Mark Reynier revived Bruichladdich, then Waterford, and both times argued the same thing: what matters is where the raw material comes from. Before all of it he was a wine merchant — which is where the whole idea comes from. So on Grenada he planted cane parcel by parcel, harvests and distils each one separately, and puts the field on the label instead of a blend. Rum as a wine of place, for the first time.",
 "it": "Prima di questo Mark Reynier ha fatto rinascere Bruichladdich, poi Waterford, e ogni volta ha sostenuto la stessa cosa: conta da dove viene la materia prima. Prima ancora era un mercante di vino — ed è da lì che nasce tutta l'idea. A Grenada ha quindi piantato la canna per parcelle, ne raccoglie e distilla ognuna a parte e in etichetta mette il campo invece del blend. Rum come vino di luogo, per la prima volta.",
 "fr": "Avant cela, Mark Reynier a ressuscité Bruichladdich, puis Waterford, et chaque fois soutenu la même chose : ce qui compte, c'est d'où vient la matière première. Avant tout cela, il était marchand de vin — d'où vient toute l'idée. À la Grenade, il a donc planté la canne par parcelles, récolte et distille chacune à part, et met la parcelle sur l'étiquette au lieu d'un assemblage. Du rhum comme un vin de lieu, pour la première fois.",
 "de": "Davor hat Mark Reynier Bruichladdich wiederbelebt, dann Waterford, und beide Male dasselbe behauptet: Es zählt, woher der Rohstoff kommt. Davor war er Weinhändler — daher die ganze Idee. Auf Grenada pflanzte er das Zuckerrohr also parzellenweise, erntet und brennt jede für sich und setzt das Feld aufs Etikett statt eines Verschnitts. Rum als Lagenwein, zum ersten Mal.",
 "sl": "Pred tem je Mark Reynier oživil Bruichladdich, nato Waterford, in obakrat trdil isto: pomembno je, od kod je surovina. Pred vsem tem je bil trgovec z vinom — od tod tudi vsa zamisel. Na Grenadi je zato trs zasadil po parcelah, vsako posebej žanje in destilira, na etiketo pa namesto zvrsti postavi njivo. Rum kot vino z lege, prvič.",
 "es": "Antes de esto, Mark Reynier resucitó Bruichladdich y luego Waterford, y las dos veces sostuvo lo mismo: importa de dónde viene la materia prima. Antes de todo eso era comerciante de vinos — de ahí sale toda la idea. En Granada plantó por tanto la caña por parcelas, cosecha y destila cada una aparte y pone el campo en la etiqueta en lugar de una mezcla. Ron como vino de pago, por primera vez.",
 "zh": "在这之前，马克·雷尼耶先后让布赫拉迪与沃特福德复活，两次都在讲同一件事：原料从哪里来，才是关键。而在这一切之前，他是个葡萄酒商——整个念头正是从那里来的。所以在格林纳达，他按地块种甘蔗，逐块采收、逐块蒸馏，酒标上写的是田块而不是调和。这是头一回，朗姆像一款有产地的葡萄酒。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-26s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
