# -*- coding: utf-8 -*-
"""French batch three, plus three fixes the owner caught (2026-08-12).

The l'Écu one matters most: the blurb sold a Muscadet called Granite and we
pour neither. Our bottle is Matris, a **Chenin**. That is exactly the failure
the per-estate rule exists to prevent — a guest reading about a wine we do not
have — and it had been in the text since the card was written.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

# ---- fixes to cards already live -------------------------------------------

NEW["Jacques Selosse"] = {
 "hr": "Trebalo mu je 6 godina prepirke sa šampanjskim odborom da smije raditi ono što je vidio u Jerezu: soleru — bačve u koje se svake godine mlado dolijeva u staro, pa vino nikad ne kreće ispočetka. Dopustili su mu je 1986. Istu stvar, vino kojem se daje vrijeme, vidio je i kod Lópeza de Heredije u Rioji, koji je i sam na ovoj karti: ondje desetljećima leži u starom drvu. U Champagni se tada mjerila samo svježina. Anselme Selosse učio je u Burgundiji, kod ljudi koji su vjerovali da vino nastaje u vinogradu — pa mu ni jedno ni drugo nije bilo strano.",
 "en": "It took him 6 years of argument with Champagne's governing body to be allowed what he had seen in Jerez: a solera — casks into which the young wine is topped up into the old every year, so the wine never starts from scratch. They let him have it in 1986. He had seen the same thing, wine given time, at López de Heredia in Rioja, who are themselves on this list: there it lies for decades in old wood. In Champagne the only measure then was freshness. Anselme Selosse had trained in Burgundy, among people who believed wine is made in the vineyard — so neither idea was strange to him.",
 "it": "Gli sono serviti 6 anni di discussioni con l'ente della Champagne per poter fare ciò che aveva visto a Jerez: una solera — botti in cui ogni anno il vino giovane si rabbocca nel vecchio, così il vino non riparte mai da zero. Gliel'hanno concessa nel 1986. La stessa cosa, il vino cui si dà tempo, l'aveva vista da López de Heredia in Rioja, anch'essi su questa carta: lì resta decenni in legno vecchio. In Champagne allora si misurava solo la freschezza. Anselme Selosse si era formato in Borgogna, fra gente convinta che il vino si faccia in vigna — nessuna delle due idee gli era dunque estranea.",
 "fr": "Il lui a fallu 6 ans de discussions avec l'organisme de la Champagne pour pouvoir faire ce qu'il avait vu à Jerez : une solera — des fûts où le vin jeune vient chaque année compléter le vieux, si bien que le vin ne repart jamais de zéro. On la lui a accordée en 1986. La même chose, du vin à qui l'on donne du temps, il l'avait vue chez López de Heredia en Rioja, eux aussi sur cette carte : là-bas il repose des décennies dans du vieux bois. En Champagne, on ne mesurait alors que la fraîcheur. Anselme Selosse s'était formé en Bourgogne, chez des gens convaincus que le vin se fait à la vigne — aucune des deux idées ne lui était donc étrangère.",
 "de": "Er brauchte 6 Jahre Streit mit dem Champagne-Verband, um machen zu dürfen, was er in Jerez gesehen hatte: eine Solera — Fässer, in denen der junge Wein Jahr für Jahr in den alten nachgefüllt wird, sodass der Wein nie von vorn beginnt. 1986 wurde sie ihm erlaubt. Dasselbe, Wein, dem man Zeit gibt, hatte er bei López de Heredia in der Rioja gesehen, die selbst auf dieser Karte stehen: dort liegt er jahrzehntelang in altem Holz. In der Champagne zählte damals nur Frische. Anselme Selosse hatte im Burgund gelernt, bei Leuten, die glaubten, Wein entstehe im Weinberg — keiner der beiden Gedanken war ihm also fremd.",
 "sl": "Potreboval je 6 let prerekanja s šampanjskim odborom, da je smel delati to, kar je videl v Jerezu: solero — sode, v katere se mlado vino vsako leto dolije v staro, tako da vino nikoli ne začne od začetka. Dovolili so mu jo leta 1986. Isto stvar, vino, ki mu je dan čas, je videl tudi pri Lópezu de Herediji v Rioji, ki je prav tako na tej karti: tam desetletja leži v starem lesu. V Champagni se je takrat merila le svežina. Anselme Selosse se je učil v Burgundiji, pri ljudeh, ki so verjeli, da vino nastane v vinogradu — zato mu ni bilo tuje ne eno ne drugo.",
 "es": "Le hicieron falta 6 años de discusión con el organismo de Champaña para poder hacer lo que había visto en Jerez: una solera — barricas en las que cada año el vino joven se rellena sobre el viejo, de modo que el vino nunca empieza de cero. Se la permitieron en 1986. Lo mismo, vino al que se le da tiempo, lo había visto en López de Heredia en Rioja, que están también en esta carta: allí reposa décadas en madera vieja. En Champaña entonces sólo se medía la frescura. Anselme Selosse se había formado en Borgoña, entre gente que creía que el vino se hace en la viña — así que ninguna de las dos ideas le era ajena.",
 "zh": "他和香槟产区管理机构争了 6 年，才被允许做他在赫雷斯看到的事：索莱拉——每年把新酒续进老酒的那一组桶，酒因此从不从头开始。1986 年获准。同一件事，也就是「给酒时间」，他在里奥哈的 López de Heredia 也见过——那家同样在这份酒单上：酒在那里的老木桶中一躺几十年。而当时的香槟区，只衡量新鲜。安塞尔姆·瑟洛斯在勃艮第学艺，身边人都相信酒是在葡萄园里做成的——所以这两件事对他都不陌生。"
}

NEW["l'Écu"] = {
 "hr": "Ekološki certifikat imaju od 1972., kad je ostatak Francuske još prskao sve što se prskati dalo. Guy Bossard, koji je to pokrenuo, bio je jedan od prvih biodinamičara u zemlji; 2011. imanje je preuzeo Fred Niger i danas u biodinamici drži 17 hektara. Vina nose imena kamena ispod loze — gnajs, granit, ortognajs — jer se ondje jedno od drugog razlikuju upravo po tome. Uz melon i chenin, sve vrije na vlastitim kvascima, bez ičega dodanog.",
 "en": "They have been certified organic since 1972, when the rest of France was still spraying anything that could be sprayed. Guy Bossard, who started it, was one of the country's first biodynamic growers; Fred Niger took the estate on in 2011 and farms its 17 hectares biodynamically today. The wines are named after the rock beneath the vines — gneiss, granite, orthogneiss — because that is what tells them apart. Melon and Chenin alike ferment on their own yeasts, with nothing added.",
 "it": "Sono certificati biologici dal 1972, quando il resto della Francia irrorava ancora tutto ciò che si poteva irrorare. Guy Bossard, che avviò la cosa, fu uno dei primi biodinamici del paese; nel 2011 la tenuta è passata a Fred Niger, che ne conduce oggi 17 ettari in biodinamica. I vini portano il nome della roccia sotto la vigna — gneiss, granito, ortogneiss — perché è quello a distinguerli l'uno dall'altro. Melon e chenin fermentano entrambi con i propri lieviti, senza nulla di aggiunto.",
 "fr": "Ils sont certifiés bio depuis 1972, quand le reste de la France traitait encore tout ce qui pouvait l'être. Guy Bossard, qui a lancé cela, fut l'un des premiers biodynamistes du pays ; Fred Niger a repris le domaine en 2011 et en mène aujourd'hui 17 hectares en biodynamie. Les vins portent le nom de la roche sous la vigne — gneiss, granite, orthogneiss — parce que c'est cela qui les distingue les uns des autres. Melon comme chenin fermentent sur leurs propres levures, sans rien d'ajouté.",
 "de": "Bio-zertifiziert sind sie seit 1972, als der Rest Frankreichs noch alles spritzte, was sich spritzen ließ. Guy Bossard, der damit anfing, war einer der ersten Biodynamiker des Landes; 2011 übernahm Fred Niger das Gut und bewirtschaftet heute 17 Hektar biodynamisch. Die Weine tragen den Namen des Gesteins unter den Reben — Gneis, Granit, Orthogneis — weil genau das sie voneinander unterscheidet. Melon wie Chenin vergären auf eigenen Hefen, ohne Zusatz.",
 "sl": "Ekološki certifikat imajo od leta 1972, ko je preostala Francija še škropila vse, kar se je dalo poškropiti. Guy Bossard, ki je to začel, je bil med prvimi biodinamiki v državi; leta 2011 je posestvo prevzel Fred Niger in danes biodinamično obdeluje 17 hektarov. Vina nosijo imena kamnine pod trtami — gnajs, granit, ortognajs — ker se prav po tem razlikujejo med seboj. Melon in chenin vreta na lastnih kvasovkah, brez dodatkov.",
 "es": "Están certificados en ecológico desde 1972, cuando el resto de Francia aún fumigaba todo lo que se podía fumigar. Guy Bossard, que lo puso en marcha, fue uno de los primeros biodinámicos del país; en 2011 Fred Niger tomó la finca y hoy lleva sus 17 hectáreas en biodinámica. Los vinos llevan el nombre de la roca bajo la viña — gneis, granito, ortogneis — porque es eso lo que los distingue entre sí. Melon y Chenin fermentan con sus propias levaduras, sin nada añadido.",
 "zh": "他们自 1972 年起就持有有机认证，那时法国其余地方还在喷洒一切能喷的东西。开启这一切的居伊·博萨尔，是法国最早的生物动力农之一；2011 年弗雷德·尼热接手，如今以生物动力耕作 17 公顷。酒以藤下的岩石命名——片麻岩、花岗岩、正片麻岩——因为它们彼此的分别正在于此。无论是勃艮第香瓜还是白诗南，都用自身酵母发酵，什么也不加。"
}

# ---- batch three ------------------------------------------------------------

NEW["Billecart-Salmon"] = {
 "hr": "Ovdje se vinu oduzima žurba: fermentacija je hladna i vrlo spora, postupak koji vino usporava umjesto da ga tjera — i to se osjeti na sva tri njihova vina na ovoj karti. Rosé koji tako nastaje mnogi drže najljepšim u Champagni. Kuću su spojili Nicolas François Billecart i Elisabeth Salmon, pa su oba prezimena ostala na etiketi; obitelj je drži i danas, sedmi naraštaj.",
 "en": "Here the wine is denied its hurry: the fermentation is cold and very slow, a process that holds the wine back instead of driving it — and it shows in all three of their wines on this list. The rosé it produces is held by many to be the finest in Champagne. The house was joined by Nicolas François Billecart and Elisabeth Salmon, so both surnames stayed on the label; the family holds it still, seventh generation.",
 "it": "Qui al vino si toglie la fretta: la fermentazione è fredda e lentissima, un procedimento che trattiene il vino invece di spingerlo — e si sente in tutti e tre i loro vini su questa carta. Il rosé che ne nasce è ritenuto da molti il più bello della Champagne. La maison l'hanno unita Nicolas François Billecart ed Elisabeth Salmon, e in etichetta sono rimasti entrambi i cognomi; la famiglia la tiene ancora, settima generazione.",
 "fr": "Ici, on retire au vin sa hâte : la fermentation est froide et très lente, un procédé qui retient le vin au lieu de le pousser — et cela s'entend sur les trois vins qui figurent ici. Le rosé qui en naît est tenu par beaucoup pour le plus beau de Champagne. La maison est née de l'union de Nicolas François Billecart et d'Elisabeth Salmon, et les deux noms sont restés sur l'étiquette ; la famille la tient toujours, septième génération.",
 "de": "Hier nimmt man dem Wein die Eile: Die Gärung ist kalt und sehr langsam, ein Verfahren, das den Wein zurückhält, statt ihn zu treiben — und das schmeckt man bei allen drei Weinen auf dieser Karte. Der Rosé, der so entsteht, gilt vielen als der schönste der Champagne. Das Haus verbanden Nicolas François Billecart und Elisabeth Salmon, weshalb beide Namen auf dem Etikett blieben; die Familie hält es bis heute, in siebter Generation.",
 "sl": "Tu vinu vzamejo naglico: fermentacija je hladna in zelo počasna, postopek, ki vino zadržuje, namesto da bi ga priganjal — in to se pozna pri vseh treh njihovih vinih na tej karti. Rosé, ki tako nastane, ima marsikdo za najlepšega v Champagni. Hišo sta združila Nicolas François Billecart in Elisabeth Salmon, zato sta na etiketi ostala oba priimka; družina jo drži še danes, sedmi rod.",
 "es": "Aquí al vino se le quita la prisa: la fermentación es fría y muy lenta, un proceso que retiene el vino en vez de empujarlo — y se nota en los tres vinos suyos que hay en esta carta. El rosado que nace así lo tienen muchos por el más hermoso de Champaña. La casa la unieron Nicolas François Billecart y Elisabeth Salmon, y ambos apellidos quedaron en la etiqueta; la familia la conserva aún, séptima generación.",
 "zh": "在这里，酒是不许着急的：发酵低温而极慢，这道工序拉住酒，而不是催它——酒单上他们的三款酒都能尝出来。由此而来的桃红，被许多人视为香槟区最美的一款。这家酒庄由尼古拉·弗朗索瓦·比勒卡与伊丽莎白·萨蒙结合而成，两个姓氏都留在了酒标上；至今仍由家族持有，已是第七代。"
}

NEW["Pertois-Moriset"] = {
 "hr": "13,5 hektara grand cru chardonnaya u Le Mesnil-sur-Ogeru, Ogeru, Cramantu i Chouillyju — četiri sela koja mnogi drže najboljom kredom u Champagni. Do njih se došlo vjenčanjem: Yves Pertois i Janine Moriset, oboje djeca vinogradarskih obitelji s Côte des Blancs, spojili su 1951. prezimena u brand. Danas kuću vode njihova unuka Cécile i njezin muž Vincent.",
 "en": "13.5 hectares of grand cru Chardonnay in Le Mesnil-sur-Oger, Oger, Cramant and Chouilly — four villages many hold to be the best chalk in Champagne. They came by marriage: Yves Pertois and Janine Moriset, both children of growing families on the Côte des Blancs, joined their surnames into a brand in 1951. Their granddaughter Cécile and her husband Vincent run the house today.",
 "it": "13,5 ettari di chardonnay grand cru a Le Mesnil-sur-Oger, Oger, Cramant e Chouilly — quattro paesi che molti considerano la migliore creta della Champagne. Ci si è arrivati per matrimonio: Yves Pertois e Janine Moriset, entrambi figli di famiglie di vignaioli della Côte des Blancs, nel 1951 unirono i cognomi in un marchio. Oggi la casa è nelle mani della nipote Cécile e del marito Vincent.",
 "fr": "13,5 hectares de chardonnay grand cru au Mesnil-sur-Oger, à Oger, Cramant et Chouilly — quatre villages que beaucoup tiennent pour la meilleure craie de Champagne. Ils sont venus par un mariage : Yves Pertois et Janine Moriset, tous deux enfants de familles de vignerons de la Côte des Blancs, ont réuni leurs noms en une marque en 1951. Leur petite-fille Cécile et son mari Vincent mènent la maison aujourd'hui.",
 "de": "13,5 Hektar Grand-Cru-Chardonnay in Le Mesnil-sur-Oger, Oger, Cramant und Chouilly — vier Dörfer, die viele für die beste Kreide der Champagne halten. Dazu kam man durch eine Heirat: Yves Pertois und Janine Moriset, beide Kinder von Winzerfamilien der Côte des Blancs, machten 1951 aus ihren Namen eine Marke. Heute führen die Enkelin Cécile und ihr Mann Vincent das Haus.",
 "sl": "13,5 hektara grand cru chardonnaya v Le Mesnil-sur-Ogeru, Ogeru, Cramantu in Chouillyju — štirih vaseh, ki jih mnogi imajo za najboljšo kredo v Champagni. Prišli so do njih s poroko: Yves Pertois in Janine Moriset, oba otroka vinogradniških družin s Côte des Blancs, sta leta 1951 priimka združila v znamko. Danes hišo vodita njuna vnukinja Cécile in njen mož Vincent.",
 "es": "13,5 hectáreas de Chardonnay grand cru en Le Mesnil-sur-Oger, Oger, Cramant y Chouilly — cuatro pueblos que muchos tienen por la mejor creta de Champaña. Llegaron por un matrimonio: Yves Pertois y Janine Moriset, ambos hijos de familias viticultoras de la Côte des Blancs, unieron sus apellidos en una marca en 1951. Hoy llevan la casa su nieta Cécile y su marido Vincent.",
 "zh": "13,5 公顷特级园霞多丽，分布在 Le Mesnil-sur-Oger、Oger、Cramant 与 Chouilly——许多人认为这四个村子拥有香槟区最好的白垩土。这些园子是靠一桩婚姻来的：伊夫·佩尔图瓦与雅尼娜·莫里塞，两位都出身白丘的种植世家，1951 年把两个姓氏合成了一个牌子。如今由孙女塞西尔和丈夫樊尚打理。"
}

NEW["Bernard-Bonin"] = {
 "hr": "Djed je radio Meursault kakav se tada tražio: bogat, pun, s dosta drva. Unuka radi suprotno — više napet nego debeo — i to na 7 hektara koje je morala izmoliti. Kad je 1998. Bernard Michelot imanje dijelio među 3 kćeri, Véronique je nagovorila majku da taj dio prepusti njoj i suprugu Nicolasu. Iz podijeljenog nasljedstva izašla je jedna od najtraženijih adresa u selu.",
 "en": "The grandfather made the Meursault of his day: rich, full, with plenty of oak. The granddaughter makes the opposite — more tense than fat — and does it on 7 hectares she had to ask for. When Bernard Michelot divided the estate among his 3 daughters in 1998, Véronique talked her mother into leaving that share to her and her husband Nicolas. Out of a split inheritance came one of the most sought-after addresses in the village.",
 "it": "Il nonno faceva il Meursault che allora si cercava: ricco, pieno, con parecchio legno. La nipote fa l'opposto — più teso che grasso — e lo fa su 7 ettari che ha dovuto chiedere. Quando nel 1998 Bernard Michelot divise la tenuta fra le 3 figlie, Véronique convinse la madre a lasciare quella parte a lei e al marito Nicolas. Da un'eredità spezzata è uscito uno degli indirizzi più ricercati del paese.",
 "fr": "Le grand-père faisait le meursault qu'on demandait alors : riche, plein, bien boisé. La petite-fille fait l'inverse — plus tendu que gras — et le fait sur 7 hectares qu'elle a dû demander. Quand Bernard Michelot a partagé le domaine entre ses 3 filles en 1998, Véronique a convaincu sa mère de leur laisser cette part, à elle et à son mari Nicolas. D'un héritage divisé est sortie l'une des adresses les plus recherchées du village.",
 "de": "Der Großvater machte den Meursault, den man damals wollte: reich, füllig, mit viel Holz. Die Enkelin macht das Gegenteil — eher gespannt als fett — und zwar auf 7 Hektar, um die sie bitten musste. Als Bernard Michelot das Gut 1998 unter seine 3 Töchter aufteilte, überredete Véronique ihre Mutter, diesen Teil ihr und ihrem Mann Nicolas zu überlassen. Aus einem geteilten Erbe wurde eine der begehrtesten Adressen des Dorfes.",
 "sl": "Ded je delal meursault, kakršen se je takrat iskal: bogat, poln, z veliko lesa. Vnukinja dela nasprotno — bolj napeto kot debelo — in to na 7 hektarih, ki jih je morala izprositi. Ko je Bernard Michelot leta 1998 posestvo delil med 3 hčere, je Véronique pregovorila mater, naj ta del prepusti njej in možu Nicolasu. Iz razdeljene dediščine je nastal eden najbolj iskanih naslovov v vasi.",
 "es": "El abuelo hacía el Meursault que entonces se buscaba: rico, lleno, con bastante madera. La nieta hace lo contrario — más tenso que graso — y lo hace en 7 hectáreas que tuvo que pedir. Cuando en 1998 Bernard Michelot repartió la finca entre sus 3 hijas, Véronique convenció a su madre de dejarles esa parte a ella y a su marido Nicolas. De una herencia partida salió una de las direcciones más buscadas del pueblo.",
 "zh": "外祖父做的是当年人们想要的默尔索：丰腴、饱满、木桶味十足。外孙女做的恰恰相反——紧绷多过肥厚——而且是在她开口求来的 7 公顷上做的。1998 年贝尔纳·米什洛把酒庄分给 3 个女儿时，韦罗妮克说动母亲把那一份留给她和丈夫尼古拉。一份被分割的遗产，最后成了村里最抢手的地址之一。"
}

NEW["Raveneau"] = {
 "hr": "Dva najtraženija imena Chablisa su rodbina: François Raveneau oženio je Andrée Dauvissat, sestru Renéa Dauvissata, pa su njezini vinogradi došli k njegovima — a Dauvissati su na ovoj karti nekoliko redaka dalje. Zajedno su u Chablis donijeli način rada s Côte d'Ora: vrenje u bačvi i dugo ležanje na talogu. Šezdesetih i sedamdesetih François je kupovao grand cru parcele dok ih još nitko nije htio.",
 "en": "Chablis's two most sought-after names are in-laws: François Raveneau married Andrée Dauvissat, sister of René Dauvissat, and her vineyards came to join his — and the Dauvissats are a few lines further along this list. Together they brought the Côte d'Or's way of working to Chablis: fermentation in barrel and long ageing on the lees. Through the 1960s and 70s François bought grand cru parcels while nobody else wanted them.",
 "it": "I due nomi più ricercati di Chablis sono parenti: François Raveneau sposò Andrée Dauvissat, sorella di René Dauvissat, e le vigne di lei andarono ad aggiungersi alle sue — e i Dauvissat stanno qualche riga più in là su questa carta. Insieme portarono a Chablis il modo di lavorare della Côte d'Or: fermentazione in botte e lunga sosta sui lieviti. Negli anni Sessanta e Settanta François comprava parcelle grand cru quando ancora non le voleva nessuno.",
 "fr": "Les deux noms les plus recherchés de Chablis sont alliés : François Raveneau a épousé Andrée Dauvissat, sœur de René Dauvissat, et les vignes de celle-ci sont venues rejoindre les siennes — les Dauvissat se trouvent quelques lignes plus loin sur cette carte. Ensemble ils ont apporté à Chablis la façon de faire de la Côte d'Or : fermentation en fût et long élevage sur lies. Dans les années 1960 et 70, François achetait des parcelles de grand cru quand personne n'en voulait encore.",
 "de": "Die zwei begehrtesten Namen von Chablis sind verschwägert: François Raveneau heiratete Andrée Dauvissat, die Schwester von René Dauvissat, und ihre Weinberge kamen zu seinen — die Dauvissats stehen ein paar Zeilen weiter auf dieser Karte. Gemeinsam brachten sie die Arbeitsweise der Côte d'Or nach Chablis: Gärung im Fass und langes Hefelager. In den 1960er- und 70er-Jahren kaufte François Grand-Cru-Parzellen, als sie noch niemand wollte.",
 "sl": "Dve najbolj iskani imeni Chablisa sta v sorodstvu: François Raveneau se je poročil z Andrée Dauvissat, sestro Renéja Dauvissata, in njeni vinogradi so se pridružili njegovim — Dauvissati pa so na tej karti nekaj vrstic naprej. Skupaj sta v Chablis prinesla način dela s Côte d'Ora: vrenje v sodu in dolgo ležanje na drožeh. V šestdesetih in sedemdesetih je François kupoval grand cru parcele, ko jih še nihče ni hotel.",
 "es": "Los dos nombres más buscados de Chablis son parientes: François Raveneau se casó con Andrée Dauvissat, hermana de René Dauvissat, y las viñas de ella se sumaron a las suyas — y los Dauvissat están unas líneas más allá en esta carta. Juntos trajeron a Chablis la manera de trabajar de la Côte d'Or: fermentación en barrica y larga crianza sobre lías. En los años sesenta y setenta François compraba parcelas de grand cru cuando aún no las quería nadie.",
 "zh": "夏布利最抢手的两个名字是姻亲：弗朗索瓦·拉沃诺娶了勒内·多维萨的妹妹安德蕾·多维萨，她的葡萄园于是并入他的——而多维萨家就在这份酒单往下几行。两家一起把金丘的做法带进夏布利：桶中发酵，长时间带泥陈酿。六七十年代，弗朗索瓦在还没人要的时候，一块块买下了特级园。"
}

NEW["Pascal Cotat"] = {
 "hr": "Nagib je takav da se u njemu ne radi stojeći: berači se spuštaju sjedeći, privezani za jastuk. To je Monts Damnés iznad Chavignola, gdje Cotati rade od kraja Drugoga svjetskog rata. Devedesetih su braća Paul i Francis predala imanje sinovima — François jedno, Pascal drugo — pa danas dva bratića prave vrlo slično vino s istoga brda. Pascal bere ručno i vrlo kasno, i otud težina koju Sancerre inače nema.",
 "en": "The slope is such that you cannot work it standing up: the pickers go down sitting, strapped to a cushion. This is Monts Damnés above Chavignol, where the Cotats have worked since the end of the Second World War. In the 1990s the brothers Paul and Francis handed the estate to their sons — one to François, the other to Pascal — so today two cousins make very similar wine off the same hill. Pascal picks by hand and very late, and that is where the weight comes from, which Sancerre otherwise does not have.",
 "it": "La pendenza è tale che non ci si lavora in piedi: i vendemmiatori scendono seduti, legati a un cuscino. Sono i Monts Damnés sopra Chavignol, dove i Cotat lavorano dalla fine della Seconda guerra mondiale. Negli anni Novanta i fratelli Paul e Francis passarono la tenuta ai figli — una a François, l'altra a Pascal — così oggi due cugini fanno un vino molto simile dalla stessa collina. Pascal vendemmia a mano e molto tardi, e di lì viene quel peso che il Sancerre di solito non ha.",
 "fr": "La pente est telle qu'on n'y travaille pas debout : les vendangeurs descendent assis, sanglés à un coussin. Ce sont les Monts Damnés au-dessus de Chavignol, où les Cotat travaillent depuis la fin de la Seconde Guerre mondiale. Dans les années 1990, les frères Paul et Francis ont passé le domaine à leurs fils — l'un à François, l'autre à Pascal — si bien qu'aujourd'hui deux cousins font un vin très proche sur la même colline. Pascal vendange à la main et très tard, et de là vient ce poids que le sancerre n'a d'ordinaire pas.",
 "de": "Der Hang ist so steil, dass man darin nicht stehend arbeitet: Die Leser lassen sich sitzend hinab, an ein Kissen geschnallt. Das ist Monts Damnés über Chavignol, wo die Cotats seit dem Ende des Zweiten Weltkriegs arbeiten. In den 1990ern gaben die Brüder Paul und Francis das Gut an ihre Söhne weiter — das eine an François, das andere an Pascal — sodass heute zwei Cousins sehr ähnlichen Wein vom selben Hügel machen. Pascal liest von Hand und sehr spät, und daher kommt jenes Gewicht, das Sancerre sonst nicht hat.",
 "sl": "Strmina je taka, da se v njej ne dela stoje: trgači se spuščajo sede, privezani na blazino. To so Monts Damnés nad Chavignolom, kjer Cotati delajo od konca druge svetovne vojne. V devetdesetih sta brata Paul in Francis posestvo predala sinovoma — eno Françoisu, drugo Pascalu — zato danes dva bratranca delata zelo podobno vino z istega hriba. Pascal trga ročno in zelo pozno, od tod pa teža, kakršne Sancerre sicer nima.",
 "es": "La pendiente es tal que no se trabaja de pie: los vendimiadores bajan sentados, atados a un cojín. Son los Monts Damnés sobre Chavignol, donde los Cotat trabajan desde el final de la Segunda Guerra Mundial. En los años noventa los hermanos Paul y Francis pasaron la finca a sus hijos — una a François, la otra a Pascal — así que hoy dos primos hacen un vino muy parecido en la misma colina. Pascal vendimia a mano y muy tarde, y de ahí viene ese peso que el Sancerre normalmente no tiene.",
 "zh": "坡陡到无法站着干活：采收的人是坐着往下挪的，身上绑着一只垫子。这里是沙维尼奥尔之上的 Monts Damnés，科塔家自二战结束起就在此耕作。九十年代，保罗与弗朗西斯兄弟把庄园交给儿子——一份给弗朗索瓦，一份给帕斯卡尔——所以今天是两位堂兄弟在同一面坡上做着极为相似的酒。帕斯卡尔手工采收，而且极晚，桑塞尔通常没有的那份重量就是这么来的。"
}

NEW["Albert Mann"] = {
 "hr": "Dvadesetak hektara razbijeno je na više od 100 parcela u 7 grand cruova — u prosjeku dvadesetak ari po komadu, što znači da se svaka bere i vinificira zasebno. Biodinamiku su u Alsaceu počeli 1997., prije gotovo svih. Imanje u Wettolsheimu vode dva brata i dvije Marie: Maurice i Jacky Barthelmé sa suprugama Marie-Claire i Marie-Thérèse. Najčvršća vina dolaze s Hengsta, vapnenca i lapora.",
 "en": "Some twenty hectares are broken into more than 100 parcels across 7 grand crus — about twenty ares apiece, which means each one is picked and vinified on its own. They began biodynamics in Alsace in 1997, before almost anyone. The Wettolsheim estate is run by two brothers and two Maries: Maurice and Jacky Barthelmé with their wives Marie-Claire and Marie-Thérèse. The firmest wines come off Hengst, limestone and marl.",
 "it": "Una ventina di ettari sono spezzati in più di 100 parcelle su 7 grand cru — una ventina di are l'una, il che vuol dire che ognuna si vendemmia e si vinifica a parte. La biodinamica in Alsazia l'hanno cominciata nel 1997, prima di quasi tutti. La tenuta di Wettolsheim è condotta da due fratelli e due Marie: Maurice e Jacky Barthelmé con le mogli Marie-Claire e Marie-Thérèse. I vini più saldi vengono dallo Hengst, calcare e marna.",
 "fr": "Une vingtaine d'hectares éclatés en plus de 100 parcelles sur 7 grands crus — une vingtaine d'ares chacune, ce qui veut dire que chacune est vendangée et vinifiée à part. Ils ont commencé la biodynamie en Alsace en 1997, avant presque tout le monde. Le domaine de Wettolsheim est mené par deux frères et deux Marie : Maurice et Jacky Barthelmé avec leurs femmes Marie-Claire et Marie-Thérèse. Les vins les plus fermes viennent du Hengst, calcaire et marne.",
 "de": "Rund zwanzig Hektar sind in mehr als 100 Parzellen über 7 Grands Crus zersplittert — im Schnitt zwanzig Ar je Stück, was heißt: jede wird für sich gelesen und ausgebaut. Mit Biodynamie begannen sie im Elsass 1997, vor fast allen. Das Gut in Wettolsheim führen zwei Brüder und zwei Maries: Maurice und Jacky Barthelmé mit ihren Frauen Marie-Claire und Marie-Thérèse. Die festesten Weine kommen vom Hengst, Kalk und Mergel.",
 "sl": "Kakšnih dvajset hektarov je razbitih na več kot 100 parcel v 7 grand crujih — v povprečju kakšnih dvajset arov na kos, kar pomeni, da se vsaka trga in vinificira posebej. Z biodinamiko so v Alzaciji začeli leta 1997, pred skoraj vsemi. Posestvo v Wettolsheimu vodita dva brata in dve Marie: Maurice in Jacky Barthelmé z ženama Marie-Claire in Marie-Thérèse. Najtrdnejša vina prihajajo s Hengsta, apnenca in laporja.",
 "es": "Una veintena de hectáreas está partida en más de 100 parcelas repartidas por 7 grand crus — unas veinte áreas cada una, lo que significa que cada una se vendimia y se vinifica aparte. Empezaron con la biodinámica en Alsacia en 1997, antes que casi nadie. La finca de Wettolsheim la llevan dos hermanos y dos Maries: Maurice y Jacky Barthelmé con sus mujeres Marie-Claire y Marie-Thérèse. Los vinos más firmes vienen del Hengst, caliza y marga.",
 "zh": "二十来公顷被拆成 100 多块园地，散落在 7 个特级园里——平均每块约二十公亩，也就是说每一块都单独采收、单独酿造。他们 1997 年就在阿尔萨斯开始生物动力，几乎早于所有人。韦托尔塞姆的这座酒庄由两兄弟和两位玛丽打理：莫里斯与雅基·巴泰尔梅，以及妻子玛丽-克莱尔和玛丽-泰蕾兹。最紧实的酒来自 Hengst，石灰岩与泥灰岩。"
}

NEW["Machard de Gramont"] = {
 "hr": "Nuits kakav je Nuits bio prije nego što je postao skup: čvrst, zemljan, bez ijedne suvišne geste. Bertrand Machard de Gramont počeo je iznova kad se obiteljsko imanje razdijelilo na tri dijela i njemu je pripala trećina — pa je dokupljivao ondje gdje si je mogao priuštiti, u Vosne-Romanéeu i u brdima iznad, u Curtil-Vergyju. Danas radi s kćeri Axelle.",
 "en": "Nuits as Nuits was before it got expensive: firm, earthy, without one superfluous gesture. Bertrand Machard de Gramont began again when the family estate was split three ways and a third fell to him — so he bought where he could afford to, in Vosne-Romanée and in the hills above, at Curtil-Vergy. He works with his daughter Axelle today.",
 "it": "Il Nuits com'era prima di diventare caro: saldo, terroso, senza un gesto di troppo. Bertrand Machard de Gramont ricominciò da capo quando la tenuta di famiglia fu divisa in tre e a lui toccò un terzo — così comprò dove poteva permetterselo, a Vosne-Romanée e sulle colline sopra, a Curtil-Vergy. Oggi lavora con la figlia Axelle.",
 "fr": "Le nuits tel qu'il était avant de devenir cher : ferme, terrien, sans un geste de trop. Bertrand Machard de Gramont a tout recommencé quand le domaine familial a été partagé en trois et qu'un tiers lui est revenu — il a donc acheté là où il le pouvait, à Vosne-Romanée et sur les hauteurs, à Curtil-Vergy. Il travaille aujourd'hui avec sa fille Axelle.",
 "de": "Nuits, wie Nuits war, bevor es teuer wurde: fest, erdig, ohne eine überflüssige Geste. Bertrand Machard de Gramont fing von vorn an, als das Familiengut in drei Teile zerfiel und ihm ein Drittel zufiel — also kaufte er dort, wo er es sich leisten konnte, in Vosne-Romanée und in den Hügeln darüber, in Curtil-Vergy. Heute arbeitet er mit seiner Tochter Axelle.",
 "sl": "Nuits, kakršen je bil, preden je postal drag: trden, zemeljski, brez ene same odvečne geste. Bertrand Machard de Gramont je začel znova, ko se je družinsko posestvo razdelilo na tri dele in mu je pripadla tretjina — zato je dokupoval tam, kjer si je lahko privoščil, v Vosne-Romanéeju in v hribih nad njim, v Curtil-Vergyju. Danes dela s hčerko Axelle.",
 "es": "El Nuits tal como era antes de ponerse caro: firme, terroso, sin un gesto de más. Bertrand Machard de Gramont volvió a empezar cuando la finca familiar se partió en tres y a él le tocó un tercio — así que compró donde podía permitírselo, en Vosne-Romanée y en las colinas de arriba, en Curtil-Vergy. Hoy trabaja con su hija Axelle.",
 "zh": "这是夜丘还没变贵时的样子：结实、带土气，没有一个多余的姿态。当家族产业一分为三、他只分到三分之一时，贝特朗·马沙尔·德·格拉蒙从头再来——于是他在自己付得起的地方买地：沃恩-罗曼尼，以及上头山坡的 Curtil-Vergy。如今他和女儿阿克塞尔一起做酒。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]

# the owner's single-word fix on a card already applied
r = prods["Domaine Armand Rousseau"]["blurb"]
r["hr"] = r["hr"].replace("dokupovao", "dokupljivao")
print("Rousseau: dokupovao -> dokupljivao")

for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-22s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
