# -*- coding: utf-8 -*-
"""Five cards the owner read and found unclear or badly opened (2026-08-12).

Mulassano: nobody said who Amilcare Mulassano was, so "za Amilcarea Mulassana,
za goste kafića" read as two unrelated things. He is the man who opened the
café — the card now says so, and the vermouth was poured to his guests only.

Kilchoman, Bladnoch: the punchline was at the bottom. Same rule as the wines,
now written into CLAUDE.md: the most appealing thing first, always.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Mulassano"] = {
 "hr": "Tramezzino — sendvič bez korice koji danas jede cijela Italija — izmišljen je za šankom ovog kafića na Piazzi Castello, a ime mu je dao Gabriele D'Annunzio, jer *sandwich* nije bio dovoljno talijanski. Vermut je nastao na isti način: vlasnik kafića Amilcare Mulassano naručio je vlastitu recepturu od Pietra Bordige, koji je upravo bio otvorio destileriju u Cuneu, i vermut se isprva točio samo gostima kafića. Bordiga ga radi i danas, s alpskim biljem branim rukom.",
 "en": "The tramezzino — the crustless sandwich all Italy eats today — was invented at the counter of this café on Piazza Castello, and Gabriele D'Annunzio named it, because *sandwich* was not Italian enough. The vermouth came about the same way: the café's owner, Amilcare Mulassano, commissioned a recipe of his own from Pietro Bordiga, who had just opened his distillery in Cuneo, and at first it was poured only to the café's guests. Bordiga makes it to this day, with alpine botanicals picked by hand.",
 "it": "Il tramezzino — il panino senza crosta che oggi mangia tutta l'Italia — fu inventato al banco di questo caffè in piazza Castello, e a battezzarlo fu Gabriele D'Annunzio, perché *sandwich* non era abbastanza italiano. Il vermouth è nato allo stesso modo: il proprietario del caffè, Amilcare Mulassano, commissionò una ricetta tutta sua a Pietro Bordiga, che aveva appena aperto la distilleria a Cuneo, e all'inizio lo si serviva solo ai clienti del caffè. Bordiga lo fa ancora oggi, con erbe alpine raccolte a mano.",
 "fr": "Le tramezzino — le sandwich sans croûte que toute l'Italie mange aujourd'hui — a été inventé au comptoir de ce café, piazza Castello, et c'est Gabriele D'Annunzio qui l'a baptisé, parce que *sandwich* n'était pas assez italien. Le vermouth est né de la même façon : le propriétaire du café, Amilcare Mulassano, a commandé sa propre recette à Pietro Bordiga, qui venait d'ouvrir sa distillerie à Cuneo, et on ne l'a d'abord servi qu'aux clients du café. Bordiga le fait encore aujourd'hui, avec des plantes alpines cueillies à la main.",
 "de": "Das Tramezzino — das rindenlose Sandwich, das heute ganz Italien isst — wurde am Tresen dieses Cafés an der Piazza Castello erfunden, und getauft hat es Gabriele D'Annunzio, weil *Sandwich* nicht italienisch genug war. Der Wermut entstand auf dieselbe Weise: Der Besitzer des Cafés, Amilcare Mulassano, bestellte bei Pietro Bordiga, der eben seine Brennerei in Cuneo eröffnet hatte, ein eigenes Rezept, und ausgeschenkt wurde er zunächst nur den Gästen des Cafés. Bordiga macht ihn bis heute, mit von Hand gepflückten Alpenkräutern.",
 "sl": "Tramezzino — sendvič brez skorje, ki ga danes je vsa Italija — so izumili za šankom te kavarne na Piazzi Castello, ime pa mu je dal Gabriele D'Annunzio, ker *sandwich* ni bil dovolj italijanski. Vermut je nastal na isti način: lastnik kavarne Amilcare Mulassano je pri Pietru Bordigi, ki je prav takrat odprl destilarno v Cuneu, naročil svojo lastno recepturo, in sprva so ga točili samo gostom kavarne. Bordiga ga dela še danes, z ročno nabranimi alpskimi zelišči.",
 "es": "El tramezzino — el sándwich sin corteza que hoy come toda Italia — se inventó en la barra de este café de la piazza Castello, y lo bautizó Gabriele D'Annunzio, porque *sandwich* no era bastante italiano. El vermut nació igual: el dueño del café, Amilcare Mulassano, le encargó una receta propia a Pietro Bordiga, que acababa de abrir su destilería en Cuneo, y al principio sólo se servía a los clientes del café. Bordiga lo sigue haciendo hoy, con hierbas alpinas recogidas a mano.",
 "zh": "tramezzino——如今全意大利都在吃的那种去边三明治——就是在城堡广场这家咖啡馆的吧台边发明的，命名者是加布里埃莱·邓南遮，因为 *sandwich* 不够意大利。味美思的来历一样：咖啡馆的老板阿米尔卡雷·穆拉萨诺，向刚在库内奥开设酒厂的皮埃特罗·博尔迪加订制了一份专属配方，起初只倒给咖啡馆的客人喝。这酒至今仍由 Bordiga 制作，用的是手工采摘的阿尔卑斯草药。"
}

NEW["Kilchoman"] = {
 "hr": "Farma koja peče viski, ne tvornica koja glumi farmu: ječam sije sama, slad slaže po podu i sve ostalo radi unutar istog dvorišta — jedina na Islayu koja put od sjemena do boce prijeđe bez izlaska kroz kapiju. Ostali slad kupuju s kopna. Bila je i prva nova destilerija na otoku nakon 124 godine, otvorena 2005.",
 "en": "A farm that makes whisky, not a factory playing at being a farm: it sows its own barley, spreads the malt across its own floor and does everything else inside the same yard — the only one on Islay to go from seed to bottle without passing through the gate. The others buy their malt from the mainland. It was also the island's first new distillery in 124 years, opened in 2005.",
 "it": "Una fattoria che fa whisky, non una fabbrica che gioca a fare la fattoria: semina il proprio orzo, stende il malto sul proprio pavimento e fa tutto il resto dentro la stessa corte — l'unica a Islay ad andare dal seme alla bottiglia senza uscire dal cancello. Gli altri comprano il malto dalla terraferma. È stata anche la prima distilleria nuova dell'isola dopo 124 anni, aperta nel 2005.",
 "fr": "Une ferme qui fait du whisky, pas une usine qui joue à la ferme : elle sème son orge, étend son malt sur son propre sol et fait tout le reste dans la même cour — la seule d'Islay à aller de la graine à la bouteille sans franchir le portail. Les autres achètent leur malt sur le continent. Elle fut aussi la première distillerie nouvelle de l'île depuis 124 ans, ouverte en 2005.",
 "de": "Ein Hof, der Whisky macht, keine Fabrik, die Hof spielt: Er sät seine eigene Gerste, breitet das Malz auf der eigenen Tenne aus und erledigt alles Weitere im selben Hof — der einzige auf Islay, der vom Korn bis zur Flasche kein Tor passiert. Die anderen kaufen ihr Malz vom Festland. Sie war zudem die erste neue Brennerei der Insel seit 124 Jahren, eröffnet 2005.",
 "sl": "Kmetija, ki dela viski, ne tovarna, ki se gre kmetijo: ječmen seje sama, slad razgrne po lastnih tleh in vse drugo opravi znotraj istega dvorišča — edina na Islayu, ki pot od semena do steklenice prehodi brez izhoda skozi vrata. Drugi slad kupujejo s celine. Bila je tudi prva nova destilarna na otoku po 124 letih, odprta leta 2005.",
 "es": "Una granja que hace whisky, no una fábrica que juega a ser granja: siembra su propia cebada, extiende la malta sobre su propio suelo y hace todo lo demás dentro del mismo patio — la única de Islay que va de la semilla a la botella sin cruzar la verja. Los demás compran la malta en el continente. Fue además la primera destilería nueva de la isla en 124 años, abierta en 2005.",
 "zh": "这是一座做威士忌的农场，而不是一间扮成农场的工厂：自种大麦，麦芽摊在自家地板上发，其余工序也都在同一个院子里完成——全艾雷岛唯一一家从种子到装瓶都不出大门的酒厂。其他人的麦芽都从岛外买。它也是艾雷岛 124 年来的第一家新酒厂，2005 年开业。"
}

NEW["Glenrothes"] = {
 "hr": "Bez ovog viskija ne bi bilo ni Cutty Sarka ni Famous Grousea: Glenrothes je stoljeće destilirao za tuđe kupaže i tek onda pustio vlastito ime na bocu. Zato ovdje broje berbe, ne godine — svaka boca kaže kad je destilirana, kao vino, jer kuća drži da 1998. i 2015. nisu ista stvar ni kad su jednako stare. Speyside bez dima i bez pokazivanja.",
 "en": "There would be no Cutty Sark and no Famous Grouse without this whisky: Glenrothes distilled for other people's blends for a century, and only then let its own name onto the bottle. Which is why they count vintages here, not years — every bottle says when it was distilled, like wine, because the house holds that 1998 and 2015 are not the same thing even when they are the same age. Speyside without smoke and without showing off.",
 "it": "Senza questo whisky non ci sarebbero né Cutty Sark né Famous Grouse: Glenrothes ha distillato per i blend degli altri per un secolo, e solo dopo ha messo il proprio nome in bottiglia. Per questo qui contano le annate, non gli anni — ogni bottiglia dice quando è stata distillata, come un vino, perché la casa ritiene che il 1998 e il 2015 non siano la stessa cosa nemmeno alla stessa età. Speyside senza fumo e senza mettersi in mostra.",
 "fr": "Sans ce whisky, il n'y aurait ni Cutty Sark ni Famous Grouse : Glenrothes a distillé un siècle durant pour les assemblages des autres, et n'a mis son nom sur la bouteille qu'ensuite. D'où les millésimes plutôt que les âges — chaque bouteille dit quand elle a été distillée, comme un vin, parce que la maison tient que 1998 et 2015 ne sont pas la même chose, même au même âge. Un Speyside sans fumée et sans esbroufe.",
 "de": "Ohne diesen Whisky gäbe es weder Cutty Sark noch Famous Grouse: Glenrothes brannte ein Jahrhundert lang für fremde Blends und ließ erst danach den eigenen Namen auf die Flasche. Darum zählt man hier Jahrgänge, nicht Jahre — jede Flasche sagt, wann sie gebrannt wurde, wie bei Wein, weil das Haus findet, 1998 und 2015 seien nicht dasselbe, auch wenn sie gleich alt sind. Speyside ohne Rauch und ohne Auftritt.",
 "sl": "Brez tega viskija ne bi bilo ne Cutty Sarka ne Famous Grousea: Glenrothes je stoletje destiliral za tuje zvrsti in šele nato spustil lastno ime na steklenico. Zato tu štejejo letnike, ne let — vsaka steklenica pove, kdaj je bila destilirana, kot pri vinu, ker hiša meni, da 1998 in 2015 nista ista stvar niti pri isti starosti. Speyside brez dima in brez razkazovanja.",
 "es": "Sin este whisky no habría ni Cutty Sark ni Famous Grouse: Glenrothes destiló un siglo para las mezclas de otros y sólo después dejó su nombre en la botella. Por eso aquí cuentan añadas, no años — cada botella dice cuándo se destiló, como un vino, porque la casa sostiene que 1998 y 2015 no son lo mismo ni siquiera con la misma edad. Speyside sin humo y sin exhibirse.",
 "zh": "没有这款威士忌，就没有顺风，也没有威雀：格兰路思为别人的调和威士忌蒸馏了整整一个世纪，之后才把自己的名字放上瓶身。所以这里数的是年份，不是酒龄——每一瓶都写明何时蒸馏，像葡萄酒一样，因为酒厂认为 1998 与 2015 即便同龄也不是一回事。这是不带烟熏、也不炫技的斯佩塞。"
}

NEW["Isle of Jura"] = {
 "hr": "Otok s jednom cestom, jednom destilerijom, dvjestotinjak ljudi i nekoliko tisuća jelena. George Orwell došao je tu 1946. u kuću bez struje i telefona na sjevernom kraju otoka, do koje se zadnjih 11 kilometara ide pješice, i ondje napisao roman *1984.* Sam je to mjesto opisao kao „do kojeg se ne da doći”. Viski je isti takav: bez dima, bez žurbe, bez publike.",
 "en": "An island with one road, one distillery, some two hundred people and several thousand deer. George Orwell came here in 1946, to a house at the northern end with no electricity and no telephone, the last 11 kilometres of it on foot, and there wrote the novel *1984*. He described the place himself as \"extremely un-get-at-able\". The whisky is the same: no smoke, no hurry, no audience.",
 "it": "Un'isola con una strada, una distilleria, un paio di centinaia di persone e qualche migliaio di cervi. George Orwell arrivò qui nel 1946, in una casa all'estremità nord senza elettricità né telefono, gli ultimi 11 chilometri a piedi, e vi scrisse il romanzo *1984*. Del posto disse lui stesso che era \"assolutamente irraggiungibile\". Il whisky è uguale: senza fumo, senza fretta, senza pubblico.",
 "fr": "Une île avec une route, une distillerie, quelque deux cents habitants et plusieurs milliers de cerfs. George Orwell est venu ici en 1946, dans une maison de l'extrémité nord sans électricité ni téléphone, les 11 derniers kilomètres à pied, et y a écrit le roman *1984*. Il décrivait lui-même l'endroit comme « absolument inaccessible ». Le whisky est pareil : sans fumée, sans hâte, sans public.",
 "de": "Eine Insel mit einer Straße, einer Brennerei, gut zweihundert Menschen und mehreren tausend Hirschen. George Orwell kam 1946 hierher, in ein Haus am Nordende ohne Strom und Telefon, die letzten 11 Kilometer zu Fuß, und schrieb dort den Roman *1984*. Den Ort nannte er selbst „völlig unerreichbar“. Der Whisky ist genauso: ohne Rauch, ohne Eile, ohne Publikum.",
 "sl": "Otok z eno cesto, eno destilarno, kakšnimi dvesto ljudmi in nekaj tisoč jeleni. George Orwell je prišel sem leta 1946, v hišo na severnem koncu brez elektrike in telefona, zadnjih 11 kilometrov peš, in tam napisal roman *1984*. Kraj je sam opisal kot »povsem nedosegljiv«. Viski je enak: brez dima, brez naglice, brez občinstva.",
 "es": "Una isla con una carretera, una destilería, unas doscientas personas y varios miles de ciervos. George Orwell llegó aquí en 1946, a una casa del extremo norte sin electricidad ni teléfono, los últimos 11 kilómetros a pie, y allí escribió la novela *1984*. Del lugar dijo él mismo que era \"absolutamente inalcanzable\". El whisky es igual: sin humo, sin prisa, sin público.",
 "zh": "一座只有一条路、一家酒厂、两百来人和几千头鹿的岛。1946 年，乔治·奥威尔来到这里，住进岛北端一栋没有电、也没有电话的房子——最后 11 公里只能步行——并在那里写下了小说《1984》。他自己形容那地方「根本到不了」。威士忌也是这样：没有烟熏，不赶时间，也不为观众。"
}

NEW["Bladnoch"] = {
 "hr": "Oživio ju je Australac koji je novac zaradio na organskom jogurtu. David Prior kupio je 2015. najjužniju destileriju Škotske i u podrumu zatekao bačve koje su ondje tiho ležale 19 godina. Kuća stoji uz rijeku u Wigtownshireu od 1817. i zatvarana je i otvarana toliko puta da je čudo što još stoji. Danas radi tiho, daleko od svih.",
 "en": "It was brought back by an Australian who made his money in organic yoghurt. David Prior bought Scotland's southernmost distillery in 2015 and found casks in the warehouse that had been lying there quietly for 19 years. The place has stood on the river in Wigtownshire since 1817 and has been closed and reopened so many times it is a wonder it still stands. It works quietly today, far from everyone.",
 "it": "L'ha fatta rinascere un australiano che aveva fatto i soldi con lo yogurt biologico. David Prior comprò nel 2015 la distilleria più a sud della Scozia e in magazzino trovò botti che stavano lì in silenzio da 19 anni. La casa sta sul fiume nel Wigtownshire dal 1817 ed è stata chiusa e riaperta tante volte che è un miracolo sia ancora in piedi. Oggi lavora in silenzio, lontano da tutti.",
 "fr": "Elle a été relevée par un Australien qui avait fait fortune dans le yaourt bio. David Prior a racheté en 2015 la distillerie la plus au sud d'Écosse et a trouvé au chai des fûts qui dormaient là depuis 19 ans. La maison est au bord de la rivière dans le Wigtownshire depuis 1817, fermée et rouverte tant de fois que c'est un miracle qu'elle tienne encore. Elle travaille aujourd'hui sans bruit, loin de tout.",
 "de": "Wiederbelebt hat sie ein Australier, der sein Geld mit Bio-Joghurt verdient hatte. David Prior kaufte 2015 die südlichste Brennerei Schottlands und fand im Lager Fässer, die dort still 19 Jahre gelegen hatten. Das Haus steht seit 1817 am Fluss in Wigtownshire und wurde so oft geschlossen und wieder geöffnet, dass es ein Wunder ist, dass es noch steht. Heute arbeitet es leise, weit weg von allem.",
 "sl": "Oživil jo je Avstralec, ki je denar zaslužil z ekološkim jogurtom. David Prior je leta 2015 kupil najjužnejšo destilarno Škotske in v skladišču našel sode, ki so tam tiho ležali 19 let. Hiša stoji ob reki v Wigtownshiru od leta 1817 in je bila zaprta in odprta tolikokrat, da je čudež, da še stoji. Danes dela tiho, daleč od vseh.",
 "es": "La resucitó un australiano que había hecho su dinero con yogur ecológico. David Prior compró en 2015 la destilería más meridional de Escocia y encontró en la nave barricas que llevaban allí, calladas, 19 años. La casa está junto al río en Wigtownshire desde 1817 y ha sido cerrada y reabierta tantas veces que es un milagro que siga en pie. Hoy trabaja en silencio, lejos de todos.",
 "zh": "让它复活的，是一个靠有机酸奶赚到钱的澳大利亚人。2015 年，大卫·普赖尔买下苏格兰最南端的这家酒厂，并在仓库里发现了一批已经安静躺了 19 年的桶。酒厂自 1817 年起就在威格敦郡的河边，关了又开、开了又关，多到能撑到今天堪称奇迹。如今它仍在安静地运转，远离所有人。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    for lg, text in langs.items():
        prods[key]["blurb"][lg] = text
    print("%-16s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("written")
