# -*- coding: utf-8 -*-
"""Clarity pass on the spirits (2026-08-12), all from the owner reading them.

The recurring fault is jargon used as if the guest already had it: muck, a
double retort, esters, a palenquero, even what mezcal *is*. A card that has to
be looked up has failed. Each is now explained in the sentence that uses it.

Renegade's note also stops repeating its own distillery card — see
scratch/note-vs-blurb.mjs for the other eight that do.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

BLURBS = {}

BLURBS["Hampden"] = {
 "hr": "Rum koji nikad nije popustio pred lakšim ukusom. U Trelawnyju od 1753.: fermentacija traje tjednima i hrani se muckom — kiselom kašom od ostataka prijašnjih destilacija koja mjesecima zrije u vlastitoj jami pa se vraća u kacu. Para zatim prolazi kroz kotao s dvije dodatne komore i svaki put izađe jača i mirisnija, a rezultat je destilat s najviše estera na svijetu: onog laka, banane i prezrelog voća po kojem se Jamajka prepoznaje. Dva i pol stoljeća sve je to odlazilo u tuđe kupaže — vlastito ime Hampden je pustio na bocu tek 2018.",
 "en": "A rum that never gave in to an easier taste. In Trelawny since 1753: the fermentation runs for weeks and is fed with muck — an acid sludge of leftovers from earlier distillations, ripened for months in its own pit and returned to the vat. The vapour then passes through a still with two extra chambers, coming out stronger and more aromatic each time, and the result is the most ester-rich spirit in the world: that varnish, banana and overripe fruit by which Jamaica is known. For two and a half centuries all of it went into other people's blends — Hampden only let its own name onto a bottle in 2018.",
 "it": "Un rum che non ha mai ceduto a un gusto più facile. A Trelawny dal 1753: la fermentazione dura settimane ed è nutrita col muck — una poltiglia acida di residui delle distillazioni precedenti, maturata per mesi in una fossa e rimessa nel tino. Il vapore passa poi in un alambicco con due camere aggiuntive e ogni volta esce più forte e più profumato; il risultato è il distillato più ricco di esteri al mondo: quella vernice, banana e frutta stramatura da cui si riconosce la Giamaica. Per due secoli e mezzo tutto finiva nei blend altrui — il proprio nome Hampden l'ha messo in bottiglia solo nel 2018.",
 "fr": "Un rhum qui n'a jamais cédé à un goût plus facile. À Trelawny depuis 1753 : la fermentation dure des semaines et se nourrit du muck — une bouillie acide de résidus des distillations passées, mûrie des mois dans sa propre fosse puis remise en cuve. La vapeur traverse ensuite un alambic à deux chambres supplémentaires et en ressort chaque fois plus forte et plus parfumée ; le résultat est le distillat le plus riche en esters au monde : ce vernis, cette banane et ce fruit trop mûr auxquels on reconnaît la Jamaïque. Deux siècles et demi durant, tout partait dans les assemblages des autres — Hampden n'a mis son nom sur une bouteille qu'en 2018.",
 "de": "Ein Rum, der nie einem leichteren Geschmack nachgegeben hat. In Trelawny seit 1753: Die Gärung läuft wochenlang und wird mit Muck gefüttert — einem sauren Brei aus Resten früherer Destillationen, der monatelang in einer eigenen Grube reift und zurück in den Bottich kommt. Der Dampf zieht danach durch eine Brennblase mit zwei zusätzlichen Kammern und kommt jedes Mal stärker und duftiger heraus; das Ergebnis ist das esterreichste Destillat der Welt: jener Lack, jene Banane, jenes überreife Obst, an dem man Jamaika erkennt. Zweieinhalb Jahrhunderte ging alles in fremde Blends — den eigenen Namen ließ Hampden erst 2018 auf eine Flasche.",
 "sl": "Rum, ki nikoli ni popustil lažjemu okusu. V Trelawnyju od leta 1753: fermentacija traje tedne in se hrani z muckom — kislo brozgo iz ostankov prejšnjih destilacij, ki mesece zori v lastni jami in se vrne v kad. Para nato gre skozi kotel z dvema dodatnima komorama in vsakič pride ven močnejša in bolj dišeča; rezultat je destilat z največ estri na svetu: tisti lak, banana in prezrelo sadje, po katerih se Jamajka prepozna. Dve stoletji in pol je vse odhajalo v tuje zvrsti — lastno ime je Hampden spustil na steklenico šele leta 2018.",
 "es": "Un ron que nunca cedió a un sabor más fácil. En Trelawny desde 1753: la fermentación dura semanas y se alimenta con muck — una papilla ácida de restos de destilaciones anteriores, madurada meses en su propio pozo y devuelta a la cuba. El vapor pasa después por un alambique con dos cámaras añadidas y sale cada vez más fuerte y más aromático; el resultado es el destilado con más ésteres del mundo: ese barniz, ese plátano y esa fruta pasada por los que se reconoce Jamaica. Durante dos siglos y medio todo se iba a las mezclas de otros — Hampden no puso su nombre en una botella hasta 2018.",
 "zh": "一款从不向「更好入口」低头的朗姆。自 1753 年就在特里劳尼：发酵长达数周，并以 muck 喂养——那是往次蒸馏残留物发酵成的酸浆，在自家坑里熟成数月后再倒回发酵槽。蒸气随后经过带两个附加腔室的蒸馏器，每过一道就更烈、更香；结果便是全世界酯类含量最高的原酒：那股清漆、香蕉与熟透果实的气味，正是牙买加的标志。两个半世纪里，这些酒全流进别人的调和酒——Hampden 直到 2018 年才把自家名字放上瓶身。"
}

BLURBS["Foursquare"] = {
 "hr": "Richard Seale je gotovo sam izborio da na rumu piše što je i u boci: bez dodanog šećera, bez boje, bez izgovora — i punjenja u jačini u kojoj su izašla iz bačve. Godinama je zbog toga bio manjina koju industrija nije htjela slušati; danas se po tim pravilima ravna pola svijeta. Destilerija u St Philipu stoji na staroj plantaži šećera.",
 "en": "Richard Seale all but single-handedly forced rum to state on the label what is actually in the bottle: no added sugar, no colouring, no excuses — and bottlings at the strength they left the cask. For years that made him a minority the industry did not want to listen to; today half the world follows those rules. The distillery in St Philip stands on an old sugar plantation.",
 "it": "Richard Seale ha imposto quasi da solo che sul rum sia scritto ciò che c'è davvero nella bottiglia: niente zucchero aggiunto, niente colore, niente scuse — e imbottigliamenti alla gradazione con cui sono usciti dalla botte. Per anni questo ne ha fatto una minoranza che l'industria non voleva ascoltare; oggi mezzo mondo segue quelle regole. La distilleria a St Philip sorge su una vecchia piantagione di canna.",
 "fr": "Richard Seale a presque à lui seul imposé que l'étiquette d'un rhum dise ce qu'il y a vraiment dans la bouteille : pas de sucre ajouté, pas de colorant, pas d'excuses — et des mises à la force du fût. Cela en a fait pendant des années une minorité que l'industrie ne voulait pas écouter ; aujourd'hui la moitié du monde suit ces règles. La distillerie de St Philip est bâtie sur une ancienne plantation sucrière.",
 "de": "Richard Seale hat beinahe im Alleingang durchgesetzt, dass auf einem Rum steht, was auch in der Flasche ist: kein zugesetzter Zucker, keine Farbe, keine Ausreden — und Abfüllungen in Fassstärke. Jahrelang machte ihn das zu einer Minderheit, der die Branche nicht zuhören wollte; heute richtet sich die halbe Welt nach diesen Regeln. Die Brennerei in St Philip steht auf einer alten Zuckerplantage.",
 "sl": "Richard Seale je skoraj sam izboril, da na rumu piše, kaj je tudi v steklenici: brez dodanega sladkorja, brez barve, brez izgovorov — in polnitve v jakosti, s kakršno so prišle iz soda. Leta ga je to delalo za manjšino, ki je industrija ni hotela poslušati; danes se po teh pravilih ravna pol sveta. Destilarna v St Philipu stoji na stari sladkorni plantaži.",
 "es": "Richard Seale impuso casi él solo que en el ron se escriba lo que de verdad hay en la botella: sin azúcar añadido, sin color, sin excusas — y embotellados a la fuerza con que salieron de la barrica. Durante años eso lo convirtió en una minoría que la industria no quería escuchar; hoy medio mundo sigue esas reglas. La destilería de St Philip se levanta sobre una vieja plantación de azúcar.",
 "zh": "理查德·西尔几乎凭一己之力，逼着朗姆在标签上写清瓶中究竟是什么：不加糖、不加色、不找借口——而且以出桶强度装瓶。多年来这让他成了行业不愿听的少数派；如今半个世界都按这些规矩来。位于圣菲利普的酒厂，就建在一座旧糖厂庄园之上。"
}

BLURBS["Mars Shinshu"] = {
 "hr": "Gotovo 20 godina uopće nije radila: ugašena je kad je viski u Japanu prestao ići, a upaljena ponovno 2011., taman kad je počeo ići svima. Stoji na oko 800 metara u Japanskim Alpama i najviša je destilerija viskija u Japanu — zrak je rijedak, ljeta kratka, zima duga, pa bačva ovdje radi sporo i to se u čaši čuje.",
 "en": "For nearly 20 years it did not work at all: shut when whisky stopped selling in Japan, and lit again in 2011, just as it started selling to everyone. It stands at around 800 metres in the Japanese Alps and is the highest whisky distillery in Japan — thin air, short summers, long winters, so the cask works slowly here and you can hear it in the glass.",
 "it": "Per quasi 20 anni non ha lavorato affatto: spenta quando in Giappone il whisky smise di vendere, riaccesa nel 2011, giusto quando ricominciò a venderlo a tutti. Sta a circa 800 metri sulle Alpi giapponesi ed è la distilleria di whisky più alta del Giappone — aria rarefatta, estati corte, inverni lunghi, così la botte qui lavora piano e nel bicchiere si sente.",
 "fr": "Pendant près de 20 ans, elle n'a pas travaillé du tout : éteinte quand le whisky ne se vendait plus au Japon, rallumée en 2011, juste quand il s'est mis à se vendre partout. Elle se tient à quelque 800 mètres dans les Alpes japonaises et c'est la distillerie de whisky la plus haute du Japon — air raréfié, étés courts, hivers longs, si bien que le fût travaille lentement et que cela s'entend dans le verre.",
 "de": "Fast 20 Jahre lang arbeitete sie gar nicht: stillgelegt, als Whisky sich in Japan nicht mehr verkaufte, und 2011 wieder angezündet, gerade als er sich überall zu verkaufen begann. Sie steht auf rund 800 Metern in den Japanischen Alpen und ist Japans höchstgelegene Whiskybrennerei — dünne Luft, kurze Sommer, lange Winter, also arbeitet das Fass hier langsam, und man hört es im Glas.",
 "sl": "Skoraj 20 let sploh ni delala: ugasnili so jo, ko se viski na Japonskem ni več prodajal, in jo leta 2011 spet prižgali, ravno ko se je začel prodajati vsem. Stoji na okoli 800 metrih v Japonskih Alpah in je najvišje ležeča destilarna viskija na Japonskem — zrak je redek, poletja kratka, zime dolge, zato sod tu dela počasi in to se v kozarcu sliši.",
 "es": "Durante casi 20 años no trabajó en absoluto: apagada cuando el whisky dejó de venderse en Japón, y encendida de nuevo en 2011, justo cuando empezó a vendérsele a todo el mundo. Se alza a unos 800 metros en los Alpes japoneses y es la destilería de whisky más alta de Japón — aire fino, veranos cortos, inviernos largos, así que aquí la barrica trabaja despacio y se oye en la copa.",
 "zh": "它曾有将近 20 年完全停摆：日本威士忌卖不动时熄了火，2011 年重新点燃，恰好赶上全世界都开始买。它坐落在日本阿尔卑斯约 800 米处，是日本海拔最高的威士忌酒厂——空气稀薄、夏短冬长，桶在这里走得慢，杯中听得出来。"
}

BLURBS["Velier"] = {
 "hr": "Velier nije destilerija nego kuća iz Genove koja bira tuđe bačve. Luca Gargano obilazi karipske otoke, kupuje pojedinačne bačve i puni ih bez šećera, bez boje i bez razrjeđivanja — i time je sam promijenio ono što svijet misli da rum jest. Kad je Demerara u Gvajani ugasila stare kotlove, otkupio je zalihe i od njih napravio boce koje danas idu na aukcije.",
 "en": "Velier is not a distillery but a house in Genoa that selects other people's casks. Luca Gargano travels the Caribbean islands, buys single casks and bottles them with no sugar, no colour and no dilution — and in doing so changed, single-handedly, what the world thinks rum is. When Demerara in Guyana shut down its old stills, he bought up the stock and turned it into bottles that go to auction today.",
 "it": "Velier non è una distilleria ma una casa di Genova che sceglie le botti degli altri. Luca Gargano gira le isole caraibiche, compra singole botti e le imbottiglia senza zucchero, senza colore e senza diluizione — e così ha cambiato da solo l'idea che il mondo ha del rum. Quando in Guyana la Demerara ha spento i vecchi alambicchi, ne ha comprato le scorte e ne ha fatto bottiglie che oggi vanno all'asta.",
 "fr": "Velier n'est pas une distillerie mais une maison de Gênes qui choisit les fûts des autres. Luca Gargano parcourt les îles des Caraïbes, achète des fûts uniques et les met en bouteille sans sucre, sans colorant et sans réduction — et il a changé à lui seul l'idée que le monde se fait du rhum. Quand la Demerara, en Guyana, a éteint ses vieux alambics, il en a racheté les stocks et en a fait des bouteilles qui passent aujourd'hui aux enchères.",
 "de": "Velier ist keine Brennerei, sondern ein Haus in Genua, das fremde Fässer auswählt. Luca Gargano bereist die karibischen Inseln, kauft einzelne Fässer und füllt sie ohne Zucker, ohne Farbe und ohne Verdünnung ab — und hat damit im Alleingang verändert, was die Welt für Rum hält. Als Demerara in Guyana die alten Brennblasen stilllegte, kaufte er die Bestände auf und machte daraus Flaschen, die heute versteigert werden.",
 "sl": "Velier ni destilarna, ampak hiša iz Genove, ki izbira tuje sode. Luca Gargano obiskuje karibske otoke, kupuje posamezne sode in jih polni brez sladkorja, brez barve in brez razredčevanja — in s tem je sam spremenil to, kar svet misli, da rum je. Ko je Demerara v Gvajani ugasnila stare kotle, je odkupil zaloge in iz njih naredil steklenice, ki danes gredo na dražbe.",
 "es": "Velier no es una destilería sino una casa de Génova que elige las barricas de otros. Luca Gargano recorre las islas del Caribe, compra barricas sueltas y las embotella sin azúcar, sin color y sin dilución — y con eso cambió él solo lo que el mundo cree que es el ron. Cuando Demerara, en Guyana, apagó sus viejos alambiques, compró las existencias e hizo con ellas botellas que hoy van a subasta.",
 "zh": "Velier 不是酒厂，而是一家位于热那亚、专门挑别人桶的公司。卢卡·加尔加诺跑遍加勒比各岛，买下单桶，然后不加糖、不加色、不稀释地装瓶——凭一己之力改变了世界对朗姆的看法。当圭亚那的德梅拉拉熄掉那些老蒸馏器时，他买下库存，做成了如今在拍卖会上流转的酒。"
}

BLURBS["Del Maguey"] = {
 "hr": "Prije njega mezcal se izvozio kao anonimna roba s crvom u boci. Mezcal je pečena agava — rođak tequile, samo što se agava peče u zemlji i smije biti bilo koja od dvadesetak sorti. Ron Cooper, američki umjetnik koji je godine proveo u Oaxaci, počeo ga je osamdesetih puniti selo po selo i na etiketu stavljati ime sela i palenquera — čovjeka koji ga u svojoj maloj seoskoj destileriji i ispeče. Kategorija koju je time otvorio danas je sve što mezcal jest.",
 "en": "Before him, mezcal was exported as anonymous goods with a worm in the bottle. Mezcal is roasted agave — tequila's cousin, except that the agave is baked in the ground and may be any of some twenty varieties. Ron Cooper, an American artist who spent years in Oaxaca, began in the 1980s to bottle it village by village and to put on the label the name of the village and of the palenquero — the man who makes it in his own small village distillery. The category he opened is everything mezcal is today.",
 "it": "Prima di lui il mezcal si esportava come merce anonima col verme nella bottiglia. Il mezcal è agave cotta — cugino della tequila, solo che l'agave si cuoce nella terra e può essere una qualsiasi di una ventina di varietà. Ron Cooper, artista americano che passò anni a Oaxaca, cominciò negli anni Ottanta a imbottigliarlo villaggio per villaggio e a mettere in etichetta il nome del villaggio e del palenquero — l'uomo che lo distilla nella sua piccola distilleria di paese. La categoria che ha aperto è oggi tutto ciò che il mezcal è.",
 "fr": "Avant lui, le mezcal s'exportait comme une marchandise anonyme avec un ver dans la bouteille. Le mezcal, c'est de l'agave cuite — le cousin de la tequila, sauf que l'agave cuit dans la terre et peut être l'une d'une vingtaine de variétés. Ron Cooper, artiste américain qui a passé des années à Oaxaca, s'est mis dans les années 1980 à l'embouteiller village par village et à inscrire sur l'étiquette le nom du village et du palenquero — l'homme qui le distille dans sa petite distillerie de campagne. La catégorie qu'il a ouverte est aujourd'hui tout ce qu'est le mezcal.",
 "de": "Vor ihm wurde Mezcal als anonyme Ware mit einem Wurm in der Flasche exportiert. Mezcal ist gebackene Agave — der Vetter des Tequila, nur dass die Agave in der Erde gegart wird und eine von rund zwanzig Sorten sein darf. Ron Cooper, ein amerikanischer Künstler, der Jahre in Oaxaca verbrachte, begann in den 1980ern, ihn Dorf für Dorf abzufüllen und den Namen des Dorfes und des Palenquero aufs Etikett zu setzen — des Mannes, der ihn in seiner kleinen Dorfbrennerei macht. Die Kategorie, die er öffnete, ist heute alles, was Mezcal ist.",
 "sl": "Pred njim se je mezcal izvažal kot anonimno blago s črvom v steklenici. Mezcal je pečena agava — sorodnik tekile, le da se agava peče v zemlji in je lahko katera koli od kakšnih dvajsetih sort. Ron Cooper, ameriški umetnik, ki je v Oaxaci preživel leta, ga je v osemdesetih začel polniti vas za vasjo in na etiketo pisati ime vasi in palenquera — človeka, ki ga v svoji majhni vaški destilarni tudi naredi. Kategorija, ki jo je odprl, je danes vse, kar mezcal je.",
 "es": "Antes de él, el mezcal se exportaba como mercancía anónima con un gusano en la botella. El mezcal es agave cocido — primo del tequila, sólo que el agave se cuece en la tierra y puede ser cualquiera de unas veinte variedades. Ron Cooper, artista estadounidense que pasó años en Oaxaca, empezó en los años ochenta a embotellarlo pueblo por pueblo y a poner en la etiqueta el nombre del pueblo y del palenquero — el hombre que lo hace en su pequeña destilería de aldea. La categoría que abrió es hoy todo lo que el mezcal es.",
 "zh": "在他之前，梅斯卡尔是作为匿名货物出口的，瓶里还泡着一条虫。梅斯卡尔就是烤过的龙舌兰——特其拉的表亲，只不过龙舌兰是埋在土里烤的，而且可以是二十来个品种中的任何一种。美国艺术家罗恩·库珀在瓦哈卡待了多年，八十年代开始按村子逐一装瓶，并把村名与 palenquero 的名字写上酒标——那是在自家小村酒坊里把酒做出来的人。他开创的这个品类，就是今天梅斯卡尔的全部。"
}

BLURBS["Bruxo"] = {
 "hr": "Ime znači vračar, a dim u čaši nije aroma koja se dodaje nego trag vatre u zemlji: agava se peče u zemljanoj jami na drva, pa melje kamenim kolom koje vuče konj — tako nastaje mezcal, pečena agava kakvu Oaxaca radi stoljećima. Drukčije se i ne može: struje u tim selima nema, a jama i konj ne kvare se.",
 "en": "The name means sorcerer, and the smoke in the glass is not an aroma anyone adds but the trace of a fire in the ground: the agave is baked in an earthen wood-fired pit, then crushed by a stone wheel pulled by a horse — that is how mezcal is made, roasted agave as Oaxaca has done it for centuries. There is no other way: those villages have no electricity, and a pit and a horse do not break down.",
 "it": "Il nome significa stregone, e il fumo nel bicchiere non è un aroma che si aggiunge ma la traccia di un fuoco nella terra: l'agave si cuoce in una fossa di terra a legna, poi si macina con una ruota di pietra tirata da un cavallo — così nasce il mezcal, agave cotta come Oaxaca la fa da secoli. Altrimenti non si può: in quei villaggi non c'è corrente, e la fossa e il cavallo non si guastano.",
 "fr": "Le nom veut dire sorcier, et la fumée dans le verre n'est pas un arôme qu'on ajoute mais la trace d'un feu dans la terre : l'agave cuit dans une fosse de terre au bois, puis passe sous une meule de pierre tirée par un cheval — c'est ainsi que naît le mezcal, de l'agave cuite comme Oaxaca le fait depuis des siècles. On ne peut pas faire autrement : ces villages n'ont pas l'électricité, et une fosse et un cheval ne tombent pas en panne.",
 "de": "Der Name heißt Hexer, und der Rauch im Glas ist kein zugesetztes Aroma, sondern die Spur eines Feuers in der Erde: Die Agave wird in einer erdigen Holzgrube gebacken und dann von einem Steinrad zermahlen, das ein Pferd zieht — so entsteht Mezcal, gebackene Agave, wie Oaxaca sie seit Jahrhunderten macht. Anders geht es nicht: In diesen Dörfern gibt es keinen Strom, und eine Grube und ein Pferd fallen nicht aus.",
 "sl": "Ime pomeni čarovnik, dim v kozarcu pa ni aroma, ki bi se dodala, ampak sled ognja v zemlji: agava se peče v zemeljski jami na drva, nato jo zmelje kamnito kolo, ki ga vleče konj — tako nastane mezcal, pečena agava, kakršno Oaxaca dela že stoletja. Drugače ne gre: v teh vaseh ni elektrike, jama in konj pa se ne pokvarita.",
 "es": "El nombre significa brujo, y el humo en la copa no es un aroma que se añada sino el rastro de un fuego en la tierra: el agave se cuece en un horno de tierra a leña y luego se muele con una rueda de piedra tirada por un caballo — así nace el mezcal, agave cocido como Oaxaca lo hace desde hace siglos. No se puede de otro modo: en esos pueblos no hay electricidad, y un horno y un caballo no se averían.",
 "zh": "这名字的意思是「巫师」，而杯中的烟并不是谁加进去的香气，而是地里那团火留下的痕迹：龙舌兰在土坑里以柴火焖烤，再由马拉着石磨碾碎——梅斯卡尔就是这样来的，也就是瓦哈卡做了几个世纪的烤龙舌兰。别无他法：那些村子没有电，而土坑和马不会坏。"
}

BLURBS["Cimarrón"] = {
 "hr": "Desetljećima su uzgajali agavu za tuđe marke, a onda odlučili napraviti i svoju. Los Altos u Jalisci leži visoko, pa agava ondje dozrijeva sporije i dolazi slađa; kuća je peče u zidanoj peći, bez aditiva i bez šminke. Tequila kakvu piju oni koji je i uzgajaju — a ne ona koju kupuješ zbog imena na etiketi.",
 "en": "For decades they grew agave for other people's brands, then decided to make one of their own. Los Altos in Jalisco lies high, so the agave ripens more slowly there and comes sweeter; the house bakes it in a brick oven, with no additives and no make-up. The tequila drunk by the people who grow it — not the kind you buy for the name on the label.",
 "it": "Per decenni hanno coltivato agave per i marchi altrui, poi hanno deciso di farne uno loro. Los Altos, in Jalisco, sta in alto, così l'agave matura più lentamente ed è più dolce; la casa la cuoce in forno di mattoni, senza additivi e senza trucco. La tequila che bevono quelli che la coltivano — non quella che si compra per il nome in etichetta.",
 "fr": "Pendant des décennies, ils ont cultivé l'agave pour les marques des autres, puis ont décidé d'en faire une à eux. Los Altos, au Jalisco, est en altitude : l'agave y mûrit plus lentement et arrive plus sucrée ; la maison la cuit au four de briques, sans additifs et sans fard. La tequila que boivent ceux qui la cultivent — pas celle qu'on achète pour le nom sur l'étiquette.",
 "de": "Jahrzehntelang bauten sie Agave für fremde Marken an, dann beschlossen sie, eine eigene zu machen. Los Altos in Jalisco liegt hoch, die Agave reift dort langsamer und kommt süßer; das Haus backt sie im Ziegelofen, ohne Zusätze und ohne Schminke. Der Tequila, den die trinken, die ihn anbauen — nicht der, den man wegen des Namens auf dem Etikett kauft.",
 "sl": "Desetletja so gojili agavo za tuje znamke, potem pa se odločili narediti še svojo. Los Altos v Jalisci leži visoko, zato agava tam dozoreva počasneje in je slajša; hiša jo peče v zidani peči, brez dodatkov in brez šminke. Tekila, kakršno pijejo tisti, ki jo tudi gojijo — in ne tista, ki jo kupiš zaradi imena na etiketi.",
 "es": "Durante décadas cultivaron agave para marcas ajenas, y luego decidieron hacer la suya. Los Altos, en Jalisco, está en altura, así que el agave madura más despacio y llega más dulce; la casa lo cuece en horno de mampostería, sin aditivos y sin maquillaje. El tequila que beben quienes lo cultivan — no el que se compra por el nombre de la etiqueta.",
 "zh": "他们为别人的品牌种了几十年龙舌兰，后来决定做一个自己的。哈利斯科的 Los Altos 地势高，龙舌兰成熟得更慢、也更甜；酒厂用砖砌炉窑烘烤，不加添加剂，不施粉黛。这是种龙舌兰的人自己喝的特其拉——而不是你因为标签上的名字才买的那种。"
}

# Mount Gay: "rumarska marka" is not Croatian — "rumska marka" is.
FIX = {"Mount Gay": [("rumarskom markom", "rumskom markom")]}

# Renegade's note repeated its own distillery card almost word for word.
NOTE = {
 "habitation-velier--renegade-2020": {
  "hr": "Bez bačve nema se iza čega sakriti. Ovo punjenje nije vidjelo drvo, pa je u čaši samo trska s jedne njive i ono što je od nje ostalo poslije kotla — slano, travnato, živo. Malo koji rum se usudi izaći ovako gol.",
  "en": "With no cask there is nowhere to hide. This bottling never saw wood, so what is in the glass is cane from a single field and whatever survived the still — salty, grassy, alive. Few rums dare come out this bare.",
  "it": "Senza botte non c'è dove nascondersi. Questo imbottigliamento non ha visto legno, così nel bicchiere c'è solo canna di un unico campo e ciò che ne è rimasto dopo l'alambicco — salato, erbaceo, vivo. Pochi rum osano uscire così nudi.",
  "fr": "Sans fût, on ne peut se cacher nulle part. Cette mise n'a jamais vu le bois : dans le verre, il n'y a que la canne d'une seule parcelle et ce qui en a réchappé après l'alambic — salé, herbacé, vivant. Peu de rhums osent sortir aussi nus.",
  "de": "Ohne Fass gibt es kein Versteck. Diese Abfüllung hat nie Holz gesehen, im Glas ist also nur Zuckerrohr von einem einzigen Feld und was nach der Brennblase davon übrig blieb — salzig, grasig, lebendig. Wenige Rums trauen sich so nackt heraus.",
  "sl": "Brez soda se ni kam skriti. To polnjenje ni videlo lesa, zato je v kozarcu le trs z ene njive in tisto, kar je od njega ostalo po kotlu — slano, travnato, živo. Malokateri rum si upa ven tako gol.",
  "es": "Sin barrica no hay dónde esconderse. Este embotellado nunca vio madera, así que en la copa hay sólo caña de una única parcela y lo que quedó de ella tras el alambique — salado, herbáceo, vivo. Pocos rones se atreven a salir tan desnudos.",
  "zh": "没有木桶，就无处可藏。这一瓶从未过桶，杯中只有来自单一地块的甘蔗，以及它在蒸馏之后剩下的东西——咸、青草、活。很少有朗姆敢这样赤裸地出场。"
 }
}

p = "data/producers.json"
d = json.loads(open(p, "r", encoding="utf-8", newline="").read())
for key, langs in BLURBS.items():
    for lg, text in langs.items():
        d["producers"][key]["blurb"][lg] = text
    print("%-14s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
for key, subs in FIX.items():
    for lg, t in d["producers"][key]["blurb"].items():
        for a, b in subs:
            if a in t: d["producers"][key]["blurb"][lg] = t.replace(a, b); print(f"  {key} [{lg}]: {a} -> {b}")
open(p, "w", encoding="utf-8", newline="").write((json.dumps(d, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))

p = "library/wines.json"
w = json.loads(open(p, "r", encoding="utf-8", newline="").read())
for ref, langs in NOTE.items():
    w["wines"][ref]["note"] = langs
    print("note rewritten:", ref)
open(p, "w", encoding="utf-8", newline="").write((json.dumps(w, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("written")
