# -*- coding: utf-8 -*-
"""Eight corrections the owner made reading the cards (2026-08-12).

Four are Croatian that does not parse ("ime dolazi od oblika" — of what?),
one is a wrong word (opatija/samostan), and three are openings that are true
but flat. Moët's plénitudes get the years on lees, because a guest looking at
4.850 € deserves to know what the money buys.
"""
import json, sys
sys.stdout.reconfigure(encoding="utf-8")

NEW = {}

NEW["Château La Pointe"] = {
 "hr": "Ime dolazi od jedne parcele: uz sam ulaz u imanje leži oštro zašiljena, trokutasta — la pointe, vrh. Godine 1868. bilo je jedno od prva dva imanja u Pomerolu kojima je uopće dopušteno da se nazovu châteauom. 23 hektara loze i 2 hektara uređenog vrta; merlot s cabernet francom, na šljunku i glini.",
 "en": "The name comes from a single plot: right by the entrance to the estate lies a sharply angled, triangular one — la pointe, the point. In 1868 it was one of the first two estates in Pomerol allowed to call itself a château at all. 23 hectares of vines and 2 hectares of formal garden; Merlot with Cabernet Franc, on gravel and clay.",
 "it": "Il nome viene da una parcella: proprio all'ingresso della tenuta ne giace una appuntita, triangolare — la pointe, la punta. Nel 1868 fu una delle prime due tenute di Pomerol cui fu concesso di chiamarsi château. 23 ettari di vigna e 2 ettari di giardino all'italiana; merlot con cabernet franc, su ghiaia e argilla.",
 "fr": "Le nom vient d'une parcelle : à l'entrée même du domaine s'en trouve une aiguë, triangulaire — la pointe. En 1868, il fut l'un des deux premiers domaines de Pomerol autorisés à se dire château. 23 hectares de vignes et 2 hectares de jardin dessiné ; merlot avec cabernet franc, sur graves et argile.",
 "de": "Der Name kommt von einer Parzelle: gleich am Eingang des Guts liegt eine spitz zulaufende, dreieckige — la pointe, die Spitze. 1868 war es eines der ersten zwei Güter in Pomerol, die sich überhaupt Château nennen durften. 23 Hektar Reben und 2 Hektar angelegter Garten; Merlot mit Cabernet Franc, auf Kies und Lehm.",
 "sl": "Ime prihaja od ene parcele: tik ob vhodu na posestvo leži ostro zašiljena, trikotna — la pointe, konica. Leta 1868 je bilo eno prvih dveh posestev v Pomerolu, ki so se sploh smela imenovati château. 23 hektarov trt in 2 hektara urejenega vrta; merlot s cabernet francom, na produ in glini.",
 "es": "El nombre viene de una parcela: justo a la entrada de la finca hay una afilada, triangular — la pointe, la punta. En 1868 fue una de las dos primeras fincas de Pomerol autorizadas a llamarse château. 23 hectáreas de viña y 2 hectáreas de jardín trazado; Merlot con Cabernet Franc, sobre grava y arcilla.",
 "zh": "名字来自一块园地：就在庄园入口旁，有一块尖锐的三角形地——la pointe，尖角。1868 年，它是波美侯最早获准自称 château 的两座庄园之一。23 公顷葡萄园，2 公顷修整的花园；美乐配品丽珠，长在砾石与黏土上。"
}

NEW["Salon"] = {
 "hr": "Eugène-Aimé Salon nije htio prodavati vino: napravio je blanc de blancs iz jednog sela za sebe i svoje goste. Prva berba u prodaji bila je 1921., a u stoljeće i nešto proglasili su ih manje od 45 — u godinama koje ne zasluže ime, grožđe jednostavno ode sestrinskoj kući Delamotte, koja je na istoj adresi i pod istom upravom. I koja je također na ovoj karti. Jedno selo, jedna sorta, i pravo da vina ne bude.",
 "en": "Eugène-Aimé Salon did not want to sell wine: he made a blanc de blancs from one village for himself and his guests. The first vintage on sale was 1921, and in a century and a bit they have declared fewer than 45 — in years that do not deserve the name the fruit simply goes to the sister house, Delamotte, at the same address and under the same management. Which is also on this list. One village, one grape, and the right for the wine not to exist.",
 "it": "Eugène-Aimé Salon non voleva vendere vino: fece un blanc de blancs da un solo paese, per sé e per i suoi ospiti. La prima annata in vendita fu il 1921, e in poco più di un secolo ne hanno dichiarate meno di 45 — nelle annate che non meritano il nome l'uva va semplicemente alla casa sorella Delamotte, stesso indirizzo e stessa direzione. Che è anch'essa su questa carta. Un paese, un vitigno, e il diritto che il vino non ci sia.",
 "fr": "Eugène-Aimé Salon ne voulait pas vendre de vin : il a fait un blanc de blancs d'un seul village, pour lui et ses invités. Le premier millésime commercialisé fut 1921, et en un siècle et quelques ils en ont déclaré moins de 45 — les années qui ne méritent pas le nom, le raisin part tout simplement à la maison sœur Delamotte, même adresse et même direction. Laquelle figure aussi sur cette carte. Un village, un cépage, et le droit pour le vin de ne pas exister.",
 "de": "Eugène-Aimé Salon wollte keinen Wein verkaufen: Er machte einen Blanc de Blancs aus einem einzigen Dorf, für sich und seine Gäste. Der erste verkaufte Jahrgang war 1921, und in gut einem Jahrhundert wurden weniger als 45 erklärt — in Jahren, die den Namen nicht verdienen, geht die Ernte schlicht ans Schwesterhaus Delamotte, gleiche Adresse, gleiche Leitung. Das ebenfalls auf dieser Karte steht. Ein Dorf, eine Rebsorte und das Recht, dass es den Wein nicht gibt.",
 "sl": "Eugène-Aimé Salon ni hotel prodajati vina: naredil je blanc de blancs iz ene same vasi, zase in za svoje goste. Prvi letnik v prodaji je bil 1921, v stoletje in nekaj pa so jih razglasili manj kot 45 — v letih, ki imena ne zaslužijo, grozdje preprosto odide k sestrski hiši Delamotte, na istem naslovu in pod isto upravo. Ki je prav tako na tej karti. Ena vas, ena sorta in pravica, da vina ni.",
 "es": "Eugène-Aimé Salon no quería vender vino: hizo un blanc de blancs de un solo pueblo, para él y sus invitados. La primera añada a la venta fue 1921, y en un siglo y pico han declarado menos de 45 — en los años que no merecen el nombre la uva se va sin más a la casa hermana Delamotte, misma dirección y misma dirección de casa. Que está también en esta carta. Un pueblo, una variedad y el derecho a que el vino no exista.",
 "zh": "欧仁-埃梅·萨隆本来并不想卖酒：他只用一个村子的果实做白中白，给自己和客人喝。第一个上市年份是 1921 年，一个多世纪里他们宣告过的年份不到 45 个——遇上配不上这个名字的年份，果实就干脆送去同一地址、同一管理层的姊妹酒庄 Delamotte，那家也在这份酒单上。一个村子，一个品种，以及让酒不存在的权利。"
}

NEW["Vouette"] = {
 "hr": "Susjedi su ga iza leđa prozvali *ubojicom konja*: parcele su tako strme da ih je obrađivao konjem. Kaže da nijedan nije nastradao i da su radili sjajno. Bertrand Gautherot učio je kod Anselmea Selossea, koji je također na ovoj karti, pa se vratio u Buxières-sur-Arce — na sam južni rub Champagne, bliže Chablisu nego Reimsu. Biodinamika od 1998., 4 hektara, i šampanjac bez ijednog grama šećera na kraju, jer nema što skrivati.",
 "en": "The neighbours took to calling him *the horse killer* behind his back: the slopes are so steep he worked them with a horse. He says not one came to harm and that they did marvellous work. Bertrand Gautherot trained under Anselme Selosse, who is also on this list, then went back to Buxières-sur-Arce — the southern edge of Champagne, closer to Chablis than to Reims. Biodynamic since 1998, 4 hectares, and champagne with not a gram of sugar at the end, because there is nothing to hide.",
 "it": "I vicini lo chiamavano alle spalle *l'ammazzacavalli*: le parcelle sono così ripide che le lavorava col cavallo. Dice che nessuno si è fatto male e che hanno lavorato benissimo. Bertrand Gautherot ha imparato da Anselme Selosse, anch'egli su questa carta, poi è tornato a Buxières-sur-Arce — sul margine meridionale della Champagne, più vicino a Chablis che a Reims. Biodinamica dal 1998, 4 ettari, e uno champagne senza un grammo di zucchero alla fine, perché non c'è nulla da nascondere.",
 "fr": "Les voisins l'appelaient dans son dos *le tueur de chevaux* : les parcelles sont si raides qu'il les travaillait au cheval. Il dit qu'aucun n'a souffert et qu'ils ont fait un travail magnifique. Bertrand Gautherot a appris chez Anselme Selosse, lui aussi sur cette carte, puis il est rentré à Buxières-sur-Arce — tout au sud de la Champagne, plus près de Chablis que de Reims. Biodynamie depuis 1998, 4 hectares, et un champagne sans un gramme de sucre à la fin, parce qu'il n'y a rien à cacher.",
 "de": "Die Nachbarn nannten ihn hinter seinem Rücken *den Pferdemörder*: Die Parzellen sind so steil, dass er sie mit dem Pferd bearbeitete. Er sagt, keinem sei etwas geschehen und sie hätten großartig gearbeitet. Bertrand Gautherot lernte bei Anselme Selosse, der ebenfalls auf dieser Karte steht, und ging dann zurück nach Buxières-sur-Arce — an den Südrand der Champagne, näher an Chablis als an Reims. Biodynamie seit 1998, 4 Hektar, und ein Champagner ohne ein Gramm Zucker am Ende, weil es nichts zu verbergen gibt.",
 "sl": "Sosedje so ga za hrbtom klicali *konjemorec*: parcele so tako strme, da jih je obdeloval s konjem. Pravi, da se ni poškodoval nobeden in da so delali odlično. Bertrand Gautherot se je učil pri Anselmu Selossu, ki je prav tako na tej karti, nato pa se vrnil v Buxières-sur-Arce — na sam južni rob Champagne, bliže Chablisu kot Reimsu. Biodinamika od 1998, 4 hektari in šampanjec brez enega samega grama sladkorja na koncu, ker ni česa skrivati.",
 "es": "Los vecinos lo llamaban a sus espaldas *el matacaballos*: las parcelas son tan empinadas que las trabajaba con caballo. Dice que ninguno sufrió y que trabajaron de maravilla. Bertrand Gautherot aprendió con Anselme Selosse, que está también en esta carta, y volvió luego a Buxières-sur-Arce — en el borde sur de Champaña, más cerca de Chablis que de Reims. Biodinámica desde 1998, 4 hectáreas, y un champán sin un gramo de azúcar al final, porque no hay nada que esconder.",
 "zh": "邻居在背后叫他*杀马的人*：坡太陡，他只能用马耕作。他说没有一匹马出事，而且它们干得极好。贝特朗·戈特罗曾师从安塞尔姆·瑟洛斯——那家也在这份酒单上——之后回到 Buxières-sur-Arce：香槟最南端，离夏布利比离兰斯更近。1998 年起生物动力，4 公顷，最后一克糖也不加，因为没有什么需要遮掩。"
}

NEW["Moët"] = {
 "hr": "Dom Pérignon nije izumio šampanjac — bio je benediktinski redovnik zadužen za podrum samostana u Hautvillersu, a posao mu je bio suprotan: da vino ne pjeni. Ono što jest napravio je kupaža: naučio je slagati grožđe iz različitih sela u jedno bolje vino. Po njemu se zove cuvée koja iz iste berbe izlazi u nekoliko navrata: prvo izdanje nakon 8 do 9 godina na talogu, P2 nakon 15-ak, P3 nakon 25 i više. P2 i P3 dakle nisu starije boce nego iste, samo mnogo dulje ostavljene s kvascem — i to je ono što se u čaši osjeti kao dubina.",
 "en": "Dom Pérignon did not invent champagne — he was the Benedictine monk in charge of the monastery cellar at Hautvillers, and his job was the opposite: to stop the wine fizzing. What he did do was blending: he learned to assemble fruit from different villages into one better wine. The cuvée that carries his name leaves the same vintage in several waves: the first release after 8 to 9 years on the lees, P2 after some 15, P3 after 25 and more. So P2 and P3 are not older bottles but the same ones, left far longer with the yeast — and that is what reads in the glass as depth.",
 "it": "Dom Pérignon non ha inventato lo champagne — era il monaco benedettino responsabile della cantina del monastero di Hautvillers, e il suo compito era l'opposto: che il vino non spumeggiasse. Quello che fece davvero fu l'assemblaggio: imparò a mettere insieme uve di paesi diversi in un vino migliore. La cuvée che porta il suo nome esce dalla stessa annata in più riprese: la prima dopo 8-9 anni sui lieviti, la P2 dopo una quindicina, la P3 dopo 25 e più. P2 e P3 non sono dunque bottiglie più vecchie ma le stesse, lasciate molto più a lungo sui lieviti — ed è questo che nel bicchiere si sente come profondità.",
 "fr": "Dom Pérignon n'a pas inventé le champagne — il était le moine bénédictin en charge de la cave du monastère d'Hautvillers, et son travail était l'inverse : empêcher le vin de mousser. Ce qu'il a fait, c'est l'assemblage : il a appris à réunir des raisins de villages différents en un vin meilleur. La cuvée qui porte son nom sort du même millésime en plusieurs vagues : la première après 8 à 9 ans sur lies, la P2 après une quinzaine, la P3 après 25 et plus. P2 et P3 ne sont donc pas des bouteilles plus vieilles mais les mêmes, laissées bien plus longtemps avec les levures — et c'est cela qui se lit dans le verre comme de la profondeur.",
 "de": "Dom Pérignon hat den Champagner nicht erfunden — er war der Benediktinermönch, der den Klosterkeller in Hautvillers führte, und seine Aufgabe war das Gegenteil: dass der Wein nicht schäumt. Was er tat, war die Assemblage: Er lernte, Trauben aus verschiedenen Dörfern zu einem besseren Wein zusammenzusetzen. Die Cuvée, die seinen Namen trägt, verlässt denselben Jahrgang in mehreren Wellen: die erste Freigabe nach 8 bis 9 Jahren auf der Hefe, P2 nach etwa 15, P3 nach 25 und mehr. P2 und P3 sind also keine älteren Flaschen, sondern dieselben, nur viel länger auf der Hefe gelassen — und genau das liest sich im Glas als Tiefe.",
 "sl": "Dom Pérignon šampanjca ni izumil — bil je benediktinski menih, zadolžen za klet samostana v Hautvillersu, in njegova naloga je bila nasprotna: da vino ne peni. Kar je res naredil, je zvrst: naučil se je sestavljati grozdje iz različnih vasi v eno boljše vino. Cuvée, ki nosi njegovo ime, iz istega letnika izide v več valovih: prva izdaja po 8 do 9 letih na drožeh, P2 po kakih 15, P3 po 25 in več. P2 in P3 torej nista starejši steklenici, ampak isti, le veliko dlje puščeni s kvasovkami — in prav to se v kozarcu bere kot globina.",
 "es": "Dom Pérignon no inventó el champán — era el monje benedictino a cargo de la bodega del monasterio de Hautvillers, y su trabajo era el contrario: que el vino no burbujeara. Lo que sí hizo fue el ensamblaje: aprendió a juntar uvas de pueblos distintos en un vino mejor. La cuvée que lleva su nombre sale de la misma añada en varias oleadas: la primera tras 8 o 9 años sobre lías, la P2 tras unos 15, la P3 tras 25 y más. P2 y P3 no son, pues, botellas más viejas sino las mismas, dejadas mucho más tiempo con las levaduras — y eso es lo que en la copa se lee como profundidad.",
 "zh": "唐培里侬并没有发明香槟——他是奥维莱修道院里管酒窖的本笃会修士，而他的差事恰恰相反：让酒别起泡。他真正做成的是调配：他学会把不同村庄的果实拼成一款更好的酒。以他命名的这款酒，会从同一个年份分几次出厂：第一次在酒泥上待 8 到 9 年，P2 约 15 年，P3 则是 25 年以上。所以 P2、P3 并不是更老的瓶子，而是同一批，只是与酵母共处得久得多——落在杯子里，那便是所谓的深度。"
}

NEW["Egly-Ouriet"] = {
 "hr": "Vina ovdje ostaju na talogu 3 do 7 godina, a jedno i do 9 — višestruko dulje nego što zakon traži. Francis Egly, četvrti naraštaj u Ambonnayu, jednostavno ne žuri. Grand cru parcele su mu u Ambonnayu, Verzenayu i Bouzyju, dakle ondje gdje pinot crni u Champagni ima najviše mesa. Les Crayères dolazi s loza posađenih 1946. i 1947. u čistoj kredi. Šampanjac koji se pije kao veliko bijelo vino.",
 "en": "The wines here stay on their lees for 3 to 7 years, and one of them up to 9 — several times longer than the law asks. Francis Egly, fourth generation in Ambonnay, is simply in no hurry. His grand cru parcels are in Ambonnay, Verzenay and Bouzy, which is to say where Pinot Noir in Champagne has the most flesh. Les Crayères comes from vines planted in 1946 and 1947 in pure chalk. A champagne you drink the way you drink a great white wine.",
 "it": "Qui i vini restano sui lieviti da 3 a 7 anni, e uno fino a 9 — molte volte più a lungo di quanto chieda la legge. Francis Egly, quarta generazione ad Ambonnay, semplicemente non ha fretta. Le sue parcelle grand cru sono ad Ambonnay, Verzenay e Bouzy, cioè dove il pinot nero in Champagne ha più carne. Les Crayères viene da viti piantate nel 1946 e nel 1947 in pura creta. Uno champagne che si beve come un grande bianco.",
 "fr": "Ici les vins restent sur lies de 3 à 7 ans, et l'un d'eux jusqu'à 9 — plusieurs fois plus longtemps que ne l'exige la loi. Francis Egly, quatrième génération à Ambonnay, n'est tout simplement pas pressé. Ses parcelles grand cru sont à Ambonnay, Verzenay et Bouzy, c'est-à-dire là où le pinot noir de Champagne a le plus de chair. Les Crayères vient de vignes plantées en 1946 et 1947 dans la craie pure. Un champagne qui se boit comme un grand blanc.",
 "de": "Die Weine bleiben hier 3 bis 7 Jahre auf der Hefe, einer bis zu 9 — ein Vielfaches dessen, was das Gesetz verlangt. Francis Egly, vierte Generation in Ambonnay, hat es schlicht nicht eilig. Seine Grand-Cru-Parzellen liegen in Ambonnay, Verzenay und Bouzy, also dort, wo der Pinot Noir in der Champagne am meisten Fleisch hat. Les Crayères kommt von Reben, die 1946 und 1947 in reine Kreide gepflanzt wurden. Ein Champagner, den man trinkt wie einen großen Weißwein.",
 "sl": "Vina tu ostanejo na drožeh 3 do 7 let, eno pa celo 9 — večkratnik tega, kar zahteva zakon. Francis Egly, četrti rod v Ambonnayu, se preprosto ne mudi. Njegove grand cru parcele so v Ambonnayu, Verzenayu in Bouzyju, torej tam, kjer ima modri pinot v Champagni največ mesa. Les Crayères prihaja s trt, posajenih leta 1946 in 1947 v čisto kredo. Šampanjec, ki se pije kot veliko belo vino.",
 "es": "Aquí los vinos permanecen sobre lías de 3 a 7 años, y uno hasta 9 — varias veces más de lo que pide la ley. Francis Egly, cuarta generación en Ambonnay, sencillamente no tiene prisa. Sus parcelas grand cru están en Ambonnay, Verzenay y Bouzy, es decir donde la Pinot Noir de Champaña tiene más carne. Les Crayères viene de cepas plantadas en 1946 y 1947 en creta pura. Un champán que se bebe como un gran blanco.",
 "zh": "这里的酒要在酒泥上待 3 到 7 年，其中一款甚至 9 年——是法规要求的好几倍。安博内第四代的弗朗西斯·埃格利，就是不着急。他的特级园分布在安博内、韦尔泽奈和布齐，也就是香槟区黑皮诺最有肉感的地方。Les Crayères 来自 1946 与 1947 年种在纯白垩上的老藤。这是一款可以当伟大白葡萄酒来喝的香槟。"
}

NEW["De Sousa"] = {
 "hr": "U Avizeu se prezimena nasljeđuju zajedno s parcelama, a na ovoj etiketi stoji portugalsko: Manuel de Sousa došao je poslije Prvog svjetskog rata i ostao. Unuk Erick preveo je vinograde na biodinamiku i dobio Demeterov certifikat 1999. — u Champagni, gdje se tada tako nije radilo i gdje su ga gledali poprijeko. Danas kuću vode Charlotte, Julie i Valentin: 14 hektara same krede, loze u prosjeku 45 godina, a za vrhunske cuvée parcele starije od 60. Stara loza u Côte des Blancsu daje malo grožđa i puno soli.",
 "en": "In Avize surnames are inherited along with the plots, and this label carries a Portuguese one: Manuel de Sousa came after the First World War and stayed. His grandson Erick turned the vineyards biodynamic and took Demeter certification in 1999 — in Champagne, where nobody worked that way then and where he was looked at sideways for it. Charlotte, Julie and Valentin run the house now: 14 hectares of nothing but chalk, vines averaging 45 years, and for the top cuvées plots older than 60. Old vines on the Côte des Blancs give little fruit and a great deal of salt.",
 "it": "Ad Avize i cognomi si ereditano insieme alle parcelle, e su questa etichetta ce n'è uno portoghese: Manuel de Sousa arrivò dopo la Prima guerra mondiale e rimase. Il nipote Erick portò le vigne in biodinamica e ottenne la certificazione Demeter nel 1999 — in Champagne, dove allora non si lavorava così e dove lo si guardava di traverso. Oggi la casa è di Charlotte, Julie e Valentin: 14 ettari di pura creta, viti di 45 anni in media, e per le cuvée di vertice parcelle oltre i 60. La vigna vecchia sulla Côte des Blancs dà poca uva e molto sale.",
 "fr": "À Avize, les noms se transmettent avec les parcelles, et sur cette étiquette il y en a un portugais : Manuel de Sousa est arrivé après la Première Guerre mondiale et il est resté. Son petit-fils Erick a converti les vignes en biodynamie et obtenu la certification Demeter en 1999 — en Champagne, où l'on ne travaillait pas ainsi et où on le regardait de travers. Charlotte, Julie et Valentin mènent la maison aujourd'hui : 14 hectares de craie pure, des vignes de 45 ans en moyenne, et pour les grandes cuvées des parcelles de plus de 60. La vieille vigne de la Côte des Blancs donne peu de raisin et beaucoup de sel.",
 "de": "In Avize erbt man Nachnamen zusammen mit den Parzellen, und auf diesem Etikett steht ein portugiesischer: Manuel de Sousa kam nach dem Ersten Weltkrieg und blieb. Sein Enkel Erick stellte die Weinberge auf Biodynamie um und holte 1999 das Demeter-Zertifikat — in der Champagne, wo damals niemand so arbeitete und wo man ihn dafür schief ansah. Heute führen Charlotte, Julie und Valentin das Haus: 14 Hektar reine Kreide, Reben im Schnitt 45 Jahre alt, für die Spitzencuvées Parzellen über 60. Alte Reben an der Côte des Blancs geben wenig Frucht und sehr viel Salz.",
 "sl": "V Avizeju se priimki dedujejo skupaj s parcelami, na tej etiketi pa stoji portugalski: Manuel de Sousa je prišel po prvi svetovni vojni in ostal. Vnuk Erick je vinograde prevedel na biodinamiko in leta 1999 dobil Demetrin certifikat — v Champagni, kjer se takrat tako ni delalo in kjer so ga gledali postrani. Danes hišo vodijo Charlotte, Julie in Valentin: 14 hektarov same krede, trte v povprečju 45 let, za vrhunske cuvéeje pa parcele, starejše od 60. Stara trta na Côte des Blancs da malo grozdja in veliko soli.",
 "es": "En Avize los apellidos se heredan junto con las parcelas, y en esta etiqueta hay uno portugués: Manuel de Sousa llegó después de la Primera Guerra Mundial y se quedó. Su nieto Erick pasó las viñas a biodinámica y obtuvo la certificación Demeter en 1999 — en Champaña, donde entonces nadie trabajaba así y donde lo miraban de reojo. Hoy llevan la casa Charlotte, Julie y Valentin: 14 hectáreas de pura creta, cepas de 45 años de media y, para las grandes cuvées, parcelas de más de 60. La viña vieja de la Côte des Blancs da poca uva y mucha sal.",
 "zh": "在阿维兹，姓氏是随园地一起继承的，而这张酒标上却是个葡萄牙姓：曼努埃尔·德索萨在一战后来到这里，就此留下。孙子埃里克把葡萄园转为生物动力，1999 年拿到 Demeter 认证——在当时的香槟区，没有人这么做，他也因此被斜眼看待。如今由夏洛特、朱莉与瓦朗坦掌管：14 公顷纯白垩，藤龄平均 45 年，顶级酒款的园块则超过 60 年。白丘的老藤给的果实很少，盐味却很足。"
}

NEW["Château d'Yquem"] = {
 "hr": "Berači kroz vinograd prolaze iznova i iznova, katkad i 13 puta, i svaki put uzimaju samo bobice koje je plemenita plijesan pogodila točno koliko treba. Jedan trs u prosjeku da jednu čašu vina — drugdje da bocu. A kad godina ne uspije, Yquema jednostavno nema: ime se ne stavlja na bocu, a u 20. stoljeću dogodilo se to 9 puta, posljednji put 1992., pa opet 2012. Vino koje ima pravo ne postojati.",
 "en": "The pickers go through the vineyard again and again, sometimes 13 times, and each time take only the berries the noble rot has caught exactly as much as it should. One vine gives, on average, one glass of wine — elsewhere it gives a bottle. And when a year does not come off, there simply is no Yquem: the name does not go on the bottle, which in the 20th century happened 9 times, most recently in 1992, and again in 2012. A wine with the right not to exist.",
 "it": "I vendemmiatori passano nella vigna di nuovo e di nuovo, a volte 13 volte, e ogni volta prendono solo gli acini che la muffa nobile ha colpito esattamente quanto serve. Una vite dà in media un bicchiere di vino — altrove ne dà una bottiglia. E quando l'annata non riesce, l'Yquem semplicemente non c'è: il nome non va in bottiglia, e nel Novecento è successo 9 volte, l'ultima nel 1992, e poi ancora nel 2012. Un vino che ha il diritto di non esistere.",
 "fr": "Les vendangeurs passent dans la vigne encore et encore, parfois 13 fois, et ne prennent chaque fois que les baies que la pourriture noble a touchées juste comme il faut. Un cep donne en moyenne un verre de vin — ailleurs il donne une bouteille. Et quand l'année ne se fait pas, il n'y a tout simplement pas d'Yquem : le nom ne va pas sur la bouteille, ce qui au XXe siècle est arrivé 9 fois, la dernière en 1992, puis de nouveau en 2012. Un vin qui a le droit de ne pas exister.",
 "de": "Die Leser gehen wieder und wieder durch den Weinberg, manchmal 13 Mal, und nehmen jedes Mal nur die Beeren, die die Edelfäule genau richtig erwischt hat. Ein Stock gibt im Schnitt ein Glas Wein — anderswo gibt er eine Flasche. Und wenn ein Jahr nicht gelingt, gibt es schlicht keinen Yquem: Der Name kommt nicht auf die Flasche, was im 20. Jahrhundert 9 Mal geschah, zuletzt 1992, und dann wieder 2012. Ein Wein mit dem Recht, nicht zu existieren.",
 "sl": "Trgači gredo skozi vinograd znova in znova, včasih tudi 13-krat, in vsakič vzamejo le jagode, ki jih je plemenita plesen zadela točno prav. Ena trta da v povprečju en kozarec vina — drugod da steklenico. In kadar letnik ne uspe, Yquema preprosto ni: imena ne dajo na steklenico, kar se je v 20. stoletju zgodilo 9-krat, nazadnje leta 1992, nato spet 2012. Vino, ki ima pravico, da ga ni.",
 "es": "Los vendimiadores pasan por la viña una y otra vez, a veces 13 veces, y cada vez toman sólo las bayas que la podredumbre noble ha tocado exactamente lo justo. Una cepa da de media una copa de vino — en otros sitios da una botella. Y cuando el año no sale, sencillamente no hay Yquem: el nombre no va a la botella, algo que en el siglo XX ocurrió 9 veces, la última en 1992, y de nuevo en 2012. Un vino con derecho a no existir.",
 "zh": "采收的人一遍又一遍走进葡萄园，有时多达 13 次，每次只摘那些被贵腐恰到好处侵染的果粒。一株藤平均只给一杯酒——换个地方，它能给一瓶。而当年份不成，就干脆没有伊甘：名字不会印上瓶身。20 世纪里这样的事发生过 9 次，最近一次是 1992 年，之后 2012 年又一次。一款有权不存在的酒。"
}

NEW["Jacques Selosse"] = {
 "hr": "Trebalo mu je 6 godina prepirke sa šampanjskim odborom da dobije ono što je vidio u Jerezu: soleru. Dopustili su mu je 1986. Anselme Selosse učio je sedamdesetih u Burgundiji, kod ljudi koji su vjerovali da vino nastaje u vinogradu, i to je uvjerenje donio natrag u Avize — gdje ga tada nitko nije dijelio. Na istom putu po Španjolskoj vidio je i katedrale bačava Lópeza de Heredije u Rioji, koji je i sam na ovoj karti. Les Carelles jedan je od šest njegovih pojedinačnih položaja.",
 "en": "It took him 6 years of argument with Champagne's governing body to be allowed what he had seen in Jerez: a solera. They let him have it in 1986. Anselme Selosse trained in Burgundy in the 1970s, among people who believed wine is made in the vineyard, and brought that conviction back to Avize — where nobody then shared it. On the same trip through Spain he saw the cathedrals of barrels at López de Heredia in Rioja, who are themselves on this list. Les Carelles is one of his six single vineyards.",
 "it": "Gli sono serviti 6 anni di discussioni con l'ente della Champagne per ottenere ciò che aveva visto a Jerez: una solera. Gliel'hanno concessa nel 1986. Anselme Selosse si era formato negli anni Settanta in Borgogna, fra gente convinta che il vino si faccia in vigna, e quella convinzione l'ha riportata ad Avize — dove allora non la condivideva nessuno. Nello stesso viaggio in Spagna aveva visto le cattedrali di botti di López de Heredia in Rioja, anch'essi su questa carta. Les Carelles è uno dei suoi sei cru.",
 "fr": "Il lui a fallu 6 ans de discussions avec l'organisme de la Champagne pour obtenir ce qu'il avait vu à Jerez : une solera. On la lui a accordée en 1986. Anselme Selosse s'était formé dans les années 1970 en Bourgogne, chez des gens convaincus que le vin se fait à la vigne, et il a rapporté cette conviction à Avize — où personne alors ne la partageait. Au cours du même voyage en Espagne, il avait vu les cathédrales de fûts de López de Heredia en Rioja, eux aussi sur cette carte. Les Carelles est l'un de ses six lieux-dits.",
 "de": "Er brauchte 6 Jahre Streit mit dem Champagne-Verband, um zu bekommen, was er in Jerez gesehen hatte: eine Solera. 1986 wurde sie ihm erlaubt. Anselme Selosse hatte in den 1970ern im Burgund gelernt, bei Leuten, die glaubten, Wein entstehe im Weinberg, und diese Überzeugung nach Avize zurückgebracht — wo sie damals niemand teilte. Auf derselben Reise durch Spanien sah er die Kathedralen aus Fässern bei López de Heredia in der Rioja, die selbst auf dieser Karte stehen. Les Carelles ist eine seiner sechs Einzellagen.",
 "sl": "Potreboval je 6 let prerekanja s šampanjskim odborom, da je dobil to, kar je videl v Jerezu: solero. Dovolili so mu jo leta 1986. Anselme Selosse se je v sedemdesetih učil v Burgundiji, pri ljudeh, ki so verjeli, da vino nastane v vinogradu, in to prepričanje je prinesel nazaj v Avize — kjer ga takrat ni delil nihče. Na isti poti po Španiji je videl tudi katedrale sodov pri Lópezu de Herediji v Rioji, ki je prav tako na tej karti. Les Carelles je ena od njegovih šestih posameznih leg.",
 "es": "Le hicieron falta 6 años de discusión con el organismo de Champaña para conseguir lo que había visto en Jerez: una solera. Se la permitieron en 1986. Anselme Selosse se formó en los años setenta en Borgoña, entre gente que creía que el vino se hace en la viña, y trajo esa convicción de vuelta a Avize — donde entonces no la compartía nadie. En ese mismo viaje por España vio las catedrales de barricas de López de Heredia en Rioja, que están también en esta carta. Les Carelles es uno de sus seis pagos.",
 "zh": "他和香槟产区管理机构争了 6 年，才拿到他在赫雷斯看见的那样东西：索莱拉。1986 年，他们终于允许了。安塞尔姆·瑟洛斯在七十年代于勃艮第学艺，身边人都相信酒是在葡萄园里做成的，他把这个信念带回阿维兹——当时那里没有人认同。也正是在那趟西班牙之行里，他看见了里奥哈 López de Heredia 的橡木桶大教堂，那家也在这份酒单上。Les Carelles 是他六块单一园之一。"
}

p = "data/producers.json"
raw = open(p, "r", encoding="utf-8", newline="").read()
data = json.loads(raw)
prods = data["producers"]
for key, langs in NEW.items():
    assert key in prods, key
    for lg, text in langs.items():
        assert lg in prods[key]["blurb"], (key, lg)
        prods[key]["blurb"][lg] = text
    print("%-20s %d languages, hr %3d chars" % (key, len(langs), len(langs["hr"])))
open(p, "w", encoding="utf-8", newline="").write((json.dumps(data, ensure_ascii=False, indent=1) + "\n").replace("\n", "\r\n"))
print("\nwritten")
